package com.sun.java.swing.plaf.gtk.resources;

import java.util.ListResourceBundle;

public final class gtk extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "FileChooser.acceptAllFileFilterText", "All Files" },
            { "FileChooser.cancelButtonMnemonic", "67" },
            { "FileChooser.cancelButtonText", "Cancel" },
            { "FileChooser.cancelButtonToolTipText", "Abort file chooser dialog." },
            { "FileChooser.deleteFileButtonMnemonic", "76" },
            { "FileChooser.deleteFileButtonText", "Delete File" },
            { "FileChooser.filesLabelMnemonic", "70" },
            { "FileChooser.filesLabelText", "Files" },
            { "FileChooser.filterLabelText", "Filter:" },
            { "FileChooser.foldersLabelMnemonic", "68" },
            { "FileChooser.foldersLabelText", "Folders" },
            { "FileChooser.newFolderButtonMnemonic", "78" },
            { "FileChooser.newFolderButtonText", "New Folder" },
            { "FileChooser.newFolderDialogText", "Folder name:" },
            { "FileChooser.openButtonMnemonic", "79" },
            { "FileChooser.openButtonText", "OK" },
            { "FileChooser.openButtonToolTipText", "Open selected file." },
            { "FileChooser.openDialogTitleText", "Open" },
            { "FileChooser.pathLabelMnemonic", "83" },
            { "FileChooser.pathLabelText", "Selection:" },
            { "FileChooser.renameFileButtonMnemonic", "82" },
            { "FileChooser.renameFileButtonText", "Rename File" },
            { "FileChooser.renameFileDialogText", "Rename file \"{0}\" to" },
            { "FileChooser.renameFileErrorText", "Error renaming file \"{0}\" to \"{1}\"" },
            { "FileChooser.renameFileErrorTitle", "Error " },
            { "FileChooser.saveButtonMnemonic", "79" },
            { "FileChooser.saveButtonText", "OK" },
            { "FileChooser.saveButtonToolTipText", "Save selected file." },
            { "FileChooser.saveDialogTitleText", "Save" },
            { "GTKColorChooserPanel.blueMnemonic", "66" },
            { "GTKColorChooserPanel.blueText", "Blue:" },
            { "GTKColorChooserPanel.colorNameMnemonic", "78" },
            { "GTKColorChooserPanel.colorNameText", "Color Name:" },
            { "GTKColorChooserPanel.greenMnemonic", "71" },
            { "GTKColorChooserPanel.greenText", "Green:" },
            { "GTKColorChooserPanel.hueMnemonic", "72" },
            { "GTKColorChooserPanel.hueText", "Hue:" },
            { "GTKColorChooserPanel.mnemonic", "71" },
            { "GTKColorChooserPanel.nameText", "GTK Color Chooser" },
            { "GTKColorChooserPanel.redMnemonic", "69" },
            { "GTKColorChooserPanel.redText", "Red:" },
            { "GTKColorChooserPanel.saturationMnemonic", "83" },
            { "GTKColorChooserPanel.saturationText", "Saturation:" },
            { "GTKColorChooserPanel.valueMnemonic", "86" },
            { "GTKColorChooserPanel.valueText", "Value:" },
            { "OptionPane.cancelButtonMnemonic", "67" },
            { "OptionPane.okButtonMnemonic", "79" },
        };
    }
}
