package com.sun.java.swing.plaf.gtk.resources;

import java.util.ListResourceBundle;

public final class gtk_de extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "FileChooser.acceptAllFileFilterText", "Alle Dateien" },
            { "FileChooser.cancelButtonMnemonic", "83" },
            { "FileChooser.cancelButtonText", "Abbrechen" },
            { "FileChooser.cancelButtonToolTipText", "Farbauswahl abbrechen" },
            { "FileChooser.deleteFileButtonMnemonic", "76" },
            { "FileChooser.deleteFileButtonText", "Datei l\u00F6schen" },
            { "FileChooser.filesLabelMnemonic", "70" },
            { "FileChooser.filesLabelText", "Dateien" },
            { "FileChooser.filterLabelText", "Filter:" },
            { "FileChooser.foldersLabelMnemonic", "82" },
            { "FileChooser.foldersLabelText", "Ordner" },
            { "FileChooser.newFolderButtonMnemonic", "78" },
            { "FileChooser.newFolderButtonText", "Neuer Ordner" },
            { "FileChooser.newFolderDialogText", "Ordnername:" },
            { "FileChooser.openButtonMnemonic", "79" },
            { "FileChooser.openButtonText", "OK" },
            { "FileChooser.openButtonToolTipText", "Ausgew\u00E4hlte Datei \u00F6ffnen" },
            { "FileChooser.openDialogTitleText", "\u00D6ffnen" },
            { "FileChooser.pathLabelMnemonic", "83" },
            { "FileChooser.pathLabelText", "Auswahl:" },
            { "FileChooser.renameFileButtonMnemonic", "87" },
            { "FileChooser.renameFileButtonText", "Datei umbenennen" },
            { "FileChooser.renameFileDialogText", "Datei \"{0}\" umbenennen in" },
            { "FileChooser.renameFileErrorText", "Fehler beim Umbenennen der Datei \"{0}\" in \"{1}\"" },
            { "FileChooser.renameFileErrorTitle", "Fehler " },
            { "FileChooser.saveButtonMnemonic", "69" },
            { "FileChooser.saveButtonText", "Speichern" },
            { "FileChooser.saveButtonToolTipText", "Ausgew\u00E4hlte Datei speichern" },
            { "FileChooser.saveDialogTitleText", "Speichern" },
            { "GTKColorChooserPanel.blueMnemonic", "66" },
            { "GTKColorChooserPanel.blueText", "Blau:" },
            { "GTKColorChooserPanel.colorNameMnemonic", "78" },
            { "GTKColorChooserPanel.colorNameText", "Name der Farbe:" },
            { "GTKColorChooserPanel.greenMnemonic", "71" },
            { "GTKColorChooserPanel.greenText", "Gr\u00FCn:" },
            { "GTKColorChooserPanel.hueMnemonic", "70" },
            { "GTKColorChooserPanel.hueText", "Farbton:" },
            { "GTKColorChooserPanel.mnemonic", "71" },
            { "GTKColorChooserPanel.nameText", "GTK-Farbauswahl" },
            { "GTKColorChooserPanel.redMnemonic", "82" },
            { "GTKColorChooserPanel.redText", "Rot:" },
            { "GTKColorChooserPanel.saturationMnemonic", "83" },
            { "GTKColorChooserPanel.saturationText", "S\u00E4ttigung:" },
            { "GTKColorChooserPanel.valueMnemonic", "87" },
            { "GTKColorChooserPanel.valueText", "Wert:" },
            { "OptionPane.cancelButtonMnemonic", "83" },
            { "OptionPane.okButtonMnemonic", "79" },
        };
    }
}
