package com.sun.java.swing.plaf.gtk.resources;

import java.util.ListResourceBundle;

public final class gtk_fr extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "FileChooser.acceptAllFileFilterText", "Tous les fichiers" },
            { "FileChooser.cancelButtonMnemonic", "70" },
            { "FileChooser.cancelButtonText", "Annuler" },
            { "FileChooser.cancelButtonToolTipText", "Abandonner la bo\u00EEte de dialogue du s\u00E9lectionneur de fichier." },
            { "FileChooser.deleteFileButtonMnemonic", "76" },
            { "FileChooser.deleteFileButtonText", "Supprimer le fichier" },
            { "FileChooser.filesLabelMnemonic", "70" },
            { "FileChooser.filesLabelText", "Fichiers" },
            { "FileChooser.filterLabelText", "Filtre :" },
            { "FileChooser.foldersLabelMnemonic", "71" },
            { "FileChooser.foldersLabelText", "Dossiers" },
            { "FileChooser.newFolderButtonMnemonic", "78" },
            { "FileChooser.newFolderButtonText", "Nouveau dossier" },
            { "FileChooser.newFolderDialogText", "Nom de dossier:" },
            { "FileChooser.openButtonMnemonic", "79" },
            { "FileChooser.openButtonText", "OK" },
            { "FileChooser.openButtonToolTipText", "Ouvrir le fichier s\u00E9lectionn\u00E9." },
            { "FileChooser.openDialogTitleText", "Ouvrir" },
            { "FileChooser.pathLabelMnemonic", "83" },
            { "FileChooser.pathLabelText", "S\u00E9lection\u00A0:" },
            { "FileChooser.renameFileButtonMnemonic", "82" },
            { "FileChooser.renameFileButtonText", "Renommer le fichier" },
            { "FileChooser.renameFileDialogText", "Renommer le fichier \"{0}\" en" },
            { "FileChooser.renameFileErrorText", "Erreur lors du changement de nom du fichier \"{0}\" en \"{1}\"" },
            { "FileChooser.renameFileErrorTitle", "Erreur " },
            { "FileChooser.saveButtonMnemonic", "79" },
            { "FileChooser.saveButtonText", "Enregistrer" },
            { "FileChooser.saveButtonToolTipText", "Enregistrer le fichier s\u00E9lectionn\u00E9." },
            { "FileChooser.saveDialogTitleText", "Enregistrer" },
            { "GTKColorChooserPanel.blueMnemonic", "66" },
            { "GTKColorChooserPanel.blueText", "Bleu\u00A0:" },
            { "GTKColorChooserPanel.colorNameMnemonic", "78" },
            { "GTKColorChooserPanel.colorNameText", "Nom de la couleur\u00A0:" },
            { "GTKColorChooserPanel.greenMnemonic", "69" },
            { "GTKColorChooserPanel.greenText", "Vert\u00A0:" },
            { "GTKColorChooserPanel.hueMnemonic", "84" },
            { "GTKColorChooserPanel.hueText", "Teinte\u00A0:" },
            { "GTKColorChooserPanel.mnemonic", "71" },
            { "GTKColorChooserPanel.nameText", "S\u00E9lectionneur de couleur GTK" },
            { "GTKColorChooserPanel.redMnemonic", "82" },
            { "GTKColorChooserPanel.redText", "Rouge\u00A0:" },
            { "GTKColorChooserPanel.saturationMnemonic", "83" },
            { "GTKColorChooserPanel.saturationText", "Saturation\u00A0:" },
            { "GTKColorChooserPanel.valueMnemonic", "86" },
            { "GTKColorChooserPanel.valueText", "Valeur\u00A0:" },
            { "OptionPane.cancelButtonMnemonic", "67" },
            { "OptionPane.okButtonMnemonic", "79" },
        };
    }
}
