package com.sun.java.swing.plaf.gtk.resources;

import java.util.ListResourceBundle;

public final class gtk_es extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "FileChooser.acceptAllFileFilterText", "Todos los archivos" },
            { "FileChooser.cancelButtonMnemonic", "67" },
            { "FileChooser.cancelButtonText", "Cancelar" },
            { "FileChooser.cancelButtonToolTipText", "Cancelar cuadro de di\u00E1logo de selecci\u00F3n de archivos." },
            { "FileChooser.deleteFileButtonMnemonic", "76" },
            { "FileChooser.deleteFileButtonText", "Eliminar archivo" },
            { "FileChooser.filesLabelMnemonic", "70" },
            { "FileChooser.filesLabelText", "Archivos" },
            { "FileChooser.filterLabelText", "Filtro:" },
            { "FileChooser.foldersLabelMnemonic", "74" },
            { "FileChooser.foldersLabelText", "Carpetas" },
            { "FileChooser.newFolderButtonMnemonic", "78" },
            { "FileChooser.newFolderButtonText", "Nueva carpeta" },
            { "FileChooser.newFolderDialogText", "Nombre de la carpeta:" },
            { "FileChooser.openButtonMnemonic", "79" },
            { "FileChooser.openButtonText", "Aceptar" },
            { "FileChooser.openButtonToolTipText", "Abrir el archivo seleccionado." },
            { "FileChooser.openDialogTitleText", "Abrir" },
            { "FileChooser.pathLabelMnemonic", "83" },
            { "FileChooser.pathLabelText", "Selecci\u00F3n:" },
            { "FileChooser.renameFileButtonMnemonic", "82" },
            { "FileChooser.renameFileButtonText", "Renombrar archivo" },
            { "FileChooser.renameFileDialogText", "Cambiar el nombre del archivo \"{0}\" por" },
            { "FileChooser.renameFileErrorText", "Error al cambiar el nombre del archivo \"{0}\" por \"{1}\"" },
            { "FileChooser.renameFileErrorTitle", "Error " },
            { "FileChooser.saveButtonMnemonic", "82" },
            { "FileChooser.saveButtonText", "Guardar" },
            { "FileChooser.saveButtonToolTipText", "Guardar el archivo seleccionado." },
            { "FileChooser.saveDialogTitleText", "Guardar" },
            { "GTKColorChooserPanel.blueMnemonic", "65" },
            { "GTKColorChooserPanel.blueText", "Azul:" },
            { "GTKColorChooserPanel.colorNameMnemonic", "78" },
            { "GTKColorChooserPanel.colorNameText", "Nombre del color:" },
            { "GTKColorChooserPanel.greenMnemonic", "86" },
            { "GTKColorChooserPanel.greenText", "Verde:" },
            { "GTKColorChooserPanel.hueMnemonic", "84" },
            { "GTKColorChooserPanel.hueText", "Tono:" },
            { "GTKColorChooserPanel.mnemonic", "71" },
            { "GTKColorChooserPanel.nameText", "Selector de color para GTK" },
            { "GTKColorChooserPanel.redMnemonic", "82" },
            { "GTKColorChooserPanel.redText", "Rojo:" },
            { "GTKColorChooserPanel.saturationMnemonic", "83" },
            { "GTKColorChooserPanel.saturationText", "Saturaci\u00F3n:" },
            { "GTKColorChooserPanel.valueMnemonic", "65" },
            { "GTKColorChooserPanel.valueText", "Valor:" },
            { "OptionPane.cancelButtonMnemonic", "67" },
            { "OptionPane.okButtonMnemonic", "79" },
        };
    }
}
