package com.sun.java.swing.plaf.gtk.resources;

import java.util.ListResourceBundle;

public final class gtk_sv extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "FileChooser.acceptAllFileFilterText", "Alla filer" },
            { "FileChooser.cancelButtonMnemonic", "83" },
            { "FileChooser.cancelButtonText", "Avbryt" },
            { "FileChooser.cancelButtonToolTipText", "St\u00E4ng dialogrutan f\u00F6r filval." },
            { "FileChooser.deleteFileButtonMnemonic", "76" },
            { "FileChooser.deleteFileButtonText", "Ta bort fil" },
            { "FileChooser.filesLabelMnemonic", "70" },
            { "FileChooser.filesLabelText", "Filer" },
            { "FileChooser.filterLabelText", "Filter:" },
            { "FileChooser.foldersLabelMnemonic", "82" },
            { "FileChooser.foldersLabelText", "Mappar" },
            { "FileChooser.newFolderButtonMnemonic", "70" },
            { "FileChooser.newFolderButtonText", "Ny mapp" },
            { "FileChooser.newFolderDialogText", "Mapp:" },
            { "FileChooser.openButtonMnemonic", "79" },
            { "FileChooser.openButtonText", "OK" },
            { "FileChooser.openButtonToolTipText", "\u00D6ppna den markerade filen." },
            { "FileChooser.openDialogTitleText", "\u00D6ppna" },
            { "FileChooser.pathLabelMnemonic", "77" },
            { "FileChooser.pathLabelText", "Markeringen:" },
            { "FileChooser.renameFileButtonMnemonic", "84" },
            { "FileChooser.renameFileButtonText", "Byt namn p\u00E5 fil" },
            { "FileChooser.renameFileDialogText", "Byt namn p\u00E5 fil \"{0}\" till" },
            { "FileChooser.renameFileErrorText", "Det gick inte att byta namn p\u00E5 fil \"{0}\" till \"{1}\"" },
            { "FileChooser.renameFileErrorTitle", "Fel " },
            { "FileChooser.saveButtonMnemonic", "80" },
            { "FileChooser.saveButtonText", "Spara" },
            { "FileChooser.saveButtonToolTipText", "Spara den markerade filen." },
            { "FileChooser.saveDialogTitleText", "Spara" },
            { "GTKColorChooserPanel.blueMnemonic", "66" },
            { "GTKColorChooserPanel.blueText", "Bl\u00E5:" },
            { "GTKColorChooserPanel.colorNameMnemonic", "70" },
            { "GTKColorChooserPanel.colorNameText", "F\u00E4rgnamn:" },
            { "GTKColorChooserPanel.greenMnemonic", "71" },
            { "GTKColorChooserPanel.greenText", "Gr\u00F6n:" },
            { "GTKColorChooserPanel.hueMnemonic", "78" },
            { "GTKColorChooserPanel.hueText", "Nyans:" },
            { "GTKColorChooserPanel.mnemonic", "71" },
            { "GTKColorChooserPanel.nameText", "GTK F\u00E4rgv\u00E4ljaren" },
            { "GTKColorChooserPanel.redMnemonic", "82" },
            { "GTKColorChooserPanel.redText", "R\u00F6d:" },
            { "GTKColorChooserPanel.saturationMnemonic", "77" },
            { "GTKColorChooserPanel.saturationText", "M\u00E4ttnad:" },
            { "GTKColorChooserPanel.valueMnemonic", "86" },
            { "GTKColorChooserPanel.valueText", "V\u00E4rde:" },
            { "OptionPane.cancelButtonMnemonic", "83" },
            { "OptionPane.okButtonMnemonic", "79" },
        };
    }
}
