package sun.print.resources;

import java.util.ListResourceBundle;

public final class serviceui_fr extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "Automatic-Feeder", "Alimentation automatique" },
            { "Cassette", "Cassette" },
            { "Form-Source", "Source du formulaire" },
            { "Large-Format", "Grand format" },
            { "Manual-Envelope", "Enveloppe (manuel)" },
            { "Small-Format", "Petit format" },
            { "Tractor-Feeder", "Alimentation en continu" },
            { "a", "Ing\u00E9nierie A" },
            { "accepting-jobs", "Acceptation des t\u00E2ches" },
            { "auto-select", "S\u00E9lection automatique" },
            { "b", "Ing\u00E9nierie B" },
            { "border.chromaticity", "Couleur" },
            { "border.copies", "Copies" },
            { "border.jobattributes", "Attributs de t\u00E2che" },
            { "border.margins", "Marges" },
            { "border.media", "Support" },
            { "border.orientation", "Orientation" },
            { "border.printrange", "Plage d'impression" },
            { "border.printservice", "Service d'impression" },
            { "border.quality", "Qualit\u00E9" },
            { "border.sides", "C\u00F4t\u00E9s" },
            { "bottom", "Bas" },
            { "button.cancel", "Annuler" },
            { "button.ok", "OK" },
            { "button.print", "Imprimer" },
            { "button.properties", "P&ropri\u00E9t\u00E9s..." },
            { "c", "Ing\u00E9nierie C" },
            { "checkbox.collate", "&Collationner" },
            { "checkbox.jobsheets", "Page de &banni\u00E8re" },
            { "checkbox.printtofile", "Imprimer dans un &fichier" },
            { "d", "Ing\u00E9nierie D" },
            { "dialog.noprintermsg", "Service d'impression introuvable." },
            { "dialog.overwrite", "Ce fichier existe d\u00E9j\u00E0. Remplacer le fichier existant ?" },
            { "dialog.owtitle", "Imprimer dans un fichier" },
            { "dialog.printtitle", "Imprimer" },
            { "dialog.printtofile", "Imprimer dans un fichier" },
            { "dialog.pstitle", "Mise en page" },
            { "dialog.writeerror", "Impossible d'\u00E9crire dans le fichier :" },
            { "e", "Ing\u00E9nierie E" },
            { "envelope", "Enveloppe" },
            { "error.destination", "Nom de fichier non valide ; recommencez" },
            { "error.pagerange", "Plage de pages non valide. Sp\u00E9cifiez les valeurs de nouveau (ex. : 1-3,5,7-10)" },
            { "executive", "Administratif" },
            { "folio", "Folio" },
            { "invite-envelope", "Enveloppe invitation" },
            { "invoice", "Facture" },
            { "iso-2a0", "2A0 (ISO/DIN & JIS)" },
            { "iso-4a0", "4A0 (ISO/DIN & JIS)" },
            { "iso-a0", "A0 (ISO/DIN & JIS)" },
            { "iso-a1", "A1 (ISO/DIN & JIS)" },
            { "iso-a10", "A10 (ISO/DIN & JIS)" },
            { "iso-a2", "A2 (ISO/DIN & JIS)" },
            { "iso-a3", "A3 (ISO/DIN & JIS)" },
            { "iso-a4", "A4 (ISO/DIN & JIS)" },
            { "iso-a5", "A5 (ISO/DIN & JIS)" },
            { "iso-a6", "A6 (ISO/DIN & JIS)" },
            { "iso-a7", "A7 (ISO/DIN & JIS)" },
            { "iso-a8", "A8 (ISO/DIN & JIS)" },
            { "iso-a9", "A9 (ISO/DIN & JIS)" },
            { "iso-b0", "B0 (ISO/DIN)" },
            { "iso-b1", "B1 (ISO/DIN)" },
            { "iso-b10", "B10 (ISO/DIN)" },
            { "iso-b2", "B2 (ISO/DIN)" },
            { "iso-b3", "B3 (ISO/DIN)" },
            { "iso-b4", "B4 (ISO/DIN)" },
            { "iso-b5", "B5 (ISO/DIN)" },
            { "iso-b6", "B6 (ISO/DIN)" },
            { "iso-b7", "B7 (ISO/DIN)" },
            { "iso-b8", "B8 (ISO/DIN)" },
            { "iso-b9", "B9 (ISO/DIN)" },
            { "iso-c0", "C0 (ISO/DIN)" },
            { "iso-c1", "C1 (ISO/DIN)" },
            { "iso-c10", "C10 (ISO/DIN)" },
            { "iso-c2", "C2 (ISO/DIN)" },
            { "iso-c3", "C3 (ISO/DIN)" },
            { "iso-c4", "C4 (ISO/DIN)" },
            { "iso-c5", "C5 (ISO/DIN)" },
            { "iso-c6", "C6 (ISO/DIN)" },
            { "iso-c7", "C7 (ISO/DIN)" },
            { "iso-c8", "C8 (ISO/DIN)" },
            { "iso-c9", "C9 (ISO/DIN)" },
            { "iso-designated-long", "Long ISO" },
            { "italian-envelope", "Enveloppe Italie" },
            { "italy-envelope", "Enveloppe Italie" },
            { "japanese-postcard", "Carte postale (JIS)" },
            { "jis-b0", "B0 (JIS)" },
            { "jis-b1", "B1 (JIS)" },
            { "jis-b10", "B10 (JIS)" },
            { "jis-b2", "B2 (JIS)" },
            { "jis-b3", "B3 (JIS)" },
            { "jis-b4", "B4 (JIS)" },
            { "jis-b5", "B5 (JIS)" },
            { "jis-b6", "B6 (JIS)" },
            { "jis-b7", "B7 (JIS)" },
            { "jis-b8", "B8 (JIS)" },
            { "jis-b9", "B9 (JIS)" },
            { "label.bottommargin", "&bas" },
            { "label.inches", "(po)" },
            { "label.info", "Infos :" },
            { "label.jobname", "Nom du tra&vail :" },
            { "label.leftmargin", "gauc&he" },
            { "label.millimetres", "(mm)" },
            { "label.numcopies", "Nombre de c&opies :" },
            { "label.priority", "P&riorit\u00E9 :" },
            { "label.psname", "&Nom :" },
            { "label.pstype", "Type :" },
            { "label.rangeto", "A" },
            { "label.rightmargin", "&droite" },
            { "label.size", "Tai&lle :" },
            { "label.source", "Sour&ce :" },
            { "label.status", "Statut :" },
            { "label.topmargin", "&haut" },
            { "label.username", "Nom ut&ilisateur :" },
            { "large-capacity", "Grande capacit\u00E9" },
            { "ledger", "Fiche" },
            { "main", "Principal" },
            { "manual", "Manuel" },
            { "middle", "Centre" },
            { "monarch-envelope", "Enveloppe Monarch" },
            { "na-10x13-envelope", "Enveloppe 10x15" },
            { "na-10x14-envelope", "Enveloppe 10x15" },
            { "na-10x15-envelope", "Enveloppe 10x15" },
            { "na-5x7", "Papier 5x7 po" },
            { "na-6x9-envelope", "Enveloppe 6x9" },
            { "na-7x9-envelope", "Enveloppe 6x7" },
            { "na-8x10", "Papier 8x10 po" },
            { "na-9x11-envelope", "Enveloppe 9x11" },
            { "na-9x12-envelope", "Enveloppe 9x12" },
            { "na-legal", "L\u00E9gal" },
            { "na-letter", "Lettre" },
            { "na-number-10-envelope", "Enveloppe n\u00B010" },
            { "na-number-11-envelope", "Enveloppe n\u00B011" },
            { "na-number-12-envelope", "Enveloppe n\u00B012" },
            { "na-number-14-envelope", "Enveloppe n\u00B014" },
            { "na-number-9-envelope", "Enveloppe n\u00B09" },
            { "not-accepting-jobs", "Refus des t\u00E2ches" },
            { "oufuko-postcard", "Carte postale double (JIS)" },
            { "personal-envelope", "Enveloppe personnelle" },
            { "quarto", "Quarto" },
            { "radiobutton.color", "Coul&eur" },
            { "radiobutton.draftq", "Broui&llon" },
            { "radiobutton.duplex", "&Duplex" },
            { "radiobutton.highq", "Ma&x." },
            { "radiobutton.landscape", "Pa&ysage" },
            { "radiobutton.monochrome", "Monoc&hrome" },
            { "radiobutton.normalq", "&Normal" },
            { "radiobutton.oneside", "Un &c\u00F4t\u00E9" },
            { "radiobutton.portrait", "&Portrait" },
            { "radiobutton.rangeall", "&Tout" },
            { "radiobutton.rangepages", "Pag&es" },
            { "radiobutton.revlandscape", "Paysage i&nvers\u00E9" },
            { "radiobutton.revportrait", "Portrait &invers\u00E9" },
            { "radiobutton.tumble", "&T\u00EAte-b\u00EAche" },
            { "side", "C\u00F4t\u00E9" },
            { "tab.appearance", "&Apparence" },
            { "tab.general", "&G\u00E9n\u00E9ral" },
            { "tab.pagesetup", "&Mise en page" },
            { "tabloid", "Tablo\u00EFd" },
            { "top", "Haut" },
        };
    }
}
