package sun.print.resources;

import java.util.ListResourceBundle;

public final class serviceui_pt_BR extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "Automatic-Feeder", "Alimentador Autom\u00E1tico" },
            { "Cassette", "Cassete" },
            { "Form-Source", "Origem do Formul\u00E1rio" },
            { "Large-Format", "Formato Grande" },
            { "Manual-Envelope", "Envelope Manual" },
            { "Small-Format", "Formato Pequeno" },
            { "Tractor-Feeder", "Alimentador por Tracionador" },
            { "a", "Engenharia A" },
            { "accepting-jobs", "Aceitando jobs" },
            { "auto-select", "Selecionar Automaticamente" },
            { "b", "Engenharia B" },
            { "border.chromaticity", "Apar\u00EAncia da Cor" },
            { "border.copies", "C\u00F3pias" },
            { "border.jobattributes", "Atributos do Job" },
            { "border.margins", "Margens" },
            { "border.media", "M\u00EDdia" },
            { "border.orientation", "Orienta\u00E7\u00E3o" },
            { "border.printrange", "Faixa de Impress\u00E3o" },
            { "border.printservice", "Servi\u00E7o de Impress\u00E3o" },
            { "border.quality", "Qualidade" },
            { "border.sides", "Lados" },
            { "bottom", "Inferior" },
            { "button.cancel", "Cancelar" },
            { "button.ok", "OK" },
            { "button.print", "Imprimir" },
            { "button.properties", "P&ropriedades..." },
            { "c", "Engenharia C" },
            { "checkbox.collate", "&Agrupar" },
            { "checkbox.jobsheets", "P\u00E1gina com &Banner" },
            { "checkbox.printtofile", "&Imprimir em Arquivo" },
            { "d", "Engenharia D" },
            { "dialog.noprintermsg", "Nenhum servi\u00E7o de impress\u00E3o encontrado." },
            { "dialog.overwrite", "Este arquivo j\u00E1 existe. Deseja substituir o arquivo existente?" },
            { "dialog.owtitle", "Imprimir em Arquivo" },
            { "dialog.printtitle", "Imprimir" },
            { "dialog.printtofile", "Imprimir em Arquivo" },
            { "dialog.pstitle", "Configura\u00E7\u00E3o da P\u00E1gina" },
            { "dialog.writeerror", "N\u00E3o \u00E9 poss\u00EDvel gravar no arquivo:" },
            { "e", "Engenharia E" },
            { "envelope", "Envelope" },
            { "error.destination", "Nome de arquivo inv\u00E1lido; tente novamente" },
            { "error.pagerange", "Faixa de p\u00E1ginas inv\u00E1lida; insira novamente os valores (por exemplo, 1-3,5,7-10)" },
            { "executive", "Executivo" },
            { "folio", "F\u00F3lio" },
            { "invite-envelope", "Envelope de Convite" },
            { "invoice", "Fatura" },
            { "iso-2a0", "2A0 (ISO/DIN & JIS)" },
            { "iso-4a0", "4A0 (ISO/DIN & JIS)" },
            { "iso-a0", "A0 (ISO/DIN & JIS)" },
            { "iso-a1", "A1 (ISO/DIN & JIS)" },
            { "iso-a10", "A10 (ISO/DIN & JIS)" },
            { "iso-a2", "A2 (ISO/DIN & JIS)" },
            { "iso-a3", "A3 (ISO/DIN & JIS)" },
            { "iso-a4", "A4 (ISO/DIN & JIS)" },
            { "iso-a5", "A5 (ISO/DIN & JIS)" },
            { "iso-a6", "A6 (ISO/DIN & JIS)" },
            { "iso-a7", "A7 (ISO/DIN & JIS)" },
            { "iso-a8", "A8 (ISO/DIN & JIS)" },
            { "iso-a9", "A9 (ISO/DIN & JIS)" },
            { "iso-b0", "B0 (ISO/DIN)" },
            { "iso-b1", "B1 (ISO/DIN)" },
            { "iso-b10", "B10 (ISO/DIN)" },
            { "iso-b2", "B2 (ISO/DIN)" },
            { "iso-b3", "B3 (ISO/DIN)" },
            { "iso-b4", "B4 (ISO/DIN)" },
            { "iso-b5", "B5 (ISO/DIN)" },
            { "iso-b6", "B6 (ISO/DIN)" },
            { "iso-b7", "B7 (ISO/DIN)" },
            { "iso-b8", "B8 (ISO/DIN)" },
            { "iso-b9", "B9 (ISO/DIN)" },
            { "iso-c0", "C0 (ISO/DIN)" },
            { "iso-c1", "C1 (ISO/DIN)" },
            { "iso-c10", "C10 (ISO/DIN)" },
            { "iso-c2", "C2 (ISO/DIN)" },
            { "iso-c3", "C3 (ISO/DIN)" },
            { "iso-c4", "C4 (ISO/DIN)" },
            { "iso-c5", "C5 (ISO/DIN)" },
            { "iso-c6", "C6 (ISO/DIN)" },
            { "iso-c7", "C7 (ISO/DIN)" },
            { "iso-c8", "C8 (ISO/DIN)" },
            { "iso-c9", "C9 (ISO/DIN)" },
            { "iso-designated-long", "Longo Designado ISO" },
            { "italian-envelope", "Envelope Italiano" },
            { "italy-envelope", "Envelope Italiano" },
            { "japanese-postcard", "Cart\u00E3o Postal (JIS)" },
            { "jis-b0", "B0 (JIS)" },
            { "jis-b1", "B1 (JIS)" },
            { "jis-b10", "B10 (JIS)" },
            { "jis-b2", "B2 (JIS)" },
            { "jis-b3", "B3 (JIS)" },
            { "jis-b4", "B4 (JIS)" },
            { "jis-b5", "B5 (JIS)" },
            { "jis-b6", "B6 (JIS)" },
            { "jis-b7", "B7 (JIS)" },
            { "jis-b8", "B8 (JIS)" },
            { "jis-b9", "B9 (JIS)" },
            { "label.bottommargin", "&inferior" },
            { "label.inches", "(pol)" },
            { "label.info", "Informa\u00E7\u00F5es:" },
            { "label.jobname", "Nome do &Job:" },
            { "label.leftmargin", "es&querda:" },
            { "label.millimetres", "(mm)" },
            { "label.numcopies", "N\u00FAmer&o de c\u00F3pias:" },
            { "label.priority", "Pri&oridade:" },
            { "label.psname", "&Nome:" },
            { "label.pstype", "Tipo:" },
            { "label.rangeto", "At\u00E9" },
            { "label.rightmargin", "&direita" },
            { "label.size", "Ta&manho:" },
            { "label.source", "&Origem:" },
            { "label.status", "Status:" },
            { "label.topmargin", "&superior" },
            { "label.username", "Nome do &Usu\u00E1rio:" },
            { "large-capacity", "Grande Capacidade" },
            { "ledger", "Duplo Carta" },
            { "main", "Principal" },
            { "manual", "Manual" },
            { "middle", "Meio" },
            { "monarch-envelope", "Envelope Monarca" },
            { "na-10x13-envelope", "Envelope 10x15" },
            { "na-10x14-envelope", "Envelope 10x15" },
            { "na-10x15-envelope", "Envelope 10x15" },
            { "na-5x7", "Papel 5\" x 7\"" },
            { "na-6x9-envelope", "Envelope 6x9" },
            { "na-7x9-envelope", "Envelope 6x7" },
            { "na-8x10", "Papel 8\" x 10\"" },
            { "na-9x11-envelope", "Envelope 9x11" },
            { "na-9x12-envelope", "Envelope 9x12" },
            { "na-legal", "Of\u00EDcio" },
            { "na-letter", "Carta" },
            { "na-number-10-envelope", "Envelope n\u00BA 10" },
            { "na-number-11-envelope", "Envelope n\u00BA 11" },
            { "na-number-12-envelope", "Envelope n\u00BA 12" },
            { "na-number-14-envelope", "Envelope n\u00BA 14" },
            { "na-number-9-envelope", "Envelope n\u00BA 9" },
            { "not-accepting-jobs", "N\u00E3o aceitando jobs" },
            { "oufuko-postcard", "Cart\u00E3o Postal Duplo (JIS)" },
            { "personal-envelope", "Envelope Personalizado" },
            { "quarto", "Quarto" },
            { "radiobutton.color", "&Cor" },
            { "radiobutton.draftq", "Rascun&ho" },
            { "radiobutton.duplex", "Duple&x" },
            { "radiobutton.highq", "A&lta" },
            { "radiobutton.landscape", "&Paisagem" },
            { "radiobutton.monochrome", "&Monocrom\u00E1tico" },
            { "radiobutton.normalq", "&Normal" },
            { "radiobutton.oneside", "Um La&do" },
            { "radiobutton.portrait", "Re&trato" },
            { "radiobutton.rangeall", "T&udo" },
            { "radiobutton.rangepages", "&P\u00E1ginas" },
            { "radiobutton.revlandscape", "Paisagem I&nvertida" },
            { "radiobutton.revportrait", "Retrato In&vertido" },
            { "radiobutton.tumble", "&Virar" },
            { "side", "Lado" },
            { "tab.appearance", "Apa&r\u00EAncia" },
            { "tab.general", "&Geral" },
            { "tab.pagesetup", "Con&figura\u00E7\u00E3o da P\u00E1gina" },
            { "tabloid", "Tabl\u00F3ide" },
            { "top", "Superior" },
        };
    }
}
