package sun.print.resources;

import java.util.ListResourceBundle;

public final class serviceui_ko extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "Automatic-Feeder", "\uC790\uB3D9 \uACF5\uAE09\uAE30" },
            { "Cassette", "\uCE74\uC138\uD2B8" },
            { "Form-Source", "\uC591\uC2DD \uC18C\uC2A4" },
            { "Large-Format", "\uD070 \uD615\uC2DD" },
            { "Manual-Envelope", "\uC218\uB3D9 \uBD09\uD22C" },
            { "Small-Format", "\uC791\uC740 \uD615\uC2DD" },
            { "Tractor-Feeder", "\uD2B8\uB799\uD130 \uACF5\uAE09\uAE30" },
            { "a", "Engineering A" },
            { "accepting-jobs", "\uC791\uC5C5 \uC2B9\uC778" },
            { "auto-select", "\uC790\uB3D9 \uC120\uD0DD" },
            { "b", "Engineering B" },
            { "border.chromaticity", "\uC0C9\uC0C1 \uBAA8\uC591" },
            { "border.copies", "\uBCF5\uC0AC" },
            { "border.jobattributes", "\uC791\uC5C5 \uC18D\uC131" },
            { "border.margins", "\uC5EC\uBC31" },
            { "border.media", "\uB9E4\uCCB4" },
            { "border.orientation", "\uBC29\uD5A5" },
            { "border.printrange", "\uC778\uC1C4 \uBC94\uC704" },
            { "border.printservice", "\uC778\uC1C4 \uC11C\uBE44\uC2A4" },
            { "border.quality", "\uD488\uC9C8" },
            { "border.sides", "\uCE21\uBA74" },
            { "bottom", "\uC544\uB798\uCABD" },
            { "button.cancel", "\uCDE8\uC18C" },
            { "button.ok", "\uD655\uC778" },
            { "button.print", "\uC778\uC1C4" },
            { "button.properties", "\uC18D\uC131(&R)..." },
            { "c", "Engineering C" },
            { "checkbox.collate", "\uD55C \uBD80\uC529 \uC778\uC1C4(&C)" },
            { "checkbox.jobsheets", "\uBC30\uB108 \uD398\uC774\uC9C0(&B)" },
            { "checkbox.printtofile", "\uD30C\uC77C\uB85C \uC778\uC1C4(&F)" },
            { "d", "Engineering D" },
            { "dialog.noprintermsg", "\uC778\uC1C4 \uC11C\uBE44\uC2A4\uB97C \uCC3E\uC744 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4." },
            { "dialog.overwrite", "\uC774 \uD30C\uC77C\uC774 \uC874\uC7AC\uD569\uB2C8\uB2E4. \uAE30\uC874 \uD30C\uC77C\uC744 \uACB9\uCCD0 \uC4F0\uACA0\uC2B5\uB2C8\uAE4C?" },
            { "dialog.owtitle", "\uD30C\uC77C\uB85C \uC778\uC1C4" },
            { "dialog.printtitle", "\uC778\uC1C4" },
            { "dialog.printtofile", "\uD30C\uC77C\uB85C \uC778\uC1C4" },
            { "dialog.pstitle", "\uD398\uC774\uC9C0 \uC124\uC815" },
            { "dialog.writeerror", "\uD30C\uC77C\uC5D0 \uC4F8 \uC218 \uC5C6\uC74C:" },
            { "e", "Engineering E" },
            { "envelope", "Envelope" },
            { "error.destination", "\uBD80\uC801\uD569\uD55C \uD30C\uC77C \uC774\uB984: \uB2E4\uC2DC \uC2DC\uB3C4\uD558\uC2ED\uC2DC\uC624." },
            { "error.pagerange", "\uBD80\uC801\uD569\uD55C \uD398\uC774\uC9C0 \uBC94\uC704: \uAC12\uC744 \uB2E4\uC2DC \uC785\uB825\uD558\uC2ED\uC2DC\uC624(\uC608: 1-3,5,7-10)." },
            { "executive", "Executive" },
            { "folio", "Folio" },
            { "invite-envelope", "Invitation Envelope" },
            { "invoice", "Invoice" },
            { "iso-2a0", "2A0 (ISO/DIN & JIS)" },
            { "iso-4a0", "4A0 (ISO/DIN & JIS)" },
            { "iso-a0", "A0 (ISO/DIN & JIS)" },
            { "iso-a1", "A1 (ISO/DIN & JIS)" },
            { "iso-a10", "A10 (ISO/DIN & JIS)" },
            { "iso-a2", "A2 (ISO/DIN & JIS)" },
            { "iso-a3", "A3 (ISO/DIN & JIS)" },
            { "iso-a4", "A4 (ISO/DIN & JIS)" },
            { "iso-a5", "A5 (ISO/DIN & JIS)" },
            { "iso-a6", "A6 (ISO/DIN & JIS)" },
            { "iso-a7", "A7 (ISO/DIN & JIS)" },
            { "iso-a8", "A8 (ISO/DIN & JIS)" },
            { "iso-a9", "A9 (ISO/DIN & JIS)" },
            { "iso-b0", "B0 (ISO/DIN)" },
            { "iso-b1", "B1 (ISO/DIN)" },
            { "iso-b10", "B10 (ISO/DIN)" },
            { "iso-b2", "B2 (ISO/DIN)" },
            { "iso-b3", "B3 (ISO/DIN)" },
            { "iso-b4", "B4 (ISO/DIN)" },
            { "iso-b5", "B5 (ISO/DIN)" },
            { "iso-b6", "B6 (ISO/DIN)" },
            { "iso-b7", "B7 (ISO/DIN)" },
            { "iso-b8", "B8 (ISO/DIN)" },
            { "iso-b9", "B9 (ISO/DIN)" },
            { "iso-c0", "C0 (ISO/DIN)" },
            { "iso-c1", "C1 (ISO/DIN)" },
            { "iso-c10", "C10 (ISO/DIN)" },
            { "iso-c2", "C2 (ISO/DIN)" },
            { "iso-c3", "C3 (ISO/DIN)" },
            { "iso-c4", "C4 (ISO/DIN)" },
            { "iso-c5", "C5 (ISO/DIN)" },
            { "iso-c6", "C6 (ISO/DIN)" },
            { "iso-c7", "C7 (ISO/DIN)" },
            { "iso-c8", "C8 (ISO/DIN)" },
            { "iso-c9", "C9 (ISO/DIN)" },
            { "iso-designated-long", "ISO Designated Long" },
            { "italian-envelope", "Italy Envelope" },
            { "italy-envelope", "Italy Envelope" },
            { "japanese-postcard", "Postcard (JIS)" },
            { "jis-b0", "B0 (JIS)" },
            { "jis-b1", "B1 (JIS)" },
            { "jis-b10", "B10 (JIS)" },
            { "jis-b2", "B2 (JIS)" },
            { "jis-b3", "B3 (JIS)" },
            { "jis-b4", "B4 (JIS)" },
            { "jis-b5", "B5 (JIS)" },
            { "jis-b6", "B6 (JIS)" },
            { "jis-b7", "B7 (JIS)" },
            { "jis-b8", "B8 (JIS)" },
            { "jis-b9", "B9 (JIS)" },
            { "label.bottommargin", "\uC544\uB798\uCABD(&B)" },
            { "label.inches", "(\uC778\uCE58)" },
            { "label.info", "\uC815\uBCF4:" },
            { "label.jobname", "\uC791\uC5C5 \uC774\uB984(&J):" },
            { "label.leftmargin", "\uC67C\uCABD(&F)" },
            { "label.millimetres", "(mm)" },
            { "label.numcopies", "\uB9E4\uC218(&O):" },
            { "label.priority", "\uC6B0\uC120\uC21C\uC704(&R):" },
            { "label.psname", "\uC774\uB984(&N):" },
            { "label.pstype", "\uC720\uD615:" },
            { "label.rangeto", "\uC885\uB8CC" },
            { "label.rightmargin", "\uC624\uB978\uCABD(&R)" },
            { "label.size", "\uD06C\uAE30(&Z):" },
            { "label.source", "\uC18C\uC2A4(&C):" },
            { "label.status", "\uC0C1\uD0DC:" },
            { "label.topmargin", "\uC704\uCABD(&T)" },
            { "label.username", "\uC0AC\uC6A9\uC790 \uC774\uB984(&U):" },
            { "large-capacity", "\uD070 \uC6A9\uB7C9" },
            { "ledger", "Ledger" },
            { "main", "\uC8FC" },
            { "manual", "\uC218\uB3D9" },
            { "middle", "\uAC00\uC6B4\uB370" },
            { "monarch-envelope", "Monarch Envelope" },
            { "na-10x13-envelope", "10x15 Envelope" },
            { "na-10x14-envelope", "10x15 Envelope" },
            { "na-10x15-envelope", "10x15 Envelope" },
            { "na-5x7", "5\" x 7\" \uC6A9\uC9C0" },
            { "na-6x9-envelope", "6x9 Envelope" },
            { "na-7x9-envelope", "6x7 Envelope" },
            { "na-8x10", "8\" x 10\" \uC6A9\uC9C0" },
            { "na-9x11-envelope", "9x11 Envelope" },
            { "na-9x12-envelope", "9x12 Envelope" },
            { "na-legal", "Legal" },
            { "na-letter", "Letter" },
            { "na-number-10-envelope", "No. 10 Envelope" },
            { "na-number-11-envelope", "No. 11 Envelope" },
            { "na-number-12-envelope", "No. 12 Envelope" },
            { "na-number-14-envelope", "No. 14 Envelope" },
            { "na-number-9-envelope", "No. 9 Envelope" },
            { "not-accepting-jobs", "\uC791\uC5C5 \uC2B9\uC778 \uC548\uD568" },
            { "oufuko-postcard", "Double Postcard (JIS)" },
            { "personal-envelope", "Personal Envelope" },
            { "quarto", "Quarto" },
            { "radiobutton.color", "\uC0C9\uC0C1(&C)" },
            { "radiobutton.draftq", "\uCD08\uC548(&F)" },
            { "radiobutton.duplex", "\uC591\uBA74(&D)" },
            { "radiobutton.highq", "\uB192\uC74C(&H)" },
            { "radiobutton.landscape", "\uAC00\uB85C(&L)" },
            { "radiobutton.monochrome", "\uB2E8\uC0C9(&M)" },
            { "radiobutton.normalq", "\uBCF4\uD1B5(&N)" },
            { "radiobutton.oneside", "\uB2E8\uBA74(&O)" },
            { "radiobutton.portrait", "\uC138\uB85C(&P)" },
            { "radiobutton.rangeall", "\uC804\uCCB4(&L)" },
            { "radiobutton.rangepages", "\uD398\uC774\uC9C0(&E)" },
            { "radiobutton.revlandscape", "\uAC00\uB85C \uBC18\uC804(&N)" },
            { "radiobutton.revportrait", "\uC138\uB85C \uBC18\uC804(&I)" },
            { "radiobutton.tumble", "\uD68C\uC804\uC2DD(&T)" },
            { "side", "\uCE21\uBA74" },
            { "tab.appearance", "\uBAA8\uC591(&A)" },
            { "tab.general", "\uC77C\uBC18 \uC0AC\uD56D(&G)" },
            { "tab.pagesetup", "\uD398\uC774\uC9C0 \uC124\uC815(&S)" },
            { "tabloid", "Tabloid" },
            { "top", "\uC704\uCABD" },
        };
    }
}
