package sun.print.resources;

import java.util.ListResourceBundle;

public final class serviceui_de extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "Automatic-Feeder", "Automatische Zuf\u00FChrung" },
            { "Cassette", "Kassette" },
            { "Form-Source", "Formularquelle" },
            { "Large-Format", "Gro\u00DFformat" },
            { "Manual-Envelope", "Manuelle Umschlagzuf\u00FChrung" },
            { "Small-Format", "Kleinformat" },
            { "Tractor-Feeder", "Endlospapiereinzug" },
            { "a", "Millimeterpapier A" },
            { "accepting-jobs", "Jobs annehmen" },
            { "auto-select", "Automatische Auswahl" },
            { "b", "Millimeterpapier B" },
            { "border.chromaticity", "Farbdarstellung" },
            { "border.copies", "Kopien" },
            { "border.jobattributes", "Jobattribute" },
            { "border.margins", "R\u00E4nder" },
            { "border.media", "Medien" },
            { "border.orientation", "Ausrichtung" },
            { "border.printrange", "Druckbereich" },
            { "border.printservice", "Druckservice" },
            { "border.quality", "Qualit\u00E4t" },
            { "border.sides", "Seiten" },
            { "bottom", "Unten" },
            { "button.cancel", "Abbrechen" },
            { "button.ok", "OK" },
            { "button.print", "Drucken" },
            { "button.properties", "E&igenschaften..." },
            { "c", "Millimeterpapier C" },
            { "checkbox.collate", "&Sortieren" },
            { "checkbox.jobsheets", "Banner&seite" },
            { "checkbox.printtofile", "Aus&gabe in Datei" },
            { "d", "Millimeterpapier D" },
            { "dialog.noprintermsg", "Kein Druckservice gefunden." },
            { "dialog.overwrite", "Diese Datei ist bereits vorhanden. M\u00F6chten Sie die vorhandene Datei \u00FCberschreiben?" },
            { "dialog.owtitle", "In Datei drucken" },
            { "dialog.printtitle", "Drucken" },
            { "dialog.printtofile", "In Datei drucken" },
            { "dialog.pstitle", "Seite einrichten" },
            { "dialog.writeerror", "Schreiben in Datei nicht m\u00F6glich:" },
            { "e", "Millimeterpapier E" },
            { "envelope", "Umschlag" },
            { "error.destination", "Ung\u00FCltiger Dateiname. Wiederholen Sie den Vorgang" },
            { "error.pagerange", "Ung\u00FCltiger Seitenbereich. Geben Sie die Werte erneut ein (Beispiel: 1-3,5,7-10)" },
            { "executive", "Executive" },
            { "folio", "Folio" },
            { "invite-envelope", "Einladungsumschlag" },
            { "invoice", "Invoice" },
            { "iso-2a0", "2A0 (ISO/DIN & JIS)" },
            { "iso-4a0", "4A0 (ISO/DIN & JIS)" },
            { "iso-a0", "A0 (ISO/DIN & JIS)" },
            { "iso-a1", "A1 (ISO/DIN & JIS)" },
            { "iso-a10", "A10 (ISO/DIN & JIS)" },
            { "iso-a2", "A2 (ISO/DIN & JIS)" },
            { "iso-a3", "A3 (ISO/DIN & JIS)" },
            { "iso-a4", "A4 (ISO/DIN & JIS)" },
            { "iso-a5", "A5 (ISO/DIN & JIS)" },
            { "iso-a6", "A6 (ISO/DIN & JIS)" },
            { "iso-a7", "A7 (ISO/DIN & JIS)" },
            { "iso-a8", "A8 (ISO/DIN & JIS)" },
            { "iso-a9", "A9 (ISO/DIN & JIS)" },
            { "iso-b0", "B0 (ISO/DIN)" },
            { "iso-b1", "B1 (ISO/DIN)" },
            { "iso-b10", "B10 (ISO/DIN)" },
            { "iso-b2", "B2 (ISO/DIN)" },
            { "iso-b3", "B3 (ISO/DIN)" },
            { "iso-b4", "B4 (ISO/DIN)" },
            { "iso-b5", "B5 (ISO/DIN)" },
            { "iso-b6", "B6 (ISO/DIN)" },
            { "iso-b7", "B7 (ISO/DIN)" },
            { "iso-b8", "B8 (ISO/DIN)" },
            { "iso-b9", "B9 (ISO/DIN)" },
            { "iso-c0", "C0 (ISO/DIN)" },
            { "iso-c1", "C1 (ISO/DIN)" },
            { "iso-c10", "C10 (ISO/DIN)" },
            { "iso-c2", "C2 (ISO/DIN)" },
            { "iso-c3", "C3 (ISO/DIN)" },
            { "iso-c4", "C4 (ISO/DIN)" },
            { "iso-c5", "C5 (ISO/DIN)" },
            { "iso-c6", "C6 (ISO/DIN)" },
            { "iso-c7", "C7 (ISO/DIN)" },
            { "iso-c8", "C8 (ISO/DIN)" },
            { "iso-c9", "C9 (ISO/DIN)" },
            { "iso-designated-long", "ISO Designated Long" },
            { "italian-envelope", "Italy-Umschlag" },
            { "italy-envelope", "Italy-Umschlag" },
            { "japanese-postcard", "Postkarte (JIS)" },
            { "jis-b0", "B0 (JIS)" },
            { "jis-b1", "B1 (JIS)" },
            { "jis-b10", "B10 (JIS)" },
            { "jis-b2", "B2 (JIS)" },
            { "jis-b3", "B3 (JIS)" },
            { "jis-b4", "B4 (JIS)" },
            { "jis-b5", "B5 (JIS)" },
            { "jis-b6", "B6 (JIS)" },
            { "jis-b7", "B7 (JIS)" },
            { "jis-b8", "B8 (JIS)" },
            { "jis-b9", "B9 (JIS)" },
            { "label.bottommargin", "u&nten" },
            { "label.inches", "(Zoll)" },
            { "label.info", "Info:" },
            { "label.jobname", "&Jobname:" },
            { "label.leftmargin", "&links" },
            { "label.millimetres", "(mm)" },
            { "label.numcopies", "Anzahl &Kopien:" },
            { "label.priority", "P&riorit\u00E4t:" },
            { "label.psname", "&Name:" },
            { "label.pstype", "Typ:" },
            { "label.rangeto", "Bis" },
            { "label.rightmargin", "re&chts" },
            { "label.size", "G&r\u00F6\u00DFe:" },
            { "label.source", "&Quelle:" },
            { "label.status", "Status:" },
            { "label.topmargin", "&oben" },
            { "label.username", "&Benutzername:" },
            { "large-capacity", "Hohe Kapazit\u00E4t" },
            { "ledger", "Ledger" },
            { "main", "Haupt" },
            { "manual", "Manuell" },
            { "middle", "Mitte" },
            { "monarch-envelope", "Monarch-Umschlag" },
            { "na-10x13-envelope", "10x13-Umschlag" },
            { "na-10x14-envelope", "10x14-Umschlag" },
            { "na-10x15-envelope", "10x15-Umschlag" },
            { "na-5x7", "5\" x 7\"-Papier" },
            { "na-6x9-envelope", "6x9-Umschlag" },
            { "na-7x9-envelope", "6x7-Umschlag" },
            { "na-8x10", "8\" x 10\"-Papier" },
            { "na-9x11-envelope", "9x11-Umschlag" },
            { "na-9x12-envelope", "9x12-Umschlag" },
            { "na-legal", "Legal" },
            { "na-letter", "Letter" },
            { "na-number-10-envelope", "Umschlag Nr. 10" },
            { "na-number-11-envelope", "Umschlag Nr. 11" },
            { "na-number-12-envelope", "Umschlag Nr. 12" },
            { "na-number-14-envelope", "Umschlag Nr. 14" },
            { "na-number-9-envelope", "Umschlag Nr. 9" },
            { "not-accepting-jobs", "Jobs nicht annehmen" },
            { "oufuko-postcard", "Doppelte Postkarte (JIS)" },
            { "personal-envelope", "Pers\u00F6nlicher Umschlag" },
            { "quarto", "Quarto" },
            { "radiobutton.color", "&Farbe" },
            { "radiobutton.draftq", "Ent&wurf" },
            { "radiobutton.duplex", "Du&plex" },
            { "radiobutton.highq", "&Hoch" },
            { "radiobutton.landscape", "Querforma&t" },
            { "radiobutton.monochrome", "&Monochrom" },
            { "radiobutton.normalq", "&Normal" },
            { "radiobutton.oneside", "E&inseitig" },
            { "radiobutton.portrait", "Hochfor&mat" },
            { "radiobutton.rangeall", "A&lle" },
            { "radiobutton.rangepages", "Sei&ten" },
            { "radiobutton.revlandscape", "Umgekehrtes Q&uerformat" },
            { "radiobutton.revportrait", "Umgekehrtes &Hochformat" },
            { "radiobutton.tumble", "&Kalenderdruck" },
            { "side", "Seite" },
            { "tab.appearance", "&Darstellung" },
            { "tab.general", "&Allgemein" },
            { "tab.pagesetup", "Seite &einrichten" },
            { "tabloid", "Tabloid" },
            { "top", "Oben" },
        };
    }
}
