package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/LOCATION_FORWARD.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from t:/workspace/open/src/java.corba/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Wednesday, March 7, 2018 at 6:07:53 PM Pacific Standard Time
*/

public interface LOCATION_FORWARD
{

  /**
   * Indicates a LocationForward reply status. One possible value for 
   * <code>RequestInfo.reply_status</code>.
   * @see RequestInfo#reply_status
   * @see SUCCESSFUL
   * @see SYSTEM_EXCEPTION
   * @see USER_EXCEPTION
   * @see TRANSPORT_RETRY
   */
  public static final short value = (short)(3);
}
