package sun.awt.resources;

import java.util.ListResourceBundle;

public final class awt_zh_HK extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "AWT.CompositionWindowTitle", "\u8F38\u5165\u8996\u7A97" },
            { "AWT.CrosshairCursor", "Crosshair Cursor" },
            { "AWT.DefaultCursor", "Default Cursor" },
            { "AWT.DefaultDragCursor", "Default Drag Cursor" },
            { "AWT.DefaultDropCursor", "Default Drop Cursor" },
            { "AWT.DefaultNoDropCursor", "Default NoDrag Cursor" },
            { "AWT.EResizeCursor", "East Resize Cursor" },
            { "AWT.HandCursor", "Hand Cursor" },
            { "AWT.HostInputMethodDisplayName", "\u7CFB\u7D71\u8F38\u5165\u6CD5" },
            { "AWT.InconsistentDLLsWarning", "\u4EE5\u6587\u5B57\u70BA\u57FA\u790E\u7684\u4F5C\u696D\u53EF\u80FD\u7121\u6CD5\u6B63\u78BA\u904B\u4F5C\uFF0C\u56E0\u70BA\u60A8\u7CFB\u7D71\u4E0A\u6709\u4E00\u7D44\u52D5\u614B\u9023\u7D50\u7A0B\u5F0F\u5EAB (DLL) \u4E0D\u4E00\u81F4\u3002\u82E5\u8981\u53D6\u5F97\u6709\u95DC\u6B64\u554F\u984C\u53CA\u5EFA\u8B70\u89E3\u6C7A\u65B9\u6CD5\u7684\u5176\u4ED6\u8CC7\u8A0A\uFF0C\u8ACB\u53C3\u95B1 java.sun.com \u7DB2\u7AD9\u4E0A\u7684 Java(TM) 2 SDK, Standard Edition Release Notes" },
            { "AWT.InputMethodCreationFailed", "\u7121\u6CD5\u5EFA\u7ACB {0}\u3002\u539F\u56E0: {1}" },
            { "AWT.InputMethodLanguage.ja", "\u65E5\u6587" },
            { "AWT.InputMethodLanguage.ko", "\u97D3\u6587" },
            { "AWT.InputMethodLanguage.zh", "\u4E2D\u6587" },
            { "AWT.InputMethodLanguage.zh_CN", "\u7C21\u9AD4\u4E2D\u6587" },
            { "AWT.InputMethodLanguage.zh_TW", "\u7E41\u9AD4\u4E2D\u6587" },
            { "AWT.InputMethodSelectionMenu", "\u9078\u64C7\u8F38\u5165\u6CD5" },
            { "AWT.Less", "Less" },
            { "AWT.MoveCursor", "Move Cursor" },
            { "AWT.NEResizeCursor", "Northeast Resize Cursor" },
            { "AWT.NResizeCursor", "North Resize Cursor" },
            { "AWT.NWResizeCursor", "Northwest Resize Cursor" },
            { "AWT.SEResizeCursor", "Southeast Resize Cursor" },
            { "AWT.SResizeCursor", "South Resize Cursor" },
            { "AWT.SWResizeCursor", "Southwest Resize Cursor" },
            { "AWT.TextCursor", "Text Cursor" },
            { "AWT.WResizeCursor", "West Resize Cursor" },
            { "AWT.WaitCursor", "Wait Cursor" },
            { "AWT.accept", "Accept" },
            { "AWT.add", "NumPad +" },
            { "AWT.again", "Again" },
            { "AWT.allCandidates", "All Candidates" },
            { "AWT.alphanumeric", "Alphanumeric" },
            { "AWT.alt", "Alt" },
            { "AWT.altGraph", "Alt Graph" },
            { "AWT.ampersand", "Ampersand" },
            { "AWT.asterisk", "Asterisk" },
            { "AWT.at", "At" },
            { "AWT.backQuote", "Back Quote" },
            { "AWT.backSlash", "Back Slash" },
            { "AWT.backSpace", "Backspace" },
            { "AWT.begin", "Begin" },
            { "AWT.braceLeft", "Left Brace" },
            { "AWT.braceRight", "Right Brace" },
            { "AWT.cancel", "Cancel" },
            { "AWT.capsLock", "Caps Lock" },
            { "AWT.circumflex", "Circumflex" },
            { "AWT.clear", "Clear" },
            { "AWT.closeBracket", "Close Bracket" },
            { "AWT.codeInput", "Code Input" },
            { "AWT.colon", "Colon" },
            { "AWT.comma", "Comma" },
            { "AWT.compose", "Compose" },
            { "AWT.context", "Context Menu" },
            { "AWT.control", "Ctrl" },
            { "AWT.convert", "Convert" },
            { "AWT.copy", "Copy" },
            { "AWT.cut", "Cut" },
            { "AWT.deadAboveDot", "Dead Above Dot" },
            { "AWT.deadAboveRing", "Dead Above Ring" },
            { "AWT.deadAcute", "Dead Acute" },
            { "AWT.deadBreve", "Dead Breve" },
            { "AWT.deadCaron", "Dead Caron" },
            { "AWT.deadCedilla", "Dead Cedilla" },
            { "AWT.deadCircumflex", "Dead Circumflex" },
            { "AWT.deadDiaeresis", "Dead Diaeresis" },
            { "AWT.deadDoubleAcute", "Dead Double Acute" },
            { "AWT.deadGrave", "Dead Grave" },
            { "AWT.deadIota", "Dead Iota" },
            { "AWT.deadMacron", "Dead Macron" },
            { "AWT.deadOgonek", "Dead Ogonek" },
            { "AWT.deadSemivoicedSound", "Dead Semivoiced Sound" },
            { "AWT.deadTilde", "Dead Tilde" },
            { "AWT.deadVoicedSound", "Dead Voiced Sound" },
            { "AWT.decimal", "NumPad ." },
            { "AWT.delete", "Delete" },
            { "AWT.divide", "NumPad /" },
            { "AWT.dollar", "Dollar" },
            { "AWT.down", "Down" },
            { "AWT.end", "End" },
            { "AWT.enter", "Enter" },
            { "AWT.equals", "Equals" },
            { "AWT.escape", "Escape" },
            { "AWT.euro", "Euro" },
            { "AWT.exclamationMark", "Exclamation Mark" },
            { "AWT.f1", "F1" },
            { "AWT.f10", "F10" },
            { "AWT.f11", "F11" },
            { "AWT.f12", "F12" },
            { "AWT.f13", "F13" },
            { "AWT.f14", "F14" },
            { "AWT.f15", "F15" },
            { "AWT.f16", "F16" },
            { "AWT.f17", "F17" },
            { "AWT.f18", "F18" },
            { "AWT.f19", "F19" },
            { "AWT.f2", "F2" },
            { "AWT.f20", "F20" },
            { "AWT.f21", "F21" },
            { "AWT.f22", "F22" },
            { "AWT.f23", "F23" },
            { "AWT.f24", "F24" },
            { "AWT.f3", "F3" },
            { "AWT.f4", "F4" },
            { "AWT.f5", "F5" },
            { "AWT.f6", "F6" },
            { "AWT.f7", "F7" },
            { "AWT.f8", "F8" },
            { "AWT.f9", "F9" },
            { "AWT.final", "Final" },
            { "AWT.find", "Find" },
            { "AWT.fullWidth", "Full-Width" },
            { "AWT.greater", "Greater" },
            { "AWT.halfWidth", "Half-Width" },
            { "AWT.help", "Help" },
            { "AWT.hiragana", "Hiragana" },
            { "AWT.home", "Home" },
            { "AWT.inputMethodOnOff", "Input Method On/Off" },
            { "AWT.insert", "Insert" },
            { "AWT.invertedExclamationMark", "Inverted Exclamation Mark" },
            { "AWT.japaneseHiragana", "Japanese Hiragana" },
            { "AWT.japaneseKatakana", "Japanese Katakana" },
            { "AWT.japaneseRoman", "Japanese Roman" },
            { "AWT.kana", "Kana" },
            { "AWT.kanaLock", "Kana Lock" },
            { "AWT.kanji", "Kanji" },
            { "AWT.katakana", "Katakana" },
            { "AWT.left", "Left" },
            { "AWT.leftParenthesis", "Left Parenthesis" },
            { "AWT.meta", "Meta" },
            { "AWT.minus", "Minus" },
            { "AWT.modechange", "Mode Change" },
            { "AWT.multiply", "NumPad *" },
            { "AWT.noconvert", "No Convert" },
            { "AWT.numLock", "Num Lock" },
            { "AWT.numberSign", "Number Sign" },
            { "AWT.numpad", "NumPad" },
            { "AWT.openBracket", "Open Bracket" },
            { "AWT.paste", "Paste" },
            { "AWT.pause", "Pause" },
            { "AWT.period", "Period" },
            { "AWT.pgdn", "Page Down" },
            { "AWT.pgup", "Page Up" },
            { "AWT.plus", "Plus" },
            { "AWT.previousCandidate", "Previous Candidate" },
            { "AWT.printScreen", "Print Screen" },
            { "AWT.props", "Props" },
            { "AWT.quote", "Quote" },
            { "AWT.quoteDbl", "Double Quote" },
            { "AWT.right", "Right" },
            { "AWT.rightParenthesis", "Right Parenthesis" },
            { "AWT.romanCharacters", "Roman Characters" },
            { "AWT.scrollLock", "Scroll Lock" },
            { "AWT.semicolon", "Semicolon" },
            { "AWT.separater", "NumPad ," },
            { "AWT.separator", "NumPad ," },
            { "AWT.shift", "Shift" },
            { "AWT.slash", "Slash" },
            { "AWT.space", "Space" },
            { "AWT.stop", "Stop" },
            { "AWT.subtract", "NumPad -" },
            { "AWT.tab", "Tab" },
            { "AWT.undefined", "Undefined" },
            { "AWT.underscore", "Underscore" },
            { "AWT.undo", "Undo" },
            { "AWT.unknown", "Unknown" },
            { "AWT.up", "Up" },
            { "AWT.windows", "Windows" },
            { "java.awt.def.delay", "30" },
            { "java.awt.im.style", "on-the-spot" },
        };
    }
}
