package sun.awt.resources;

import java.util.ListResourceBundle;

public final class awt_fr extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "AWT.CompositionWindowTitle", "Fen\u00EAtre d'entr\u00E9e" },
            { "AWT.CrosshairCursor", "Curseur r\u00E9ticulaire" },
            { "AWT.DefaultCursor", "Curseur par d\u00E9faut" },
            { "AWT.DefaultDragCursor", "Curseur de d\u00E9placement par d\u00E9faut" },
            { "AWT.DefaultDropCursor", "Curseur de pose par d\u00E9faut" },
            { "AWT.DefaultNoDropCursor", "Curseur non d\u00E9pla\u00E7ant par d\u00E9faut" },
            { "AWT.EResizeCursor", "Curseur de redimensionnement est" },
            { "AWT.HandCursor", "Curseur en forme de main" },
            { "AWT.HostInputMethodDisplayName", "M\u00E9thodes d'entr\u00E9e syst\u00E8me" },
            { "AWT.InconsistentDLLsWarning", "Il se peut que les op\u00E9rations li\u00E9es au texte ne fonctionnent pas correctement lorsqu'un ensemble incoh\u00E9rent de DLL est install\u00E9 sur le syst\u00E8me. Vous trouverez plus de d\u00E9tails sur ce probl\u00E8me et sur sa solution dans le document Java(TM) 2 SDK, Standard Edition Release Notes sur java.sun.com." },
            { "AWT.InputMethodCreationFailed", "Impossible de cr\u00E9er {0}.  Raison\u00A0: {1}" },
            { "AWT.InputMethodLanguage.ja", "Japonais" },
            { "AWT.InputMethodLanguage.ko", "Cor\u00E9en" },
            { "AWT.InputMethodLanguage.zh", "Chinois" },
            { "AWT.InputMethodLanguage.zh_CN", "Chinois simplifi\u00E9" },
            { "AWT.InputMethodLanguage.zh_TW", "Chinois traditionnel" },
            { "AWT.InputMethodSelectionMenu", "S\u00E9lectionner la m\u00E9thode d'entr\u00E9e" },
            { "AWT.Less", "Inf\u00E9rieur \u00E0" },
            { "AWT.MoveCursor", "Curseur de d\u00E9placement" },
            { "AWT.NEResizeCursor", "Curseur de redimensionnement nord-est" },
            { "AWT.NResizeCursor", "Curseur de redimensionnement nord" },
            { "AWT.NWResizeCursor", "Curseur de redimensionnement nord-ouest" },
            { "AWT.SEResizeCursor", "Curseur de redimensionnement sud-est" },
            { "AWT.SResizeCursor", "Curseur de redimensionnement sud" },
            { "AWT.SWResizeCursor", "Curseur de redimensionnement sud-ouest" },
            { "AWT.TextCursor", "Curseur de texte" },
            { "AWT.WResizeCursor", "Curseur de redimensionnement ouest" },
            { "AWT.WaitCursor", "Curseur d'attente" },
            { "AWT.accept", "Accepter" },
            { "AWT.add", "Pav\u00E9 num\u00E9rique +" },
            { "AWT.again", "R\u00E9p\u00E9ter" },
            { "AWT.allCandidates", "Tous les candidats" },
            { "AWT.alphanumeric", "Alphanum\u00E9rique" },
            { "AWT.alt", "Alt" },
            { "AWT.altGraph", "Alt graphique" },
            { "AWT.ampersand", "Esperluette" },
            { "AWT.asterisk", "Ast\u00E9risque" },
            { "AWT.at", "A commercial" },
            { "AWT.backQuote", "Accent grave avec chasse" },
            { "AWT.backSlash", "Barre oblique inverse" },
            { "AWT.backSpace", "Retour arri\u00E8re" },
            { "AWT.begin", "D\u00E9but" },
            { "AWT.braceLeft", "Accolade ouvrante" },
            { "AWT.braceRight", "Accolade fermante" },
            { "AWT.cancel", "Annuler" },
            { "AWT.capsLock", "Verrouillage des majuscules" },
            { "AWT.circumflex", "Circonflexe" },
            { "AWT.clear", "Effacer" },
            { "AWT.closeBracket", "Crochet fermant" },
            { "AWT.codeInput", "Entr\u00E9e de code" },
            { "AWT.colon", "Deux-points" },
            { "AWT.comma", "Virgule" },
            { "AWT.compose", "Composer" },
            { "AWT.context", "Menu contextuel" },
            { "AWT.control", "Ctrl" },
            { "AWT.convert", "Convertir" },
            { "AWT.copy", "Copier" },
            { "AWT.cut", "Couper" },
            { "AWT.deadAboveDot", "Point en chef" },
            { "AWT.deadAboveRing", "Anneau en chef" },
            { "AWT.deadAcute", "Accent aigu" },
            { "AWT.deadBreve", "Dead Breve" },
            { "AWT.deadCaron", "Caron" },
            { "AWT.deadCedilla", "C\u00E9dille" },
            { "AWT.deadCircumflex", "Accent circonflexe" },
            { "AWT.deadDiaeresis", "Tr\u00E9ma" },
            { "AWT.deadDoubleAcute", "Double accent aigu" },
            { "AWT.deadGrave", "Accent grave" },
            { "AWT.deadIota", "Iota" },
            { "AWT.deadMacron", "Macron" },
            { "AWT.deadOgonek", "Ogonek" },
            { "AWT.deadSemivoicedSound", "Son semi-vois\u00E9" },
            { "AWT.deadTilde", "Tilde" },
            { "AWT.deadVoicedSound", "Son vois\u00E9" },
            { "AWT.decimal", "Pav\u00E9 num\u00E9rique ." },
            { "AWT.delete", "Supprimer" },
            { "AWT.divide", "Pav\u00E9 num\u00E9rique /" },
            { "AWT.dollar", "Dollar" },
            { "AWT.down", "Bas" },
            { "AWT.end", "Fin" },
            { "AWT.enter", "Entr\u00E9e" },
            { "AWT.equals", "Egal" },
            { "AWT.escape", "Echap" },
            { "AWT.euro", "Euro" },
            { "AWT.exclamationMark", "Point d'exclamation" },
            { "AWT.f1", "F1" },
            { "AWT.f10", "F10" },
            { "AWT.f11", "F11" },
            { "AWT.f12", "F12" },
            { "AWT.f13", "F13" },
            { "AWT.f14", "F14" },
            { "AWT.f15", "F15" },
            { "AWT.f16", "F16" },
            { "AWT.f17", "F17" },
            { "AWT.f18", "F18" },
            { "AWT.f19", "F19" },
            { "AWT.f2", "F2" },
            { "AWT.f20", "F20" },
            { "AWT.f21", "F21" },
            { "AWT.f22", "F22" },
            { "AWT.f23", "F23" },
            { "AWT.f24", "F24" },
            { "AWT.f3", "F3" },
            { "AWT.f4", "F4" },
            { "AWT.f5", "F5" },
            { "AWT.f6", "F6" },
            { "AWT.f7", "F7" },
            { "AWT.f8", "F8" },
            { "AWT.f9", "F9" },
            { "AWT.final", "Final" },
            { "AWT.find", "Rechercher" },
            { "AWT.fullWidth", "Pleine largeur" },
            { "AWT.greater", "Sup\u00E9rieur \u00E0" },
            { "AWT.halfWidth", "Demi-largeur" },
            { "AWT.help", "Aide" },
            { "AWT.hiragana", "Hiragana" },
            { "AWT.home", "Origine" },
            { "AWT.inputMethodOnOff", "Activation/d\u00E9sactivation de la m\u00E9thode d'entr\u00E9e" },
            { "AWT.insert", "Ins\u00E9rer" },
            { "AWT.invertedExclamationMark", "Point d'exclamation invers\u00E9" },
            { "AWT.japaneseHiragana", "Japonais Hiragana" },
            { "AWT.japaneseKatakana", "Japonais Katakana" },
            { "AWT.japaneseRoman", "Japonais romain" },
            { "AWT.kana", "Kana" },
            { "AWT.kanaLock", "Verrouiller Kana" },
            { "AWT.kanji", "Kanji" },
            { "AWT.katakana", "Katakana" },
            { "AWT.left", "Gauche" },
            { "AWT.leftParenthesis", "Parenth\u00E8se ouvrante" },
            { "AWT.meta", "M\u00E9ta" },
            { "AWT.minus", "Moins" },
            { "AWT.modechange", "Changement de mode" },
            { "AWT.multiply", "Pav\u00E9 num\u00E9rique *" },
            { "AWT.noconvert", "Ne pas convertir" },
            { "AWT.numLock", "Verrouillage du pav\u00E9 num\u00E9rique" },
            { "AWT.numberSign", "Di\u00E8se" },
            { "AWT.numpad", "Pav\u00E9 num\u00E9rique" },
            { "AWT.openBracket", "Crochet ouvrant" },
            { "AWT.paste", "Coller" },
            { "AWT.pause", "Pause" },
            { "AWT.period", "Point" },
            { "AWT.pgdn", "Page suivante" },
            { "AWT.pgup", "Page pr\u00E9c\u00E9dente" },
            { "AWT.plus", "Plus" },
            { "AWT.previousCandidate", "Candidat pr\u00E9c\u00E9dent" },
            { "AWT.printScreen", "Impression d'\u00E9cran" },
            { "AWT.props", "Props" },
            { "AWT.quote", "Apostrophe" },
            { "AWT.quoteDbl", "Guillemets" },
            { "AWT.right", "Droite" },
            { "AWT.rightParenthesis", "Parenth\u00E8se fermante" },
            { "AWT.romanCharacters", "Caract\u00E8res romains" },
            { "AWT.scrollLock", "Verrouillage du d\u00E9filement" },
            { "AWT.semicolon", "Point-virgule" },
            { "AWT.separater", "Pav\u00E9 num\u00E9rique ," },
            { "AWT.separator", "Pav\u00E9 num\u00E9rique ," },
            { "AWT.shift", "Maj" },
            { "AWT.slash", "Barre oblique" },
            { "AWT.space", "Espace" },
            { "AWT.stop", "Arr\u00EAter" },
            { "AWT.subtract", "Pav\u00E9 num\u00E9rique -" },
            { "AWT.tab", "Tab" },
            { "AWT.undefined", "Non d\u00E9fini" },
            { "AWT.underscore", "Trait de soulignement" },
            { "AWT.undo", "Annuler" },
            { "AWT.unknown", "Inconnu" },
            { "AWT.up", "Haut" },
            { "AWT.windows", "Windows" },
            { "java.awt.def.delay", "30" },
            { "java.awt.im.style", "sur place" },
        };
    }
}
