package sun.awt.resources;

import java.util.ListResourceBundle;

public final class awt_ko extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "AWT.CompositionWindowTitle", "\uC785\uB825 \uCC3D" },
            { "AWT.CrosshairCursor", "\uC2ED\uC790 \uCEE4\uC11C" },
            { "AWT.DefaultCursor", "\uAE30\uBCF8 \uCEE4\uC11C" },
            { "AWT.DefaultDragCursor", "\uAE30\uBCF8 \uB04C\uAE30 \uCEE4\uC11C" },
            { "AWT.DefaultDropCursor", "\uAE30\uBCF8 \uB193\uAE30 \uCEE4\uC11C" },
            { "AWT.DefaultNoDropCursor", "\uAE30\uBCF8 NoDrag \uCEE4\uC11C" },
            { "AWT.EResizeCursor", "\uB3D9\uCABD \uBC29\uD5A5 \uD06C\uAE30 \uC870\uC815 \uCEE4\uC11C" },
            { "AWT.HandCursor", "\uC190 \uCEE4\uC11C" },
            { "AWT.HostInputMethodDisplayName", "\uC2DC\uC2A4\uD15C \uC785\uB825 \uBC29\uBC95" },
            { "AWT.InconsistentDLLsWarning", "\uC2DC\uC2A4\uD15C\uC5D0 \uC124\uCE58\uB41C DLL(Dynamic Linking Libraries) \uC9D1\uD569\uC774 \uC77C\uCE58\uD558\uC9C0 \uC54A\uC544 \uD14D\uC2A4\uD2B8 \uAE30\uBC18 \uC791\uC5C5\uC774 \uC81C\uB300\uB85C \uC791\uB3D9\uD558\uC9C0 \uC54A\uC744 \uC218 \uC788\uC2B5\uB2C8\uB2E4. \uC774 \uBB38\uC81C\uC5D0 \uB300\uD55C \uC790\uC138\uD55C \uB0B4\uC6A9\uACFC \uD574\uACB0 \uBC29\uBC95 \uC81C\uC548 \uC0AC\uD56D\uC740 java.sun.com\uC758 Java(TM) 2 SDK, Standard Edition Release Notes\uB97C \uCC38\uC870\uD558\uC2ED\uC2DC\uC624." },
            { "AWT.InputMethodCreationFailed", "{0}\uC744(\uB97C) \uC0DD\uC131\uD560 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4. \uC6D0\uC778: {1}" },
            { "AWT.InputMethodLanguage.ja", "\uC77C\uBCF8\uC5B4" },
            { "AWT.InputMethodLanguage.ko", "\uD55C\uAD6D\uC5B4" },
            { "AWT.InputMethodLanguage.zh", "\uC911\uAD6D\uC5B4" },
            { "AWT.InputMethodLanguage.zh_CN", "\uC911\uAD6D\uC5B4 \uAC04\uCCB4" },
            { "AWT.InputMethodLanguage.zh_TW", "\uC911\uAD6D\uC5B4 \uBC88\uCCB4" },
            { "AWT.InputMethodSelectionMenu", "\uC785\uB825 \uBC29\uBC95 \uC120\uD0DD" },
            { "AWT.Less", "Less" },
            { "AWT.MoveCursor", "\uC774\uB3D9 \uCEE4\uC11C" },
            { "AWT.NEResizeCursor", "\uBD81\uB3D9 \uBC29\uD5A5 \uD06C\uAE30 \uC870\uC815 \uCEE4\uC11C" },
            { "AWT.NResizeCursor", "\uBD81\uCABD \uBC29\uD5A5 \uD06C\uAE30 \uC870\uC815 \uCEE4\uC11C" },
            { "AWT.NWResizeCursor", "\uBD81\uC11C \uBC29\uD5A5 \uD06C\uAE30 \uC870\uC815 \uCEE4\uC11C" },
            { "AWT.SEResizeCursor", "\uB0A8\uB3D9 \uBC29\uD5A5 \uD06C\uAE30 \uC870\uC815 \uCEE4\uC11C" },
            { "AWT.SResizeCursor", "\uB0A8\uCABD \uBC29\uD5A5 \uD06C\uAE30 \uC870\uC815 \uCEE4\uC11C" },
            { "AWT.SWResizeCursor", "\uB0A8\uC11C \uBC29\uD5A5 \uD06C\uAE30 \uC870\uC815 \uCEE4\uC11C" },
            { "AWT.TextCursor", "\uD14D\uC2A4\uD2B8 \uCEE4\uC11C" },
            { "AWT.WResizeCursor", "\uC11C\uCABD \uBC29\uD5A5 \uD06C\uAE30 \uC870\uC815 \uCEE4\uC11C" },
            { "AWT.WaitCursor", "\uB300\uAE30 \uCEE4\uC11C" },
            { "AWT.accept", "\uB3D9\uC758" },
            { "AWT.add", "NumPad +" },
            { "AWT.again", "\uB2E4\uC2DC" },
            { "AWT.allCandidates", "\uBAA8\uB4E0 \uD6C4\uBCF4" },
            { "AWT.alphanumeric", "\uC601\uC22B\uC790" },
            { "AWT.alt", "Alt" },
            { "AWT.altGraph", "Alt Graph" },
            { "AWT.ampersand", "Ampersand" },
            { "AWT.asterisk", "Asterisk" },
            { "AWT.at", "At" },
            { "AWT.backQuote", "Back Quote" },
            { "AWT.backSlash", "Back Slash" },
            { "AWT.backSpace", "Backspace" },
            { "AWT.begin", "Begin" },
            { "AWT.braceLeft", "Left Brace" },
            { "AWT.braceRight", "Right Brace" },
            { "AWT.cancel", "Cancel" },
            { "AWT.capsLock", "Caps Lock" },
            { "AWT.circumflex", "Circumflex" },
            { "AWT.clear", "Clear" },
            { "AWT.closeBracket", "Close Bracket" },
            { "AWT.codeInput", "\uCF54\uB4DC \uC785\uB825" },
            { "AWT.colon", "Colon" },
            { "AWT.comma", "Comma" },
            { "AWT.compose", "\uAD6C\uC131" },
            { "AWT.context", "Context Menu" },
            { "AWT.control", "Ctrl" },
            { "AWT.convert", "\uBCC0\uD658" },
            { "AWT.copy", "\uBCF5\uC0AC" },
            { "AWT.cut", "\uC798\uB77C\uB0B4\uAE30" },
            { "AWT.deadAboveDot", "Dead Above Dot" },
            { "AWT.deadAboveRing", "Dead Above Ring" },
            { "AWT.deadAcute", "Dead Acute" },
            { "AWT.deadBreve", "Dead Breve" },
            { "AWT.deadCaron", "Dead Caron" },
            { "AWT.deadCedilla", "Dead Cedilla" },
            { "AWT.deadCircumflex", "Dead Circumflex" },
            { "AWT.deadDiaeresis", "Dead Diaeresis" },
            { "AWT.deadDoubleAcute", "Dead Double Acute" },
            { "AWT.deadGrave", "Dead Grave" },
            { "AWT.deadIota", "Dead Iota" },
            { "AWT.deadMacron", "Dead Macron" },
            { "AWT.deadOgonek", "Dead Ogonek" },
            { "AWT.deadSemivoicedSound", "Dead Semivoiced Sound" },
            { "AWT.deadTilde", "Dead Tilde" },
            { "AWT.deadVoicedSound", "Dead Voiced Sound" },
            { "AWT.decimal", "NumPad ." },
            { "AWT.delete", "Delete" },
            { "AWT.divide", "NumPad /" },
            { "AWT.dollar", "Dollar" },
            { "AWT.down", "Down" },
            { "AWT.end", "End" },
            { "AWT.enter", "Enter" },
            { "AWT.equals", "Equals" },
            { "AWT.escape", "Escape" },
            { "AWT.euro", "Euro" },
            { "AWT.exclamationMark", "Exclamation Mark" },
            { "AWT.f1", "F1" },
            { "AWT.f10", "F10" },
            { "AWT.f11", "F11" },
            { "AWT.f12", "F12" },
            { "AWT.f13", "F13" },
            { "AWT.f14", "F14" },
            { "AWT.f15", "F15" },
            { "AWT.f16", "F16" },
            { "AWT.f17", "F17" },
            { "AWT.f18", "F18" },
            { "AWT.f19", "F19" },
            { "AWT.f2", "F2" },
            { "AWT.f20", "F20" },
            { "AWT.f21", "F21" },
            { "AWT.f22", "F22" },
            { "AWT.f23", "F23" },
            { "AWT.f24", "F24" },
            { "AWT.f3", "F3" },
            { "AWT.f4", "F4" },
            { "AWT.f5", "F5" },
            { "AWT.f6", "F6" },
            { "AWT.f7", "F7" },
            { "AWT.f8", "F8" },
            { "AWT.f9", "F9" },
            { "AWT.final", "Final" },
            { "AWT.find", "\uCC3E\uAE30" },
            { "AWT.fullWidth", "Full-Width" },
            { "AWT.greater", "Greater" },
            { "AWT.halfWidth", "Half-Width" },
            { "AWT.help", "Help" },
            { "AWT.hiragana", "\uD788\uB77C\uAC00\uB098" },
            { "AWT.home", "Home" },
            { "AWT.inputMethodOnOff", "\uC785\uB825 \uBC29\uBC95 \uC124\uC815/\uD574\uC81C" },
            { "AWT.insert", "Insert" },
            { "AWT.invertedExclamationMark", "Inverted Exclamation Mark" },
            { "AWT.japaneseHiragana", "\uC77C\uBCF8\uC5B4 \uD788\uB77C\uAC00\uB098" },
            { "AWT.japaneseKatakana", "\uC77C\uBCF8\uC5B4 \uAC00\uD0C0\uCE74\uB098" },
            { "AWT.japaneseRoman", "\uC77C\uBCF8\uC5B4 \uB85C\uB9C8 \uBB38\uC790" },
            { "AWT.kana", "\uAC00\uB098" },
            { "AWT.kanaLock", "\uAC00\uB098 \uC7A0\uAE08" },
            { "AWT.kanji", "\uAC04\uC9C0" },
            { "AWT.katakana", "\uAC00\uD0C0\uCE74\uB098" },
            { "AWT.left", "Left" },
            { "AWT.leftParenthesis", "Left Parenthesis" },
            { "AWT.meta", "Meta" },
            { "AWT.minus", "Minus" },
            { "AWT.modechange", "\uBAA8\uB4DC \uBCC0\uACBD" },
            { "AWT.multiply", "NumPad *" },
            { "AWT.noconvert", "\uBCC0\uD658 \uC548\uD568" },
            { "AWT.numLock", "Num Lock" },
            { "AWT.numberSign", "Number Sign" },
            { "AWT.numpad", "NumPad" },
            { "AWT.openBracket", "Open Bracket" },
            { "AWT.paste", "\uBD99\uC5EC\uB123\uAE30" },
            { "AWT.pause", "Pause" },
            { "AWT.period", "Period" },
            { "AWT.pgdn", "Page Down" },
            { "AWT.pgup", "Page Up" },
            { "AWT.plus", "Plus" },
            { "AWT.previousCandidate", "\uC774\uC804 \uD6C4\uBCF4" },
            { "AWT.printScreen", "Print Screen" },
            { "AWT.props", "Props" },
            { "AWT.quote", "Quote" },
            { "AWT.quoteDbl", "Double Quote" },
            { "AWT.right", "Right" },
            { "AWT.rightParenthesis", "Right Parenthesis" },
            { "AWT.romanCharacters", "\uB85C\uB9C8 \uBB38\uC790" },
            { "AWT.scrollLock", "Scroll Lock" },
            { "AWT.semicolon", "Semicolon" },
            { "AWT.separater", "NumPad ," },
            { "AWT.separator", "NumPad ," },
            { "AWT.shift", "Shift" },
            { "AWT.slash", "Slash" },
            { "AWT.space", "Space" },
            { "AWT.stop", "\uC815\uC9C0" },
            { "AWT.subtract", "NumPad -" },
            { "AWT.tab", "Tab" },
            { "AWT.undefined", "\uC815\uC758\uB418\uC9C0 \uC54A\uC74C" },
            { "AWT.underscore", "Underscore" },
            { "AWT.undo", "\uC2E4\uD589 \uCDE8\uC18C" },
            { "AWT.unknown", "\uC54C \uC218 \uC5C6\uC74C" },
            { "AWT.up", "Up" },
            { "AWT.windows", "Windows" },
            { "java.awt.def.delay", "30" },
            { "java.awt.im.style", "on-the-spot" },
        };
    }
}
