package com.sun.accessibility.internal.resources;

import java.util.ListResourceBundle;

public final class accessibility_de extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "active", "aktiv" },
            { "alert", "Alert" },
            { "armed", "aktiviert" },
            { "awtcomponent", "AWT-Komponente" },
            { "busy", "ausgelastet" },
            { "canvas", "Leinwand" },
            { "checkbox", "Kontrollk\u00E4stchen" },
            { "checked", "markiert" },
            { "childNodeOf", "untergeordneter Knoten von" },
            { "collapsed", "ausgeblendet" },
            { "colorchooser", "Farbauswahl" },
            { "columnheader", "Spaltenheader" },
            { "combobox", "Kombinationsfeld" },
            { "controlledBy", "controlledBy" },
            { "controllerFor", "controllerFor" },
            { "desktopicon", "Desktopsymbol" },
            { "desktoppane", "Desktopbereich" },
            { "dialog", "Dialogfeld" },
            { "directorypane", "Verzeichnisbereich" },
            { "editable", "bearbeitbar" },
            { "editbar", "Bearbeitungsleiste" },
            { "embeddedBy", "eingebettet in" },
            { "embeds", "bettet ein" },
            { "enabled", "aktiviert" },
            { "expandable", "erweiterbar" },
            { "expanded", "eingeblendet" },
            { "filechooser", "Dateiauswahl" },
            { "filler", "F\u00FCllbereich" },
            { "flowsFrom", "flie\u00DFt von" },
            { "flowsTo", "flie\u00DFt zu" },
            { "focusable", "fokussierbar" },
            { "focused", "fokussiert" },
            { "footer", "Footer" },
            { "frame", "Rahmen" },
            { "glasspane", "Glass Pane" },
            { "header", "Header" },
            { "horizontal", "horizontal" },
            { "htmlcontainer", "HTML-Container" },
            { "iconified", "minimiert" },
            { "indeterminate", "unbestimmt" },
            { "internalframe", "Innerer Rahmen" },
            { "label", "Label" },
            { "labelFor", "Label f\u00FCr" },
            { "labeledBy", "beschriftet von" },
            { "layeredpane", "Layered Pane" },
            { "list", "Liste" },
            { "listitem", "Listenelement" },
            { "managesDescendants", "verwaltet untergeordnete Objekte" },
            { "memberOf", "Mitglied von" },
            { "menu", "Men\u00FC" },
            { "menubar", "Men\u00FCleiste" },
            { "menuitem", "Men\u00FCpunkt" },
            { "modal", "modal" },
            { "multiline", "mehrzeilig" },
            { "multiselectable", "mehrfach ausw\u00E4hlbar" },
            { "opaque", "nicht transparent" },
            { "optionpane", "Optionsbereich" },
            { "pagetab", "Registerkarte" },
            { "pagetablist", "Registerkartenliste" },
            { "panel", "Bereich" },
            { "paragraph", "Absatz" },
            { "parentWindowOf", "\u00FCbergeordnetes Fenster von" },
            { "passwordtext", "Kennworttext" },
            { "popupmenu", "Popup-Men\u00FC" },
            { "pressed", "gedr\u00FCckt" },
            { "progressMonitor", "Fortschrittsmonitor" },
            { "progressbar", "Fortschrittsbalken" },
            { "pushbutton", "Schaltfl\u00E4che" },
            { "radiobutton", "Optionsfeld" },
            { "resizable", "skalierbar" },
            { "rootpane", "Root-Bereich" },
            { "rowheader", "Zeilenheader" },
            { "ruler", "Lineal" },
            { "scrollbar", "Bildlaufleiste" },
            { "scrollpane", "Bildlaufbereich" },
            { "selectable", "w\u00E4hlbar" },
            { "selected", "ausgew\u00E4hlt" },
            { "separator", "Trennzeichen" },
            { "showing", "angezeigt" },
            { "singleline", "einzeilig" },
            { "slider", "Schieberegler" },
            { "splitpane", "Split Pane" },
            { "subwindowOf", "Unterfenster von" },
            { "swingcomponent", "Swing-Komponente" },
            { "table", "Tabelle" },
            { "text", "Text" },
            { "togglebutton", "Umschaltfl\u00E4che" },
            { "toggleexpand", "einblenden umschalten" },
            { "toolbar", "Symbolleiste" },
            { "tooltip", "QuickInfo" },
            { "transient", "transient" },
            { "tree", "Baumstruktur" },
            { "truncated", "abgeschnitten" },
            { "unknown", "Unbekannt" },
            { "vertical", "vertikal" },
            { "viewport", "Viewport" },
            { "visible", "sichtbar" },
            { "window", "Fenster" },
        };
    }
}
