// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !

package sun.awt.X11;

import jdk.internal.misc.Unsafe;

import sun.util.logging.PlatformLogger;
public class XArc extends XWrapperBase { 
	private Unsafe unsafe = XlibWrapper.unsafe; 
	private final boolean should_free_memory;
	public static int getSize() { return 12; }
	public int getDataSize() { return getSize(); }

	long pData;

	public long getPData() { return pData; }


	public XArc(long addr) {
		log.finest("Creating");
		pData=addr;
		should_free_memory = false;
	}


	public XArc() {
		log.finest("Creating");
		pData = unsafe.allocateMemory(getSize());
		should_free_memory = true;
	}


	public void dispose() {
		log.finest("Disposing");
		if (should_free_memory) {
			log.finest("freeing memory");
			unsafe.freeMemory(pData); 
	}
		}
	public short get_x() { log.finest("");return (Native.getShort(pData+0)); }
	public void set_x(short v) { log.finest(""); Native.putShort(pData+0, v); }
	public short get_y() { log.finest("");return (Native.getShort(pData+2)); }
	public void set_y(short v) { log.finest(""); Native.putShort(pData+2, v); }
	public short get_width() { log.finest("");return (Native.getShort(pData+4)); }
	public void set_width(short v) { log.finest(""); Native.putShort(pData+4, v); }
	public short get_height() { log.finest("");return (Native.getShort(pData+6)); }
	public void set_height(short v) { log.finest(""); Native.putShort(pData+6, v); }
	public short get_angle1() { log.finest("");return (Native.getShort(pData+8)); }
	public void set_angle1(short v) { log.finest(""); Native.putShort(pData+8, v); }
	public short get_angle2() { log.finest("");return (Native.getShort(pData+10)); }
	public void set_angle2(short v) { log.finest(""); Native.putShort(pData+10, v); }


	String getName() {
		return "XArc"; 
	}


	String getFieldsAsString() {
		StringBuilder ret = new StringBuilder(240);

		ret.append("x = ").append( get_x() ).append(", ");
		ret.append("y = ").append( get_y() ).append(", ");
		ret.append("width = ").append( get_width() ).append(", ");
		ret.append("height = ").append( get_height() ).append(", ");
		ret.append("angle1 = ").append( get_angle1() ).append(", ");
		ret.append("angle2 = ").append( get_angle2() ).append(", ");
		return ret.toString();
	}


}



