// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !

package sun.awt.X11;

import jdk.internal.misc.Unsafe;

import sun.util.logging.PlatformLogger;
public class XHostAddress extends XWrapperBase { 
	private Unsafe unsafe = XlibWrapper.unsafe; 
	private final boolean should_free_memory;
	public static int getSize() { return 16; }
	public int getDataSize() { return getSize(); }

	long pData;

	public long getPData() { return pData; }


	public XHostAddress(long addr) {
		log.finest("Creating");
		pData=addr;
		should_free_memory = false;
	}


	public XHostAddress() {
		log.finest("Creating");
		pData = unsafe.allocateMemory(getSize());
		should_free_memory = true;
	}


	public void dispose() {
		log.finest("Disposing");
		if (should_free_memory) {
			log.finest("freeing memory");
			unsafe.freeMemory(pData); 
	}
		}
	public int get_family() { log.finest("");return (Native.getInt(pData+0)); }
	public void set_family(int v) { log.finest(""); Native.putInt(pData+0, v); }
	public int get_length() { log.finest("");return (Native.getInt(pData+4)); }
	public void set_length(int v) { log.finest(""); Native.putInt(pData+4, v); }
	public long get_address(int index) { log.finest(""); return Native.getLong(pData+8)+index*Native.getLongSize(); }
	public long get_address() { log.finest("");return Native.getLong(pData+8); }
	public void set_address(long v) { log.finest(""); Native.putLong(pData + 8, v); }


	String getName() {
		return "XHostAddress"; 
	}


	String getFieldsAsString() {
		StringBuilder ret = new StringBuilder(120);

		ret.append("family = ").append( get_family() ).append(", ");
		ret.append("length = ").append( get_length() ).append(", ");
		ret.append("address = ").append( get_address() ).append(", ");
		return ret.toString();
	}


}



