// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !

package sun.awt.X11;

import jdk.internal.misc.Unsafe;

import sun.util.logging.PlatformLogger;
public class XkbNewKeyboardNotifyEvent extends XWrapperBase { 
	private Unsafe unsafe = XlibWrapper.unsafe; 
	private final boolean should_free_memory;
	public static int getSize() { return 80; }
	public int getDataSize() { return getSize(); }

	long pData;

	public long getPData() { return pData; }


	public XkbNewKeyboardNotifyEvent(long addr) {
		log.finest("Creating");
		pData=addr;
		should_free_memory = false;
	}


	public XkbNewKeyboardNotifyEvent() {
		log.finest("Creating");
		pData = unsafe.allocateMemory(getSize());
		should_free_memory = true;
	}


	public void dispose() {
		log.finest("Disposing");
		if (should_free_memory) {
			log.finest("freeing memory");
			unsafe.freeMemory(pData); 
	}
		}
	public int get_type() { log.finest("");return (Native.getInt(pData+0)); }
	public void set_type(int v) { log.finest(""); Native.putInt(pData+0, v); }
	public long get_serial() { log.finest("");return (Native.getULong(pData+8)); }
	public void set_serial(long v) { log.finest(""); Native.putULong(pData+8, v); }
	public boolean get_send_event() { log.finest("");return (Native.getBool(pData+16)); }
	public void set_send_event(boolean v) { log.finest(""); Native.putBool(pData+16, v); }
	public long get_display() { log.finest("");return (Native.getLong(pData+24)); }
	public void set_display(long v) { log.finest(""); Native.putLong(pData+24, v); }
	public long get_time() { log.finest("");return (Native.getULong(pData+32)); }
	public void set_time(long v) { log.finest(""); Native.putULong(pData+32, v); }
	public int get_xkb_type() { log.finest("");return (Native.getInt(pData+40)); }
	public void set_xkb_type(int v) { log.finest(""); Native.putInt(pData+40, v); }
	public int get_device() { log.finest("");return (Native.getInt(pData+44)); }
	public void set_device(int v) { log.finest(""); Native.putInt(pData+44, v); }
	public int get_old_device() { log.finest("");return (Native.getInt(pData+48)); }
	public void set_old_device(int v) { log.finest(""); Native.putInt(pData+48, v); }
	public int get_min_key_code() { log.finest("");return (Native.getInt(pData+52)); }
	public void set_min_key_code(int v) { log.finest(""); Native.putInt(pData+52, v); }
	public int get_max_key_code() { log.finest("");return (Native.getInt(pData+56)); }
	public void set_max_key_code(int v) { log.finest(""); Native.putInt(pData+56, v); }
	public int get_old_min_key_code() { log.finest("");return (Native.getInt(pData+60)); }
	public void set_old_min_key_code(int v) { log.finest(""); Native.putInt(pData+60, v); }
	public int get_old_max_key_code() { log.finest("");return (Native.getInt(pData+64)); }
	public void set_old_max_key_code(int v) { log.finest(""); Native.putInt(pData+64, v); }
	public int get_changed() { log.finest("");return (Native.getInt(pData+68)); }
	public void set_changed(int v) { log.finest(""); Native.putInt(pData+68, v); }
	public byte get_req_major() { log.finest("");return (Native.getByte(pData+72)); }
	public void set_req_major(byte v) { log.finest(""); Native.putByte(pData+72, v); }
	public byte get_req_minor() { log.finest("");return (Native.getByte(pData+73)); }
	public void set_req_minor(byte v) { log.finest(""); Native.putByte(pData+73, v); }


	String getName() {
		return "XkbNewKeyboardNotifyEvent"; 
	}


	String getFieldsAsString() {
		StringBuilder ret = new StringBuilder(600);

		ret.append("type = ").append( XlibWrapper.eventToString[get_type()] ).append(", ");
		ret.append("serial = ").append( get_serial() ).append(", ");
		ret.append("send_event = ").append( get_send_event() ).append(", ");
		ret.append("display = ").append( get_display() ).append(", ");
		ret.append("time = ").append( get_time() ).append(", ");
		ret.append("xkb_type = ").append( get_xkb_type() ).append(", ");
		ret.append("device = ").append( get_device() ).append(", ");
		ret.append("old_device = ").append( get_old_device() ).append(", ");
		ret.append("min_key_code = ").append( get_min_key_code() ).append(", ");
		ret.append("max_key_code = ").append( get_max_key_code() ).append(", ");
		ret.append("old_min_key_code = ").append( get_old_min_key_code() ).append(", ");
		ret.append("old_max_key_code = ").append( get_old_max_key_code() ).append(", ");
		ret.append("changed = ").append( get_changed() ).append(", ");
		ret.append("req_major = ").append( get_req_major() ).append(", ");
		ret.append("req_minor = ").append( get_req_minor() ).append(", ");
		return ret.toString();
	}


}



