// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !

package sun.awt.X11;

import jdk.internal.misc.Unsafe;

import sun.util.logging.PlatformLogger;
public class XOMFontInfo extends XWrapperBase { 
	private Unsafe unsafe = XlibWrapper.unsafe; 
	private final boolean should_free_memory;
	public static int getSize() { return 24; }
	public int getDataSize() { return getSize(); }

	long pData;

	public long getPData() { return pData; }


	public XOMFontInfo(long addr) {
		log.finest("Creating");
		pData=addr;
		should_free_memory = false;
	}


	public XOMFontInfo() {
		log.finest("Creating");
		pData = unsafe.allocateMemory(getSize());
		should_free_memory = true;
	}


	public void dispose() {
		log.finest("Disposing");
		if (should_free_memory) {
			log.finest("freeing memory");
			unsafe.freeMemory(pData); 
	}
		}
	public int get_num_font() { log.finest("");return (Native.getInt(pData+0)); }
	public void set_num_font(int v) { log.finest(""); Native.putInt(pData+0, v); }
	public long get_font_struct_list(int index) { log.finest(""); return Native.getLong(pData+8)+index*Native.getLongSize(); }
	public long get_font_struct_list() { log.finest("");return Native.getLong(pData+8); }
	public void set_font_struct_list(long v) { log.finest(""); Native.putLong(pData + 8, v); }
	public long get_font_name_list(int index) { log.finest(""); return Native.getLong(pData+16)+index*Native.getLongSize(); }
	public long get_font_name_list() { log.finest("");return Native.getLong(pData+16); }
	public void set_font_name_list(long v) { log.finest(""); Native.putLong(pData + 16, v); }


	String getName() {
		return "XOMFontInfo"; 
	}


	String getFieldsAsString() {
		StringBuilder ret = new StringBuilder(120);

		ret.append("num_font = ").append( get_num_font() ).append(", ");
		ret.append("font_struct_list = ").append( get_font_struct_list() ).append(", ");
		ret.append("font_name_list = ").append( get_font_name_list() ).append(", ");
		return ret.toString();
	}


}



