// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !

package sun.awt.X11;

import jdk.internal.misc.Unsafe;

import sun.util.logging.PlatformLogger;
public class XRectangle extends XWrapperBase { 
	private Unsafe unsafe = XlibWrapper.unsafe; 
	private final boolean should_free_memory;
	public static int getSize() { return 8; }
	public int getDataSize() { return getSize(); }

	long pData;

	public long getPData() { return pData; }


	public XRectangle(long addr) {
		log.finest("Creating");
		pData=addr;
		should_free_memory = false;
	}


	public XRectangle() {
		log.finest("Creating");
		pData = unsafe.allocateMemory(getSize());
		should_free_memory = true;
	}


	public void dispose() {
		log.finest("Disposing");
		if (should_free_memory) {
			log.finest("freeing memory");
			unsafe.freeMemory(pData); 
	}
		}
	public short get_x() { log.finest("");return (Native.getShort(pData+0)); }
	public void set_x(short v) { log.finest(""); Native.putShort(pData+0, v); }
	public short get_y() { log.finest("");return (Native.getShort(pData+2)); }
	public void set_y(short v) { log.finest(""); Native.putShort(pData+2, v); }
	public short get_width() { log.finest("");return (Native.getShort(pData+4)); }
	public void set_width(short v) { log.finest(""); Native.putShort(pData+4, v); }
	public short get_height() { log.finest("");return (Native.getShort(pData+6)); }
	public void set_height(short v) { log.finest(""); Native.putShort(pData+6, v); }


	String getName() {
		return "XRectangle"; 
	}


	String getFieldsAsString() {
		StringBuilder ret = new StringBuilder(160);

		ret.append("x = ").append( get_x() ).append(", ");
		ret.append("y = ").append( get_y() ).append(", ");
		ret.append("width = ").append( get_width() ).append(", ");
		ret.append("height = ").append( get_height() ).append(", ");
		return ret.toString();
	}


}



