package org.omg.IOP;


/**
* org/omg/IOP/CodeSets.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from t:/workspace/open/src/java.corba/share/classes/org/omg/PortableInterceptor/IOP.idl
* Wednesday, March 7, 2018 at 6:07:52 PM Pacific Standard Time
*/

public interface CodeSets
{

  /**
     * Identifies a CDR encapsulation of the 
     * <code>CONV_FRAME.CodeSetContext</code> defined in 
     * Section 13.10.2.5, "GIOP Code Set Service Context," on page 13-43.
     */
  public static final int value = (int)(1L);
}
