/*
 * Copyright (c) 2015, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package com.sun.tools.doclets.formats.html.markup;

/**
 * Enum representing the version of HTML generated by javadoc.
 *
 * @author Bhavesh Patel
 */
@Deprecated
public enum HtmlVersion {
    HTML4,
    HTML5,
    ALL
}
