/*
 * %Z%file      %M%
 * %Z%author    Sun Microsystems, Inc.
 * %Z%version   %I%
 * %Z%date      %D%
 *
 * Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 */


/* Generated By:JJTree: Do not edit this line. JDMCommunity.java */

package com.sun.jmx.snmp.IPAcl;

/** 
 * @version     %I%     %G% 
 * @author      Sun Microsystems, Inc. 
 */ 
class JDMCommunity extends SimpleNode {
  protected String communityString= "";

  JDMCommunity(int id) {
    super(id);
  }

  JDMCommunity(Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new JDMCommunity(id);
  }

  public static Node jjtCreate(Parser p, int id) {
      return new JDMCommunity(p, id);
  }

  public String getCommunity(){
	return communityString;
  }
}
