/*
 * %Z%file      %M%
 * %Z%author    Sun Microsystems, Inc.
 * %Z%version   %I%
 * %Z%date      %D%
 *
 * Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

/* Generated By:JJTree: Do not edit this line. JDMHostInform.java */

package com.sun.jmx.snmp.IPAcl;

class JDMHostInform extends SimpleNode {
    protected String name= "";
    
    JDMHostInform(int id) {
        super(id);
    }

    JDMHostInform(Parser p, int id) {
        super(p, id);
    }
    
    public static Node jjtCreate(int id) {
        return new JDMHostInform(id);
    }

    public static Node jjtCreate(Parser p, int id) {
        return new JDMHostInform(p, id);
    }
}
