/*
 * %Z%file      %M%
 * %Z%author    Sun Microsystems, Inc.
 * %Z%version   %I%
 * %Z%date      %D%
 *
 * Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 */

/* Generated By:JJTree: Do not edit this line. JDMNetMaskV6.java */

package com.sun.jmx.snmp.IPAcl;

import java.net.UnknownHostException;

class JDMNetMaskV6 extends JDMNetMask {
  public JDMNetMaskV6(int id) {
    super(id);
  }

  public JDMNetMaskV6(Parser p, int id) {
    super(p, id);
  }
    protected PrincipalImpl createAssociatedPrincipal() 
    throws UnknownHostException { 
      return new NetMaskImpl(address.toString(), Integer.parseInt(mask));
  }
}
