/*
 * %Z%file      %M%
 * %Z%author    Sun Microsystems, Inc.
 * %Z%version   %I%
 * %Z%date      %D%
 *
 * Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 */


/* Generated By:JJTree: Do not edit this line. JDMTrapInterestedHost.java */

package com.sun.jmx.snmp.IPAcl;

/** 
 * @version     %I%     %G% 
 * @author      Sun Microsystems, Inc. 
 */ 
class JDMTrapInterestedHost extends SimpleNode {
  JDMTrapInterestedHost(int id) {
    super(id);
  }

  JDMTrapInterestedHost(Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new JDMTrapInterestedHost(id);
  }

  public static Node jjtCreate(Parser p, int id) {
      return new JDMTrapInterestedHost(p, id);
  }
}
