/*
 * %Z%file      %M%
 * %Z%author    Sun Microsystems, Inc.
 * %Z%version   %I%
 * %Z%date      %D%
 *
 * Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 */


/* Generated By:JavaCC: Do not edit this line. ParseError.java Version 0.7pre1 */
package com.sun.jmx.snmp.IPAcl;

class ParseError extends Exception {
   public ParseError() {
   }
   public ParseError(String message) {
      super(message);
   }
}
