package com.sun.accessibility.internal.resources;

import java.util.ListResourceBundle;

public final class accessibility_it extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "active", "attivo" },
            { "alert", "avviso" },
            { "armed", "abilitato" },
            { "awtcomponent", "componente AWT" },
            { "busy", "occupato" },
            { "canvas", "sfondo" },
            { "checkbox", "casella di controllo" },
            { "checked", "verificato" },
            { "childNodeOf", "nodo figlio di" },
            { "collapsed", "compresso" },
            { "colorchooser", "selezione colori" },
            { "columnheader", "intestazione colonna" },
            { "combobox", "casella combinata" },
            { "controlledBy", "controlledBy" },
            { "controllerFor", "controllerFor" },
            { "desktopicon", "icona desktop" },
            { "desktoppane", "riquadro desktop" },
            { "dialog", "finestra di dialogo" },
            { "directorypane", "riquadro directory" },
            { "editable", "modificabile" },
            { "editbar", "barra di modifica" },
            { "embeddedBy", "incorporato da" },
            { "embeds", "incorpora" },
            { "enabled", "abilitato" },
            { "expandable", "espandibile" },
            { "expanded", "espanso" },
            { "filechooser", "selezione file" },
            { "filler", "utilit\u00E0 riempimento" },
            { "flowsFrom", "proviene da" },
            { "flowsTo", "va verso" },
            { "focusable", "attivabile in primo piano" },
            { "focused", "in primo piano" },
            { "footer", "pi\u00E8 di pagina" },
            { "frame", "cornice" },
            { "glasspane", "riquadro trasparente" },
            { "header", "intestazione" },
            { "horizontal", "orizzontale" },
            { "htmlcontainer", "Contenitore HTML" },
            { "iconified", "ridotto a icona" },
            { "indeterminate", "indeterminato" },
            { "internalframe", "cornice interna" },
            { "label", "etichetta" },
            { "labelFor", "etichetta per" },
            { "labeledBy", "etichetta di" },
            { "layeredpane", "riquadro a livelli" },
            { "list", "lista" },
            { "listitem", "voce lista" },
            { "managesDescendants", "gestisce i discendenti" },
            { "memberOf", "membro di" },
            { "menu", "menu" },
            { "menubar", "barra dei menu" },
            { "menuitem", "voce di menu" },
            { "modal", "modale" },
            { "multiline", "a righe multiple" },
            { "multiselectable", "multi-selezionabile" },
            { "opaque", "nascosto" },
            { "optionpane", "riquadro opzioni" },
            { "pagetab", "scheda pagina" },
            { "pagetablist", "lista schede pagina" },
            { "panel", "pannello" },
            { "paragraph", "paragrafo" },
            { "parentWindowOf", "finestra di livello superiore di" },
            { "passwordtext", "testo della password" },
            { "popupmenu", "menu popup" },
            { "pressed", "premuto" },
            { "progressMonitor", "stato avanzamento" },
            { "progressbar", "barra di avanzamento" },
            { "pushbutton", "pulsante" },
            { "radiobutton", "pulsante di scelta" },
            { "resizable", "ridimensionabile" },
            { "rootpane", "riquadro root" },
            { "rowheader", "intestazione di riga" },
            { "ruler", "righello" },
            { "scrollbar", "barra di scorrimento" },
            { "scrollpane", "riquadro scorrimento" },
            { "selectable", "selezionabile" },
            { "selected", "selezionato" },
            { "separator", "separatore" },
            { "showing", "visualizzato" },
            { "singleline", "a riga singola" },
            { "slider", "dispositivo di scorrimento" },
            { "splitpane", "riquadro doppio" },
            { "subwindowOf", "sottofinestra di" },
            { "swingcomponent", "componente swing" },
            { "table", "tabella" },
            { "text", "testo" },
            { "togglebutton", "interruttore" },
            { "toggleexpand", "attiva/disattiva espansione" },
            { "toolbar", "barra degli strumenti" },
            { "tooltip", "descrizione comandi" },
            { "transient", "transitorio" },
            { "tree", "albero" },
            { "truncated", "troncato" },
            { "unknown", "sconosciuto" },
            { "vertical", "verticale" },
            { "viewport", "viewport" },
            { "visible", "visibile" },
            { "window", "finestra" },
        };
    }
}
