package com.sun.accessibility.internal.resources;

import java.util.ListResourceBundle;

public final class accessibility_sv extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "active", "aktiv" },
            { "alert", "avisering" },
            { "armed", "redo" },
            { "awtcomponent", "AWT-komponent" },
            { "busy", "upptagen" },
            { "canvas", "rityta" },
            { "checkbox", "kryssruta" },
            { "checked", "markerad" },
            { "childNodeOf", "underordnad nod f\u00F6r" },
            { "collapsed", "komprimerad" },
            { "colorchooser", "f\u00E4rgv\u00E4ljare" },
            { "columnheader", "kolumnrubrik" },
            { "combobox", "kombinationsruta" },
            { "controlledBy", "controlledBy" },
            { "controllerFor", "controllerFor" },
            { "desktopicon", "skrivbordsikon" },
            { "desktoppane", "skrivbordsruta" },
            { "dialog", "dialogruta" },
            { "directorypane", "katalogruta" },
            { "editable", "redigerbar" },
            { "editbar", "redigeringslist" },
            { "embeddedBy", "b\u00E4ddas in av" },
            { "embeds", "b\u00E4ddar in" },
            { "enabled", "aktiverad" },
            { "expandable", "ut\u00F6kningsbar" },
            { "expanded", "ut\u00F6kad" },
            { "filechooser", "filv\u00E4ljare" },
            { "filler", "utfyllnad" },
            { "flowsFrom", "fl\u00F6dar fr\u00E5n" },
            { "flowsTo", "fl\u00F6dar till" },
            { "focusable", "fokuseringsbar" },
            { "focused", "fokuserad" },
            { "footer", "sidfot" },
            { "frame", "ram" },
            { "glasspane", "glasruta" },
            { "header", "sidhuvud" },
            { "horizontal", "horisontell" },
            { "htmlcontainer", "HTML-container" },
            { "iconified", "minimerad" },
            { "indeterminate", "obest\u00E4mt" },
            { "internalframe", "intern ram" },
            { "label", "etikett" },
            { "labelFor", "etikett f\u00F6r" },
            { "labeledBy", "etikett av" },
            { "layeredpane", "staplad ruta" },
            { "list", "lista" },
            { "listitem", "listobjekt" },
            { "managesDescendants", "hanterar underordnade" },
            { "memberOf", "medlem i" },
            { "menu", "meny" },
            { "menubar", "menyrad" },
            { "menuitem", "menyalternativ" },
            { "modal", "modal" },
            { "multiline", "flera rader" },
            { "multiselectable", "flerval" },
            { "opaque", "ogenomskinlig" },
            { "optionpane", "alternativruta" },
            { "pagetab", "sidflik" },
            { "pagetablist", "sidflikslista" },
            { "panel", "panel" },
            { "paragraph", "stycke" },
            { "parentWindowOf", "\u00F6verordnat f\u00F6nster f\u00F6r" },
            { "passwordtext", "l\u00F6senordstext" },
            { "popupmenu", "snabbmeny" },
            { "pressed", "nedtryckt" },
            { "progressMonitor", "f\u00F6rlopps\u00F6vervakare" },
            { "progressbar", "statusrad" },
            { "pushbutton", "knapp" },
            { "radiobutton", "alternativknapp" },
            { "resizable", "storleks\u00E4ndringsbar" },
            { "rootpane", "grundruta" },
            { "rowheader", "radrubrik" },
            { "ruler", "linjal" },
            { "scrollbar", "rullningslist" },
            { "scrollpane", "rullningsruta" },
            { "selectable", "valbar" },
            { "selected", "vald" },
            { "separator", "avskiljare" },
            { "showing", "visar" },
            { "singleline", "en rad" },
            { "slider", "skjutreglage" },
            { "splitpane", "delad ruta" },
            { "subwindowOf", "delf\u00F6nster av" },
            { "swingcomponent", "swing-komponent" },
            { "table", "tabell" },
            { "text", "text" },
            { "togglebutton", "v\u00E4xlingsknapp" },
            { "toggleexpand", "v\u00E4xla expandering" },
            { "toolbar", "verktygsrad" },
            { "tooltip", "knappbeskrivning" },
            { "transient", "tillf\u00E4llig" },
            { "tree", "tr\u00E4d" },
            { "truncated", "kapad" },
            { "unknown", "ok\u00E4nd" },
            { "vertical", "vertikal" },
            { "viewport", "vyport" },
            { "visible", "synlig" },
            { "window", "f\u00F6nster" },
        };
    }
}
