package com.sun.accessibility.internal.resources;

import java.util.ListResourceBundle;

public final class accessibility_es extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "active", "activo" },
            { "alert", "alerta" },
            { "armed", "armado" },
            { "awtcomponent", "componente AWT" },
            { "busy", "ocupado" },
            { "canvas", "lienzo" },
            { "checkbox", "casilla de control" },
            { "checked", "activado" },
            { "childNodeOf", "nodo secundario de" },
            { "collapsed", "reducido" },
            { "colorchooser", "selector de color" },
            { "columnheader", "cabecera de columna" },
            { "combobox", "cuadro combinado" },
            { "controlledBy", "controlledBy" },
            { "controllerFor", "controllerFor" },
            { "desktopicon", "icono de escritorio" },
            { "desktoppane", "panel de escritorio" },
            { "dialog", "cuadro de di\u00E1logo" },
            { "directorypane", "panel de directorio" },
            { "editable", "editable" },
            { "editbar", "barra de edici\u00F3n" },
            { "embeddedBy", "embebido por" },
            { "embeds", "embebe" },
            { "enabled", "activado" },
            { "expandable", "ampliable" },
            { "expanded", "ampliado" },
            { "filechooser", "selector de archivos" },
            { "filler", "rellenador" },
            { "flowsFrom", "procede de" },
            { "flowsTo", "llega a" },
            { "focusable", "enfocable" },
            { "focused", "enfocado" },
            { "footer", "pie" },
            { "frame", "marco" },
            { "glasspane", "panel de cristal" },
            { "header", "cabecera" },
            { "horizontal", "horizontal" },
            { "htmlcontainer", "Contenedor HTML" },
            { "iconified", "convertido en icono" },
            { "indeterminate", "indeterminada" },
            { "internalframe", "marco interno" },
            { "label", "etiqueta" },
            { "labelFor", "etiqueta para" },
            { "labeledBy", "etiquetado por" },
            { "layeredpane", "panel en capas" },
            { "list", "lista" },
            { "listitem", "elemento de lista" },
            { "managesDescendants", "gestiona descendientes" },
            { "memberOf", "miembro de" },
            { "menu", "men\u00FA" },
            { "menubar", "barra de men\u00FAs" },
            { "menuitem", "elemento de men\u00FA" },
            { "modal", "modal" },
            { "multiline", "l\u00EDnea m\u00FAltiple" },
            { "multiselectable", "multiseleccionable" },
            { "opaque", "opaco" },
            { "optionpane", "panel de opciones" },
            { "pagetab", "separador de p\u00E1gina" },
            { "pagetablist", "lista de separadores de p\u00E1gina" },
            { "panel", "panel" },
            { "paragraph", "p\u00E1rrafo" },
            { "parentWindowOf", "ventana principal de" },
            { "passwordtext", "texto de contrase\u00F1a" },
            { "popupmenu", "men\u00FA emergente" },
            { "pressed", "pulsado" },
            { "progressMonitor", "monitor de progreso" },
            { "progressbar", "barra de progreso" },
            { "pushbutton", "bot\u00F3n" },
            { "radiobutton", "bot\u00F3n de radio" },
            { "resizable", "redimensionable" },
            { "rootpane", "panel ra\u00EDz" },
            { "rowheader", "cabecera de filas" },
            { "ruler", "regla" },
            { "scrollbar", "barra de desplazamiento" },
            { "scrollpane", "panel de desplazamiento" },
            { "selectable", "seleccionable" },
            { "selected", "seleccionado" },
            { "separator", "separador" },
            { "showing", "mostrando" },
            { "singleline", "l\u00EDnea \u00FAnica" },
            { "slider", "deslizador" },
            { "splitpane", "panel de divisi\u00F3n" },
            { "subwindowOf", "ventana subordinada de" },
            { "swingcomponent", "componente swing" },
            { "table", "tabla" },
            { "text", "texto" },
            { "togglebutton", "bot\u00F3n conmutador" },
            { "toggleexpand", "conmutar ampliaci\u00F3n" },
            { "toolbar", "barra de herramientas" },
            { "tooltip", "ayuda de burbuja" },
            { "transient", "transitorio" },
            { "tree", "\u00E1rbol" },
            { "truncated", "truncado" },
            { "unknown", "desconocido" },
            { "vertical", "vertical" },
            { "viewport", "viewport" },
            { "visible", "visible" },
            { "window", "ventana" },
        };
    }
}
