package com.sun.accessibility.internal.resources;

import java.util.ListResourceBundle;

public final class accessibility_pt_BR extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "active", "ativo" },
            { "alert", "alerta" },
            { "armed", "armado" },
            { "awtcomponent", "componente AWT" },
            { "busy", "ocupado" },
            { "canvas", "tela" },
            { "checkbox", "caixa de sele\u00E7\u00E3o" },
            { "checked", "selecionado" },
            { "childNodeOf", "n\u00F3 filho de" },
            { "collapsed", "contra\u00EDdo" },
            { "colorchooser", "seletor de cores" },
            { "columnheader", "cabe\u00E7alho da coluna" },
            { "combobox", "caixa de combina\u00E7\u00E3o" },
            { "controlledBy", "controlledBy" },
            { "controllerFor", "controllerFor" },
            { "desktopicon", "\u00EDcone da \u00E1rea de trabalho" },
            { "desktoppane", "painel da \u00E1rea de trabalho" },
            { "dialog", "caixa de di\u00E1logo" },
            { "directorypane", "painel do diret\u00F3rio" },
            { "editable", "edit\u00E1vel" },
            { "editbar", "barra de edi\u00E7\u00E3o" },
            { "embeddedBy", "integrado por" },
            { "embeds", "integra" },
            { "enabled", "ativado" },
            { "expandable", "expans\u00EDvel" },
            { "expanded", "expandido" },
            { "filechooser", "seletor de arquivos" },
            { "filler", "preenchedor" },
            { "flowsFrom", "fluxos de" },
            { "flowsTo", "fluxos para" },
            { "focusable", "focaliz\u00E1vel" },
            { "focused", "focalizado" },
            { "footer", "rodap\u00E9" },
            { "frame", "quadro" },
            { "glasspane", "painel transparente" },
            { "header", "cabe\u00E7alho" },
            { "horizontal", "horizontal" },
            { "htmlcontainer", "Container de HTML" },
            { "iconified", "iconizado" },
            { "indeterminate", "indeterminado" },
            { "internalframe", "quadro interno" },
            { "label", "r\u00F3tulo" },
            { "labelFor", "r\u00F3tulo de" },
            { "labeledBy", "rotulado por" },
            { "layeredpane", "painel em camadas" },
            { "list", "lista" },
            { "listitem", "item da lista" },
            { "managesDescendants", "gerencia descendentes" },
            { "memberOf", "membro de" },
            { "menu", "menu" },
            { "menubar", "barra de menus" },
            { "menuitem", "item do menu" },
            { "modal", "modal" },
            { "multiline", "v\u00E1rias linhas" },
            { "multiselectable", "m\u00FAltipla escolha" },
            { "opaque", "opaco" },
            { "optionpane", "painel de op\u00E7\u00F5es" },
            { "pagetab", "guia da p\u00E1gina" },
            { "pagetablist", "lista de guias da p\u00E1gina" },
            { "panel", "painel" },
            { "paragraph", "par\u00E1grafo" },
            { "parentWindowOf", "janela pai de" },
            { "passwordtext", "texto da senha" },
            { "popupmenu", "menu pop-up" },
            { "pressed", "pressionado" },
            { "progressMonitor", "monitor de progresso" },
            { "progressbar", "barra de progresso" },
            { "pushbutton", "bot\u00E3o de a\u00E7\u00E3o" },
            { "radiobutton", "bot\u00E3o de op\u00E7\u00E3o" },
            { "resizable", "redimension\u00E1vel" },
            { "rootpane", "painel base" },
            { "rowheader", "cabe\u00E7alho da linha" },
            { "ruler", "r\u00E9gua" },
            { "scrollbar", "barra de rolagem" },
            { "scrollpane", "painel de rolagem" },
            { "selectable", "selecion\u00E1vel" },
            { "selected", "selecionado" },
            { "separator", "separador" },
            { "showing", "mostrando" },
            { "singleline", "linha \u00FAnica" },
            { "slider", "controle deslizante" },
            { "splitpane", "painel dividido" },
            { "subwindowOf", "subjanela de" },
            { "swingcomponent", "componente swing" },
            { "table", "tabela" },
            { "text", "texto" },
            { "togglebutton", "bot\u00E3o de altern\u00E2ncia" },
            { "toggleexpand", "alternar expandir" },
            { "toolbar", "barra de ferramentas" },
            { "tooltip", "dica de ferramenta" },
            { "transient", "transit\u00F3rio" },
            { "tree", "\u00E1rvore" },
            { "truncated", "truncado" },
            { "unknown", "desconhecido" },
            { "vertical", "vertical" },
            { "viewport", "janela de visualiza\u00E7\u00E3o" },
            { "visible", "vis\u00EDvel" },
            { "window", "janela" },
        };
    }
}
