package com.sun.accessibility.internal.resources;

import java.util.ListResourceBundle;

public final class accessibility_fr extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "active", "actif" },
            { "alert", "alerte" },
            { "armed", "arm\u00E9" },
            { "awtcomponent", "composant AWT" },
            { "busy", "occup\u00E9" },
            { "canvas", "canevas" },
            { "checkbox", "case \u00E0 cocher" },
            { "checked", "coch\u00E9" },
            { "childNodeOf", "noeud enfant de" },
            { "collapsed", "r\u00E9duit" },
            { "colorchooser", "s\u00E9lecteur de couleurs" },
            { "columnheader", "en-t\u00EAte de colonne" },
            { "combobox", "liste d\u00E9roulante" },
            { "controlledBy", "contr\u00F4l\u00E9 par" },
            { "controllerFor", "contr\u00F4leur pour" },
            { "desktopicon", "ic\u00F4ne de bureau" },
            { "desktoppane", "panneau de bureau" },
            { "dialog", "bo\u00EEte de dialogue" },
            { "directorypane", "panneau de r\u00E9pertoires" },
            { "editable", "modifiable" },
            { "editbar", "barre d'\u00E9dition" },
            { "embeddedBy", "incorpor\u00E9 par" },
            { "embeds", "incorpore" },
            { "enabled", "activ\u00E9" },
            { "expandable", "extensible" },
            { "expanded", "d\u00E9velopp\u00E9" },
            { "filechooser", "s\u00E9lecteur de fichiers" },
            { "filler", "\u00E9l\u00E9ment de remplissage" },
            { "flowsFrom", "flux depuis" },
            { "flowsTo", "flux vers" },
            { "focusable", "zone d'entr\u00E9e possible" },
            { "focused", "avec zone d'entr\u00E9e" },
            { "footer", "pied de page" },
            { "frame", "cadre" },
            { "glasspane", "panneau de grossissement" },
            { "header", "en-t\u00EAte" },
            { "horizontal", "horizontal" },
            { "htmlcontainer", "conteneur HTML" },
            { "iconified", "r\u00E9duit \u00E0 une ic\u00F4ne" },
            { "indeterminate", "ind\u00E9termin\u00E9" },
            { "internalframe", "cadre interne" },
            { "label", "libell\u00E9" },
            { "labelFor", "libell\u00E9 de" },
            { "labeledBy", "libell\u00E9 par" },
            { "layeredpane", "panneau superpos\u00E9" },
            { "list", "liste" },
            { "listitem", "\u00E9l\u00E9ment de liste" },
            { "managesDescendants", "g\u00E8re les descendants" },
            { "memberOf", "membre de" },
            { "menu", "menu" },
            { "menubar", "barre de menus" },
            { "menuitem", "option de menu" },
            { "modal", "modal" },
            { "multiline", "ligne multiple" },
            { "multiselectable", "multis\u00E9lectionnable" },
            { "opaque", "opaque" },
            { "optionpane", "panneau d'options" },
            { "pagetab", "onglet de page" },
            { "pagetablist", "liste d'onglets de page" },
            { "panel", "panneau" },
            { "paragraph", "paragraphe" },
            { "parentWindowOf", "fen\u00EAtre parente de" },
            { "passwordtext", "texte de mot de passe" },
            { "popupmenu", "menu contextuel" },
            { "pressed", "enfonc\u00E9" },
            { "progressMonitor", "contr\u00F4le de la progression" },
            { "progressbar", "barre de progression" },
            { "pushbutton", "bouton" },
            { "radiobutton", "bouton radio" },
            { "resizable", "redimensionnable" },
            { "rootpane", "panneau racine" },
            { "rowheader", "en-t\u00EAte de ligne" },
            { "ruler", "r\u00E8gle" },
            { "scrollbar", "barre de d\u00E9filement" },
            { "scrollpane", "panneau de d\u00E9filement" },
            { "selectable", "s\u00E9lectionnable" },
            { "selected", "s\u00E9lectionn\u00E9" },
            { "separator", "s\u00E9parateur" },
            { "showing", "montrant" },
            { "singleline", "ligne unique" },
            { "slider", "curseur" },
            { "splitpane", "panneau divis\u00E9" },
            { "subwindowOf", "sous-fen\u00EAtre de" },
            { "swingcomponent", "composant Swing" },
            { "table", "tableau" },
            { "text", "texte" },
            { "togglebutton", "bouton de basculement" },
            { "toggleexpand", "activer/d\u00E9sactiver d\u00E9veloppement" },
            { "toolbar", "barre d'outils" },
            { "tooltip", "info-bulle" },
            { "transient", "non persistant" },
            { "tree", "arborescence" },
            { "truncated", "tronqu\u00E9" },
            { "unknown", "inconnu" },
            { "vertical", "vertical" },
            { "viewport", "lucarne" },
            { "visible", "visible" },
            { "window", "fen\u00EAtre" },
        };
    }
}
