package sun.awt.resources;

import java.util.ListResourceBundle;

public final class awt_it extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "AWT.CompositionWindowTitle", "Finestra di immissione" },
            { "AWT.CrosshairCursor", "Puntatore a croce" },
            { "AWT.DefaultCursor", "Cursore predefinito" },
            { "AWT.DefaultDragCursor", "Cursore di trascinamento predefinito" },
            { "AWT.DefaultDropCursor", "Cursore di rilasciamento predefinito" },
            { "AWT.DefaultNoDropCursor", "Cursore NoDrag predefinito" },
            { "AWT.EResizeCursor", "Cursore di ridimensionamento orientale" },
            { "AWT.HandCursor", "Cursore mano" },
            { "AWT.HostInputMethodDisplayName", "Metodi di immissione di sistema" },
            { "AWT.InconsistentDLLsWarning", "Le operazioni sul testo possono non funzionare correttamente, a causa di una serie non coerente di DLL installate sul sistema. Per ulteriori informazioni su questo problema e per la soluzione suggerita, vedere le note di rilascio di Java(TM) 2 SDK, Standard Edition su java.sun.com." },
            { "AWT.InputMethodCreationFailed", "Impossibile creare {0}.  Motivo: {1}" },
            { "AWT.InputMethodLanguage.ja", "Giapponese" },
            { "AWT.InputMethodLanguage.ko", "Coreano" },
            { "AWT.InputMethodLanguage.zh", "Cinese" },
            { "AWT.InputMethodLanguage.zh_CN", "Cinese semplificato" },
            { "AWT.InputMethodLanguage.zh_TW", "Cinese tradizionale" },
            { "AWT.InputMethodSelectionMenu", "Seleziona metodo di immissione" },
            { "AWT.Less", "Minore" },
            { "AWT.MoveCursor", "Sposta cursore" },
            { "AWT.NEResizeCursor", "Cursore di ridimensionamento nordorientale" },
            { "AWT.NResizeCursor", "Cursore di ridimensionamento settentrionale" },
            { "AWT.NWResizeCursor", "Cursore di ridimensionamento nordoccidentale" },
            { "AWT.SEResizeCursor", "Cursore di ridimensionamento sudorientale" },
            { "AWT.SResizeCursor", "Cursore di ridimensionamento meridionale" },
            { "AWT.SWResizeCursor", "Cursore di ridimensionamento sudoccidentale" },
            { "AWT.TextCursor", "Cursore testo" },
            { "AWT.WResizeCursor", "Cursore di ridimensionamento occidentale" },
            { "AWT.WaitCursor", "Cursore attesa" },
            { "AWT.accept", "Accetto" },
            { "AWT.add", "NumPad +" },
            { "AWT.again", "Ancora" },
            { "AWT.allCandidates", "Tutti i candidati" },
            { "AWT.alphanumeric", "Alfanumerico" },
            { "AWT.alt", "Alt" },
            { "AWT.altGraph", "Alt Gr" },
            { "AWT.ampersand", "E commerciale" },
            { "AWT.asterisk", "Asterisco" },
            { "AWT.at", "Chiocciola" },
            { "AWT.backQuote", "Apice invertito" },
            { "AWT.backSlash", "Barra rovesciata" },
            { "AWT.backSpace", "Backspace" },
            { "AWT.begin", "Inizio" },
            { "AWT.braceLeft", "Parentesi graffa aperta" },
            { "AWT.braceRight", "Parentesi graffa chiusa" },
            { "AWT.cancel", "Annulla" },
            { "AWT.capsLock", "Bloc Maiusc" },
            { "AWT.circumflex", "Circonflesso" },
            { "AWT.clear", "Cancella" },
            { "AWT.closeBracket", "Parentesi quadra chiusa" },
            { "AWT.codeInput", "Immissione codice" },
            { "AWT.colon", "Due punti" },
            { "AWT.comma", "Virgola" },
            { "AWT.compose", "Componi" },
            { "AWT.context", "Menu di scelta rapida" },
            { "AWT.control", "Ctrl" },
            { "AWT.convert", "Converti" },
            { "AWT.copy", "Copia" },
            { "AWT.cut", "Taglia" },
            { "AWT.deadAboveDot", "Punto superiore non attivo" },
            { "AWT.deadAboveRing", "Cerchio superiore non attivo" },
            { "AWT.deadAcute", "Acuto non attivo" },
            { "AWT.deadBreve", "Breve non attivo" },
            { "AWT.deadCaron", "Caron non attivo" },
            { "AWT.deadCedilla", "Cediglia non attivo" },
            { "AWT.deadCircumflex", "Circonflesso non attivo" },
            { "AWT.deadDiaeresis", "Dieresi non attivo" },
            { "AWT.deadDoubleAcute", "Acuto doppio non attivo" },
            { "AWT.deadGrave", "Grave non attivo" },
            { "AWT.deadIota", "Iota non attivo" },
            { "AWT.deadMacron", "Macron non attivo" },
            { "AWT.deadOgonek", "Ogonek non attivo" },
            { "AWT.deadSemivoicedSound", "Suono semivocalizzato non attivo" },
            { "AWT.deadTilde", "Tilde non attivo" },
            { "AWT.deadVoicedSound", "Suono vocalizzato non attivo" },
            { "AWT.decimal", "NumPad ." },
            { "AWT.delete", "Elimina" },
            { "AWT.divide", "NumPad /" },
            { "AWT.dollar", "Dollaro" },
            { "AWT.down", "Gi\u00F9" },
            { "AWT.end", "Fine" },
            { "AWT.enter", "Invio" },
            { "AWT.equals", "Uguale" },
            { "AWT.escape", "Esc" },
            { "AWT.euro", "Euro" },
            { "AWT.exclamationMark", "Punto esclamativo" },
            { "AWT.f1", "F1" },
            { "AWT.f10", "F10" },
            { "AWT.f11", "F11" },
            { "AWT.f12", "F12" },
            { "AWT.f13", "F13" },
            { "AWT.f14", "F14" },
            { "AWT.f15", "F15" },
            { "AWT.f16", "F16" },
            { "AWT.f17", "F17" },
            { "AWT.f18", "F18" },
            { "AWT.f19", "F19" },
            { "AWT.f2", "F2" },
            { "AWT.f20", "F20" },
            { "AWT.f21", "F21" },
            { "AWT.f22", "F22" },
            { "AWT.f23", "F23" },
            { "AWT.f24", "F24" },
            { "AWT.f3", "F3" },
            { "AWT.f4", "F4" },
            { "AWT.f5", "F5" },
            { "AWT.f6", "F6" },
            { "AWT.f7", "F7" },
            { "AWT.f8", "F8" },
            { "AWT.f9", "F9" },
            { "AWT.final", "Finale" },
            { "AWT.find", "Trova" },
            { "AWT.fullWidth", "Spessore pieno" },
            { "AWT.greater", "Maggiore" },
            { "AWT.halfWidth", "Spessore ridotto" },
            { "AWT.help", "?" },
            { "AWT.hiragana", "Hiragana" },
            { "AWT.home", "Home" },
            { "AWT.inputMethodOnOff", "Metodo immissione On/Off" },
            { "AWT.insert", "Ins" },
            { "AWT.invertedExclamationMark", "Punto esclamativo invertito" },
            { "AWT.japaneseHiragana", "Hiragana giapponese" },
            { "AWT.japaneseKatakana", "Katakana giapponese" },
            { "AWT.japaneseRoman", "Romano Giapponese" },
            { "AWT.kana", "Kana" },
            { "AWT.kanaLock", "Blocco Kana" },
            { "AWT.kanji", "Kanji" },
            { "AWT.katakana", "Katakana" },
            { "AWT.left", "Sinistra" },
            { "AWT.leftParenthesis", "Parentesi aperta" },
            { "AWT.meta", "Meta" },
            { "AWT.minus", "Meno" },
            { "AWT.modechange", "Modifica modalit\u00E0" },
            { "AWT.multiply", "NumPad *" },
            { "AWT.noconvert", "Non convertire" },
            { "AWT.numLock", "Bloc Num" },
            { "AWT.numberSign", "Cancelletto" },
            { "AWT.numpad", "NumPad" },
            { "AWT.openBracket", "Parentesi quadra aperta" },
            { "AWT.paste", "Incolla" },
            { "AWT.pause", "Sospendi" },
            { "AWT.period", "Punto" },
            { "AWT.pgdn", "Pg Gi\u00F9" },
            { "AWT.pgup", "Pg Su" },
            { "AWT.plus", "Pi\u00F9" },
            { "AWT.previousCandidate", "Candidato precedente" },
            { "AWT.printScreen", "Stamp" },
            { "AWT.props", "Propriet\u00E0" },
            { "AWT.quote", "Apice" },
            { "AWT.quoteDbl", "Virgolette" },
            { "AWT.right", "Destra" },
            { "AWT.rightParenthesis", "Parentesi chiusa" },
            { "AWT.romanCharacters", "Caratteri romani" },
            { "AWT.scrollLock", "Bloc Scorr" },
            { "AWT.semicolon", "Punto e virgola" },
            { "AWT.separater", "NumPad ," },
            { "AWT.separator", "NumPad ," },
            { "AWT.shift", "Maiusc" },
            { "AWT.slash", "Barra" },
            { "AWT.space", "Barra spaziatrice" },
            { "AWT.stop", "Arresta" },
            { "AWT.subtract", "NumPad -" },
            { "AWT.tab", "Tabulazione" },
            { "AWT.undefined", "Non definito" },
            { "AWT.underscore", "Sottolineatura" },
            { "AWT.undo", "Annulla" },
            { "AWT.unknown", "Sconosciuto" },
            { "AWT.up", "Su" },
            { "AWT.windows", "Windows" },
            { "java.awt.def.delay", "30" },
            { "java.awt.im.style", "immediato" },
        };
    }
}
