package sun.awt.resources;

import java.util.ListResourceBundle;

public final class awt_de extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "AWT.CompositionWindowTitle", "Eingabefenster" },
            { "AWT.CrosshairCursor", "Fadenkreuzcursor" },
            { "AWT.DefaultCursor", "Standardcursor" },
            { "AWT.DefaultDragCursor", "Standardcursor beim Ziehen" },
            { "AWT.DefaultDropCursor", "Standardcursor beim Ablegen" },
            { "AWT.DefaultNoDropCursor", "Standardcursor NoDrag" },
            { "AWT.EResizeCursor", "Skaliercursor nach rechts" },
            { "AWT.HandCursor", "Handcursor" },
            { "AWT.HostInputMethodDisplayName", "Systemeingabemethoden" },
            { "AWT.InconsistentDLLsWarning", "Textbasierte Vorg\u00E4nge funktionieren m\u00F6glicherweise nicht richtig, weil inkonsistente Dynamic Linking Librarys (DLLs) auf dem System installiert sind. Weitere Informationen zu diesem Problem sowie eine Empfehlung zu der Umgehung finden Sie in den Java(TM) 2 SDK, Standard Edition Release Notes unter java.sun.com." },
            { "AWT.InputMethodCreationFailed", "{0} konnte nicht erstellt werden.  Grund: {1}" },
            { "AWT.InputMethodLanguage.ja", "Japanisch" },
            { "AWT.InputMethodLanguage.ko", "Koreanisch" },
            { "AWT.InputMethodLanguage.zh", "Chinesisch" },
            { "AWT.InputMethodLanguage.zh_CN", "Vereinfachtes Chinesisch" },
            { "AWT.InputMethodLanguage.zh_TW", "Traditionelles Chinesisch" },
            { "AWT.InputMethodSelectionMenu", "Eingabemethode ausw\u00E4hlen" },
            { "AWT.Less", "Kleiner als" },
            { "AWT.MoveCursor", "Verschiebecursor" },
            { "AWT.NEResizeCursor", "Skaliercursor nach oben/rechts" },
            { "AWT.NResizeCursor", "Skaliercursor nach oben" },
            { "AWT.NWResizeCursor", "Skaliercursor nach oben/links" },
            { "AWT.SEResizeCursor", "Skaliercursor nach unten/rechts" },
            { "AWT.SResizeCursor", "Skaliercursor nach unten" },
            { "AWT.SWResizeCursor", "Skaliercursor nach unten/links" },
            { "AWT.TextCursor", "Textcursor" },
            { "AWT.WResizeCursor", "Skaliercursor nach links" },
            { "AWT.WaitCursor", "Wartecursor" },
            { "AWT.accept", "Akzeptieren" },
            { "AWT.add", "NumPad +" },
            { "AWT.again", "Wiederholen" },
            { "AWT.allCandidates", "Alle Kandidaten" },
            { "AWT.alphanumeric", "Alphanumerisch" },
            { "AWT.alt", "Alt" },
            { "AWT.altGraph", "Alt Gr" },
            { "AWT.ampersand", "Et-Zeichen" },
            { "AWT.asterisk", "Sternchen" },
            { "AWT.at", "Klammeraffe" },
            { "AWT.backQuote", "Schlie\u00DFendes Anf\u00FChrungszeichen" },
            { "AWT.backSlash", "Umgekehrter Schr\u00E4gstrich" },
            { "AWT.backSpace", "R\u00FCcktaste" },
            { "AWT.begin", "Anfang" },
            { "AWT.braceLeft", "Linke geschweifte Klammer" },
            { "AWT.braceRight", "Rechte geschweifte Klammer" },
            { "AWT.cancel", "Abbrechen" },
            { "AWT.capsLock", "Feststelltaste" },
            { "AWT.circumflex", "Zirkumflex" },
            { "AWT.clear", "L\u00F6schen" },
            { "AWT.closeBracket", "Schlie\u00DFende Klammer" },
            { "AWT.codeInput", "Codeeingabe" },
            { "AWT.colon", "Doppelpunkt" },
            { "AWT.comma", "Komma" },
            { "AWT.compose", "Verfassen" },
            { "AWT.context", "Kontextmen\u00FC" },
            { "AWT.control", "Strg" },
            { "AWT.convert", "Konvertieren" },
            { "AWT.copy", "Kopieren" },
            { "AWT.cut", "Ausschneiden" },
            { "AWT.deadAboveDot", "Oberer Punkt (Dead)" },
            { "AWT.deadAboveRing", "Oberer Ring (Dead)" },
            { "AWT.deadAcute", "Akut (Dead)" },
            { "AWT.deadBreve", "Breve (Dead)" },
            { "AWT.deadCaron", "Caron (Dead)" },
            { "AWT.deadCedilla", "Cedille (Dead)" },
            { "AWT.deadCircumflex", "Zirkumflex (Dead)" },
            { "AWT.deadDiaeresis", "Trema (Dead)" },
            { "AWT.deadDoubleAcute", "Doppelakut (Dead)" },
            { "AWT.deadGrave", "Gravis (Dead)" },
            { "AWT.deadIota", "Iota (Dead)" },
            { "AWT.deadMacron", "Macron (Dead)" },
            { "AWT.deadOgonek", "Ogonek (Dead)" },
            { "AWT.deadSemivoicedSound", "Halbstimmhaft (Dead)" },
            { "AWT.deadTilde", "Tilde (Dead)" },
            { "AWT.deadVoicedSound", "Stimmhaft (Dead)" },
            { "AWT.decimal", "NumPad ." },
            { "AWT.delete", "Entf" },
            { "AWT.divide", "NumPad /" },
            { "AWT.dollar", "Dollarzeichen" },
            { "AWT.down", "Unten" },
            { "AWT.end", "Ende" },
            { "AWT.enter", "Eingabe" },
            { "AWT.equals", "Entspricht" },
            { "AWT.escape", "ESC" },
            { "AWT.euro", "Euro" },
            { "AWT.exclamationMark", "Ausrufezeichen" },
            { "AWT.f1", "F1" },
            { "AWT.f10", "F10" },
            { "AWT.f11", "F11" },
            { "AWT.f12", "F12" },
            { "AWT.f13", "F13" },
            { "AWT.f14", "F14" },
            { "AWT.f15", "F15" },
            { "AWT.f16", "F16" },
            { "AWT.f17", "F17" },
            { "AWT.f18", "F18" },
            { "AWT.f19", "F19" },
            { "AWT.f2", "F2" },
            { "AWT.f20", "F20" },
            { "AWT.f21", "F21" },
            { "AWT.f22", "F22" },
            { "AWT.f23", "F23" },
            { "AWT.f24", "F24" },
            { "AWT.f3", "F3" },
            { "AWT.f4", "F4" },
            { "AWT.f5", "F5" },
            { "AWT.f6", "F6" },
            { "AWT.f7", "F7" },
            { "AWT.f8", "F8" },
            { "AWT.f9", "F9" },
            { "AWT.final", "Abschluss" },
            { "AWT.find", "Suchen" },
            { "AWT.fullWidth", "Volle Breite" },
            { "AWT.greater", "Gr\u00F6\u00DFer als" },
            { "AWT.halfWidth", "Halbe Breite" },
            { "AWT.help", "Hilfe" },
            { "AWT.hiragana", "Hiragana" },
            { "AWT.home", "Pos 1" },
            { "AWT.inputMethodOnOff", "Eingabemethode ein/aus" },
            { "AWT.insert", "Einfg" },
            { "AWT.invertedExclamationMark", "Umgekehrtes Ausrufezeichen" },
            { "AWT.japaneseHiragana", "Japanisch (Hiragana)" },
            { "AWT.japaneseKatakana", "Japanisch (Katakana)" },
            { "AWT.japaneseRoman", "Japanisch (Latein)" },
            { "AWT.kana", "Kana" },
            { "AWT.kanaLock", "Kana Lock" },
            { "AWT.kanji", "Kanji" },
            { "AWT.katakana", "Katakana" },
            { "AWT.left", "Links" },
            { "AWT.leftParenthesis", "Linke Klammer" },
            { "AWT.meta", "Meta" },
            { "AWT.minus", "Minus" },
            { "AWT.modechange", "Modus\u00E4nderung" },
            { "AWT.multiply", "NumPad *" },
            { "AWT.noconvert", "Nicht konvertieren" },
            { "AWT.numLock", "Num" },
            { "AWT.numberSign", "Nummernzeichen" },
            { "AWT.numpad", "NumPad" },
            { "AWT.openBracket", "\u00D6ffnende Klammer" },
            { "AWT.paste", "Einf\u00FCgen" },
            { "AWT.pause", "Pause" },
            { "AWT.period", "Punkt" },
            { "AWT.pgdn", "Bild ab" },
            { "AWT.pgup", "Bild auf" },
            { "AWT.plus", "Plus" },
            { "AWT.previousCandidate", "Vorheriger Kandidat" },
            { "AWT.printScreen", "Druck" },
            { "AWT.props", "Eigenschaften" },
            { "AWT.quote", "Anf\u00FChrungszeichen" },
            { "AWT.quoteDbl", "Doppelte Anf\u00FChrungszeichen" },
            { "AWT.right", "Rechts" },
            { "AWT.rightParenthesis", "Rechte Klammer" },
            { "AWT.romanCharacters", "Lateinische Zeichen" },
            { "AWT.scrollLock", "Rollen" },
            { "AWT.semicolon", "Semikolon" },
            { "AWT.separater", "NumPad ," },
            { "AWT.separator", "NumPad ," },
            { "AWT.shift", "Umschalt" },
            { "AWT.slash", "Schr\u00E4gstrich" },
            { "AWT.space", "Leertaste" },
            { "AWT.stop", "Stopp" },
            { "AWT.subtract", "NumPad -" },
            { "AWT.tab", "Tabulator" },
            { "AWT.undefined", "Undefiniert" },
            { "AWT.underscore", "Unterstrich" },
            { "AWT.undo", "R\u00FCckg\u00E4ngig" },
            { "AWT.unknown", "Unbekannt" },
            { "AWT.up", "Oben" },
            { "AWT.windows", "Windows" },
            { "java.awt.def.delay", "30" },
            { "java.awt.im.style", "On-the-Spot" },
        };
    }
}
