package sun.awt.resources;

import java.util.ListResourceBundle;

public final class awt_es extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "AWT.CompositionWindowTitle", "Ventana de Entrada" },
            { "AWT.CrosshairCursor", "Cursor de Punto de Mira" },
            { "AWT.DefaultCursor", "Cursor Por defecto" },
            { "AWT.DefaultDragCursor", "Cursor de Arrastrar Por defecto" },
            { "AWT.DefaultDropCursor", "Cursor de Soltar Por Defecto" },
            { "AWT.DefaultNoDropCursor", "Cursor de No Arrastrar Por Defecto" },
            { "AWT.EResizeCursor", "Cursor de Cambio de Tama\u00F1o este" },
            { "AWT.HandCursor", "Cursor de Mano" },
            { "AWT.HostInputMethodDisplayName", "M\u00E9todos de Entrada del Sistema" },
            { "AWT.InconsistentDLLsWarning", "Puede que las operaciones textuales no funcionen correctamente debido a un juego incoherente de bibliotecas de enlaces din\u00E1micos (DLL) instaladas en su sistema. Para obtener m\u00E1s informaci\u00F3n acerca de este problema y de la soluci\u00F3n alternativa sugerida, consulte Java(TM) 2 SDK, Standard Edition Release Notes en java.sun.com." },
            { "AWT.InputMethodCreationFailed", "No se ha podido crear {0}. Motivo: {1}" },
            { "AWT.InputMethodLanguage.ja", "Japon\u00E9s" },
            { "AWT.InputMethodLanguage.ko", "Coreano" },
            { "AWT.InputMethodLanguage.zh", "chino" },
            { "AWT.InputMethodLanguage.zh_CN", "Chino Simplificado" },
            { "AWT.InputMethodLanguage.zh_TW", "Chino Tradicional" },
            { "AWT.InputMethodSelectionMenu", "Seleccionar M\u00E9todo de Entrada" },
            { "AWT.Less", "Menor que" },
            { "AWT.MoveCursor", "Cursor de Movimiento" },
            { "AWT.NEResizeCursor", "Cursor de Cambio de Tama\u00F1o Nordeste" },
            { "AWT.NResizeCursor", "Cursor de Cambio de Tama\u00F1o Norte" },
            { "AWT.NWResizeCursor", "Cursor de Cambio de Tama\u00F1o Noroeste" },
            { "AWT.SEResizeCursor", "Cursor de Cambio de Tama\u00F1o Sudeste" },
            { "AWT.SResizeCursor", "Cursor de Cambio de Tama\u00F1o Sur" },
            { "AWT.SWResizeCursor", "Cursor de Cambio de Tama\u00F1o Suroeste" },
            { "AWT.TextCursor", "Cursor de Texto" },
            { "AWT.WResizeCursor", "Cursor de Cambio de Tama\u00F1o Oeste" },
            { "AWT.WaitCursor", "Cursor de Espera" },
            { "AWT.accept", "Aceptar" },
            { "AWT.add", "+ de Teclado Num\u00E9rico" },
            { "AWT.again", "Repetir" },
            { "AWT.allCandidates", "Todos los Candidatos" },
            { "AWT.alphanumeric", "Alfanum\u00E9rico" },
            { "AWT.alt", "Alt" },
            { "AWT.altGraph", "Alt Gr" },
            { "AWT.ampersand", "Ampersand" },
            { "AWT.asterisk", "Asterisco" },
            { "AWT.at", "Arroba" },
            { "AWT.backQuote", "Comilla Invertida" },
            { "AWT.backSlash", "Barra Invertida" },
            { "AWT.backSpace", "Retroceso" },
            { "AWT.begin", "Inicio" },
            { "AWT.braceLeft", "Llave de Apertura" },
            { "AWT.braceRight", "Llave de Cierre" },
            { "AWT.cancel", "Cancelar" },
            { "AWT.capsLock", "Bloqueo de May\u00FAsculas" },
            { "AWT.circumflex", "Circunflejo" },
            { "AWT.clear", "Borrar" },
            { "AWT.closeBracket", "Par\u00E9ntesis de Cierre" },
            { "AWT.codeInput", "Entrada de C\u00F3digo" },
            { "AWT.colon", "Dos puntos" },
            { "AWT.comma", "Coma" },
            { "AWT.compose", "Componer" },
            { "AWT.context", "Men\u00FA Contextual" },
            { "AWT.control", "Ctrl" },
            { "AWT.convert", "Convertir" },
            { "AWT.copy", "Copiar" },
            { "AWT.cut", "Cortar" },
            { "AWT.deadAboveDot", "Punto Superior (Tecla Muerta)" },
            { "AWT.deadAboveRing", "C\u00EDrculo Superior (Tecla Muerta)" },
            { "AWT.deadAcute", "Acento Agudo Muerto" },
            { "AWT.deadBreve", "Acento Breve (Tecla Muerta)" },
            { "AWT.deadCaron", "Acento Articircunflejo (Tecla Muerta)" },
            { "AWT.deadCedilla", "Cedilla (Tecla Muerta)" },
            { "AWT.deadCircumflex", "Circunflejo (Tecla Muerta)" },
            { "AWT.deadDiaeresis", "Di\u00E9resis (Tecla Muerta)" },
            { "AWT.deadDoubleAcute", "Acento Agudo Doble (Tecla Muerta)" },
            { "AWT.deadGrave", "Acento Grave (Tecla Muerta)" },
            { "AWT.deadIota", "Iota (Tecla Muerta)" },
            { "AWT.deadMacron", "Macr\u00F3n (Tecla Muerta)" },
            { "AWT.deadOgonek", "Esp\u00EDritu \u00C1spero (Tecla Muerta)" },
            { "AWT.deadSemivoicedSound", "Sonido Semisonoro (Tecla Muerta)" },
            { "AWT.deadTilde", "Tilde (Tecla Muerta)" },
            { "AWT.deadVoicedSound", "Sonido Sonoro (Tecla Muerta)" },
            { "AWT.decimal", ". de Teclado Num\u00E9rico" },
            { "AWT.delete", "Suprimir" },
            { "AWT.divide", "/ de Teclado Num\u00E9rico" },
            { "AWT.dollar", "D\u00F3lar" },
            { "AWT.down", "Abajo" },
            { "AWT.end", "Fin" },
            { "AWT.enter", "Intro" },
            { "AWT.equals", "Igual" },
            { "AWT.escape", "Escape" },
            { "AWT.euro", "Euro" },
            { "AWT.exclamationMark", "Signo de Exclamaci\u00F3n de Cierre" },
            { "AWT.f1", "F1" },
            { "AWT.f10", "F10" },
            { "AWT.f11", "F11" },
            { "AWT.f12", "F12" },
            { "AWT.f13", "F13" },
            { "AWT.f14", "F14" },
            { "AWT.f15", "F15" },
            { "AWT.f16", "F16" },
            { "AWT.f17", "F17" },
            { "AWT.f18", "F18" },
            { "AWT.f19", "F19" },
            { "AWT.f2", "F2" },
            { "AWT.f20", "F20" },
            { "AWT.f21", "F21" },
            { "AWT.f22", "F22" },
            { "AWT.f23", "F23" },
            { "AWT.f24", "F24" },
            { "AWT.f3", "F3" },
            { "AWT.f4", "F4" },
            { "AWT.f5", "F5" },
            { "AWT.f6", "F6" },
            { "AWT.f7", "F7" },
            { "AWT.f8", "F8" },
            { "AWT.f9", "F9" },
            { "AWT.final", "Final" },
            { "AWT.find", "Buscar" },
            { "AWT.fullWidth", "Anchura Completa" },
            { "AWT.greater", "Mayor que" },
            { "AWT.halfWidth", "Media Anchura" },
            { "AWT.help", "Ayuda" },
            { "AWT.hiragana", "Hiragana" },
            { "AWT.home", "Inicio" },
            { "AWT.inputMethodOnOff", "Activar/Desactivar M\u00E9todo de Entrada" },
            { "AWT.insert", "Insertar" },
            { "AWT.invertedExclamationMark", "Signo de Exclamaci\u00F3n de Apertura" },
            { "AWT.japaneseHiragana", "Caracteres Hiragana Japoneses" },
            { "AWT.japaneseKatakana", "Caracteres Katakana Japoneses" },
            { "AWT.japaneseRoman", "Caracteres Romanos Japoneses" },
            { "AWT.kana", "Kana" },
            { "AWT.kanaLock", "Bloqueo Kana" },
            { "AWT.kanji", "Kanji" },
            { "AWT.katakana", "Katakana" },
            { "AWT.left", "Izquierda" },
            { "AWT.leftParenthesis", "Par\u00E9ntesis Izquierdo" },
            { "AWT.meta", "Meta" },
            { "AWT.minus", "Menos" },
            { "AWT.modechange", "Cambio de Modo" },
            { "AWT.multiply", "* de Teclado Num\u00E9rico" },
            { "AWT.noconvert", "No Convertir" },
            { "AWT.numLock", "Bloqueo Num\u00E9rico" },
            { "AWT.numberSign", "Signo de N\u00FAmero" },
            { "AWT.numpad", "Teclado Num\u00E9rico" },
            { "AWT.openBracket", "Par\u00E9ntesis de Apertura" },
            { "AWT.paste", "Pegar" },
            { "AWT.pause", "Pausa" },
            { "AWT.period", "Punto" },
            { "AWT.pgdn", "AvP\u00E1g" },
            { "AWT.pgup", "ReP\u00E1g" },
            { "AWT.plus", "M\u00E1s" },
            { "AWT.previousCandidate", "Candidato Anterior" },
            { "AWT.printScreen", "Imprimir Pantalla" },
            { "AWT.props", "Propiedades" },
            { "AWT.quote", "Comilla" },
            { "AWT.quoteDbl", "Dobles Comillas" },
            { "AWT.right", "Derecha" },
            { "AWT.rightParenthesis", "Par\u00E9ntesis Derecho" },
            { "AWT.romanCharacters", "Caracteres Romanos" },
            { "AWT.scrollLock", "Bloqueo de Desplazamiento" },
            { "AWT.semicolon", "Punto y coma" },
            { "AWT.separater", ", de Teclado Num\u00E9rico" },
            { "AWT.separator", ", de Teclado Num\u00E9rico" },
            { "AWT.shift", "May\u00FAs" },
            { "AWT.slash", "Barra" },
            { "AWT.space", "Espacio" },
            { "AWT.stop", "Parar" },
            { "AWT.subtract", "- de Teclado Num\u00E9rico" },
            { "AWT.tab", "Tabulador" },
            { "AWT.undefined", "No Definido" },
            { "AWT.underscore", "Subrayado" },
            { "AWT.undo", "Deshacer" },
            { "AWT.unknown", "Desconocido" },
            { "AWT.up", "Arriba" },
            { "AWT.windows", "Windows" },
            { "java.awt.def.delay", "30" },
            { "java.awt.im.style", "en el lugar" },
        };
    }
}
