// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !

package sun.awt.X11;

import jdk.internal.misc.Unsafe;

import sun.util.logging.PlatformLogger;
public class ColorEntry extends XWrapperBase { 
	private Unsafe unsafe = XlibWrapper.unsafe; 
	private final boolean should_free_memory;
	public static int getSize() { return 4; }
	public int getDataSize() { return getSize(); }

	long pData;

	public long getPData() { return pData; }


	public ColorEntry(long addr) {
		log.finest("Creating");
		pData=addr;
		should_free_memory = false;
	}


	public ColorEntry() {
		log.finest("Creating");
		pData = unsafe.allocateMemory(getSize());
		should_free_memory = true;
	}


	public void dispose() {
		log.finest("Disposing");
		if (should_free_memory) {
			log.finest("freeing memory");
			unsafe.freeMemory(pData); 
	}
		}
	public byte get_r() { log.finest("");return (Native.getByte(pData+0)); }
	public void set_r(byte v) { log.finest(""); Native.putByte(pData+0, v); }
	public byte get_g() { log.finest("");return (Native.getByte(pData+1)); }
	public void set_g(byte v) { log.finest(""); Native.putByte(pData+1, v); }
	public byte get_b() { log.finest("");return (Native.getByte(pData+2)); }
	public void set_b(byte v) { log.finest(""); Native.putByte(pData+2, v); }
	public byte get_flags() { log.finest("");return (Native.getByte(pData+3)); }
	public void set_flags(byte v) { log.finest(""); Native.putByte(pData+3, v); }


	String getName() {
		return "ColorEntry"; 
	}


	String getFieldsAsString() {
		StringBuilder ret = new StringBuilder(160);

		ret.append("r = ").append( get_r() ).append(", ");
		ret.append("g = ").append( get_g() ).append(", ");
		ret.append("b = ").append( get_b() ).append(", ");
		ret.append("flags = ").append( get_flags() ).append(", ");
		return ret.toString();
	}


}



