// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !

package sun.awt.X11;

import jdk.internal.misc.Unsafe;

import sun.util.logging.PlatformLogger;
public class Depth extends XWrapperBase { 
	private Unsafe unsafe = XlibWrapper.unsafe; 
	private final boolean should_free_memory;
	public static int getSize() { return 16; }
	public int getDataSize() { return getSize(); }

	long pData;

	public long getPData() { return pData; }


	public Depth(long addr) {
		log.finest("Creating");
		pData=addr;
		should_free_memory = false;
	}


	public Depth() {
		log.finest("Creating");
		pData = unsafe.allocateMemory(getSize());
		should_free_memory = true;
	}


	public void dispose() {
		log.finest("Disposing");
		if (should_free_memory) {
			log.finest("freeing memory");
			unsafe.freeMemory(pData); 
	}
		}
	public int get_depth() { log.finest("");return (Native.getInt(pData+0)); }
	public void set_depth(int v) { log.finest(""); Native.putInt(pData+0, v); }
	public int get_nvisuals() { log.finest("");return (Native.getInt(pData+4)); }
	public void set_nvisuals(int v) { log.finest(""); Native.putInt(pData+4, v); }
	public Visual get_visuals(int index) { log.finest(""); return (Native.getLong(pData+8) != 0)?(new Visual(Native.getLong(pData+8)+index*56)):(null); }
	public long get_visuals() { log.finest("");return Native.getLong(pData+8); }
	public void set_visuals(long v) { log.finest(""); Native.putLong(pData + 8, v); }


	String getName() {
		return "Depth"; 
	}


	String getFieldsAsString() {
		StringBuilder ret = new StringBuilder(120);

		ret.append("depth = ").append( get_depth() ).append(", ");
		ret.append("nvisuals = ").append( get_nvisuals() ).append(", ");
		ret.append("visuals = ").append( get_visuals() ).append(", ");
		return ret.toString();
	}


}



