// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !

package sun.awt.X11;

import jdk.internal.misc.Unsafe;

import sun.util.logging.PlatformLogger;
public class XkbMapNotifyEvent extends XWrapperBase { 
	private Unsafe unsafe = XlibWrapper.unsafe; 
	private final boolean should_free_memory;
	public static int getSize() { return 104; }
	public int getDataSize() { return getSize(); }

	long pData;

	public long getPData() { return pData; }


	public XkbMapNotifyEvent(long addr) {
		log.finest("Creating");
		pData=addr;
		should_free_memory = false;
	}


	public XkbMapNotifyEvent() {
		log.finest("Creating");
		pData = unsafe.allocateMemory(getSize());
		should_free_memory = true;
	}


	public void dispose() {
		log.finest("Disposing");
		if (should_free_memory) {
			log.finest("freeing memory");
			unsafe.freeMemory(pData); 
	}
		}
	public int get_type() { log.finest("");return (Native.getInt(pData+0)); }
	public void set_type(int v) { log.finest(""); Native.putInt(pData+0, v); }
	public long get_serial() { log.finest("");return (Native.getULong(pData+8)); }
	public void set_serial(long v) { log.finest(""); Native.putULong(pData+8, v); }
	public boolean get_send_event() { log.finest("");return (Native.getBool(pData+16)); }
	public void set_send_event(boolean v) { log.finest(""); Native.putBool(pData+16, v); }
	public long get_display() { log.finest("");return (Native.getLong(pData+24)); }
	public void set_display(long v) { log.finest(""); Native.putLong(pData+24, v); }
	public long get_time() { log.finest("");return (Native.getULong(pData+32)); }
	public void set_time(long v) { log.finest(""); Native.putULong(pData+32, v); }
	public int get_xkb_type() { log.finest("");return (Native.getInt(pData+40)); }
	public void set_xkb_type(int v) { log.finest(""); Native.putInt(pData+40, v); }
	public int get_device() { log.finest("");return (Native.getInt(pData+44)); }
	public void set_device(int v) { log.finest(""); Native.putInt(pData+44, v); }
	public int get_changed() { log.finest("");return (Native.getInt(pData+48)); }
	public void set_changed(int v) { log.finest(""); Native.putInt(pData+48, v); }
	public int get_flags() { log.finest("");return (Native.getInt(pData+52)); }
	public void set_flags(int v) { log.finest(""); Native.putInt(pData+52, v); }
	public int get_first_type() { log.finest("");return (Native.getInt(pData+56)); }
	public void set_first_type(int v) { log.finest(""); Native.putInt(pData+56, v); }
	public int get_num_types() { log.finest("");return (Native.getInt(pData+60)); }
	public void set_num_types(int v) { log.finest(""); Native.putInt(pData+60, v); }
	public int get_min_key_code() { log.finest("");return (Native.getInt(pData+64)); }
	public void set_min_key_code(int v) { log.finest(""); Native.putInt(pData+64, v); }
	public int get_max_key_code() { log.finest("");return (Native.getInt(pData+65)); }
	public void set_max_key_code(int v) { log.finest(""); Native.putInt(pData+65, v); }
	public int get_first_key_sym() { log.finest("");return (Native.getInt(pData+66)); }
	public void set_first_key_sym(int v) { log.finest(""); Native.putInt(pData+66, v); }
	public int get_first_key_act() { log.finest("");return (Native.getInt(pData+67)); }
	public void set_first_key_act(int v) { log.finest(""); Native.putInt(pData+67, v); }
	public int get_first_key_behavior() { log.finest("");return (Native.getInt(pData+68)); }
	public void set_first_key_behavior(int v) { log.finest(""); Native.putInt(pData+68, v); }
	public int get_first_key_explicit() { log.finest("");return (Native.getInt(pData+69)); }
	public void set_first_key_explicit(int v) { log.finest(""); Native.putInt(pData+69, v); }
	public int get_first_modmap_key() { log.finest("");return (Native.getInt(pData+70)); }
	public void set_first_modmap_key(int v) { log.finest(""); Native.putInt(pData+70, v); }
	public int get_first_vmodmap_key() { log.finest("");return (Native.getInt(pData+71)); }
	public void set_first_vmodmap_key(int v) { log.finest(""); Native.putInt(pData+71, v); }
	public int get_num_key_syms() { log.finest("");return (Native.getInt(pData+72)); }
	public void set_num_key_syms(int v) { log.finest(""); Native.putInt(pData+72, v); }
	public int get_num_key_acts() { log.finest("");return (Native.getInt(pData+76)); }
	public void set_num_key_acts(int v) { log.finest(""); Native.putInt(pData+76, v); }
	public int get_num_key_behaviors() { log.finest("");return (Native.getInt(pData+80)); }
	public void set_num_key_behaviors(int v) { log.finest(""); Native.putInt(pData+80, v); }
	public int get_num_key_explicit() { log.finest("");return (Native.getInt(pData+84)); }
	public void set_num_key_explicit(int v) { log.finest(""); Native.putInt(pData+84, v); }
	public int get_num_modmap_keys() { log.finest("");return (Native.getInt(pData+88)); }
	public void set_num_modmap_keys(int v) { log.finest(""); Native.putInt(pData+88, v); }
	public int get_num_vmodmap_keys() { log.finest("");return (Native.getInt(pData+92)); }
	public void set_num_vmodmap_keys(int v) { log.finest(""); Native.putInt(pData+92, v); }
	public int get_vmods() { log.finest("");return (Native.getInt(pData+96)); }
	public void set_vmods(int v) { log.finest(""); Native.putInt(pData+96, v); }


	String getName() {
		return "XkbMapNotifyEvent"; 
	}


	String getFieldsAsString() {
		StringBuilder ret = new StringBuilder(1040);

		ret.append("type = ").append( XlibWrapper.eventToString[get_type()] ).append(", ");
		ret.append("serial = ").append( get_serial() ).append(", ");
		ret.append("send_event = ").append( get_send_event() ).append(", ");
		ret.append("display = ").append( get_display() ).append(", ");
		ret.append("time = ").append( get_time() ).append(", ");
		ret.append("xkb_type = ").append( get_xkb_type() ).append(", ");
		ret.append("device = ").append( get_device() ).append(", ");
		ret.append("changed = ").append( get_changed() ).append(", ");
		ret.append("flags = ").append( get_flags() ).append(", ");
		ret.append("first_type = ").append( get_first_type() ).append(", ");
		ret.append("num_types = ").append( get_num_types() ).append(", ");
		ret.append("min_key_code = ").append( get_min_key_code() ).append(", ");
		ret.append("max_key_code = ").append( get_max_key_code() ).append(", ");
		ret.append("first_key_sym = ").append( get_first_key_sym() ).append(", ");
		ret.append("first_key_act = ").append( get_first_key_act() ).append(", ");
		ret.append("first_key_behavior = ").append( get_first_key_behavior() ).append(", ");
		ret.append("first_key_explicit = ").append( get_first_key_explicit() ).append(", ");
		ret.append("first_modmap_key = ").append( get_first_modmap_key() ).append(", ");
		ret.append("first_vmodmap_key = ").append( get_first_vmodmap_key() ).append(", ");
		ret.append("num_key_syms = ").append( get_num_key_syms() ).append(", ");
		ret.append("num_key_acts = ").append( get_num_key_acts() ).append(", ");
		ret.append("num_key_behaviors = ").append( get_num_key_behaviors() ).append(", ");
		ret.append("num_key_explicit = ").append( get_num_key_explicit() ).append(", ");
		ret.append("num_modmap_keys = ").append( get_num_modmap_keys() ).append(", ");
		ret.append("num_vmodmap_keys = ").append( get_num_vmodmap_keys() ).append(", ");
		ret.append("vmods = ").append( get_vmods() ).append(", ");
		return ret.toString();
	}


}



