package com.sun.swing.internal.plaf.basic.resources;

import java.util.ListResourceBundle;

public final class basic_fr extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "AbstractButton.click.textAndMnemonic", "cliquer" },
            { "AbstractDocument.addition.textAndMnemonic", "ajout" },
            { "AbstractDocument.deletion.textAndMnemonic", "suppression" },
            { "AbstractDocument.redo.textAndMnemonic", "R\u00E9tablir" },
            { "AbstractDocument.styleChange.textAndMnemonic", "modification de style" },
            { "AbstractDocument.undo.textAndMnemonic", "Annuler" },
            { "AbstractUndoableEdit.redo.textAndMnemonic", "R\u00E9tablir" },
            { "AbstractUndoableEdit.undo.textAndMnemonic", "Annuler" },
            { "ColorChooser.cancel.textAndMnemonic", "Annuler" },
            { "ColorChooser.cmyk.textAndMnemonic", "C&MYK" },
            { "ColorChooser.cmykAlpha.textAndMnemonic", "Alpha" },
            { "ColorChooser.cmykBlack.textAndMnemonic", "Noir" },
            { "ColorChooser.cmykCyan.textAndMnemonic", "Cyan" },
            { "ColorChooser.cmykMagenta.textAndMnemonic", "Magenta" },
            { "ColorChooser.cmykYellow.textAndMnemonic", "Jaune" },
            { "ColorChooser.hsl.textAndMnemonic", "TS&L" },
            { "ColorChooser.hslHue.textAndMnemonic", "Teinte" },
            { "ColorChooser.hslLightness.textAndMnemonic", "Lumi\u00E8re" },
            { "ColorChooser.hslSaturation.textAndMnemonic", "Saturation" },
            { "ColorChooser.hslTransparency.textAndMnemonic", "Transparence" },
            { "ColorChooser.hsv.textAndMnemonic", "&TSV" },
            { "ColorChooser.hsvHue.textAndMnemonic", "Teinte" },
            { "ColorChooser.hsvSaturation.textAndMnemonic", "Saturation" },
            { "ColorChooser.hsvTransparency.textAndMnemonic", "Transparence" },
            { "ColorChooser.hsvValue.textAndMnemonic", "Valeur" },
            { "ColorChooser.ok.textAndMnemonic", "OK" },
            { "ColorChooser.preview.textAndMnemonic", "Aper\u00E7u" },
            { "ColorChooser.reset.textAndMnemonic", "&R\u00E9initialiser" },
            { "ColorChooser.rgb.textAndMnemonic", "R&VB" },
            { "ColorChooser.rgbAlpha.textAndMnemonic", "Alpha" },
            { "ColorChooser.rgbBlue.textAndMnemonic", "&Bleu" },
            { "ColorChooser.rgbGreen.textAndMnemonic", "&Vert" },
            { "ColorChooser.rgbHexCode.textAndMnemonic", "&Code couleur" },
            { "ColorChooser.rgbRed.textAndMnemonic", "R&ouge" },
            { "ColorChooser.sample.textAndMnemonic", "Echantillon de texte  Echantillon de texte" },
            { "ColorChooser.swatches.textAndMnemonic", "&Echantillons" },
            { "ColorChooser.swatchesRecent.textAndMnemonic", "Dernier :" },
            { "ComboBox.togglePopup.textAndMnemonic", "togglePopup" },
            { "FileChooser.acceptAllFileFilter.textAndMnemonic", "Tous les fichiers" },
            { "FileChooser.cancelButton.textAndMnemonic", "Annuler" },
            { "FileChooser.cancelButtonToolTip.textAndMnemonic", "Ferme la bo\u00EEte de dialogue du s\u00E9lecteur de fichiers" },
            { "FileChooser.directoryDescription.textAndMnemonic", "R\u00E9pertoire" },
            { "FileChooser.directoryOpenButton.textAndMnemonic", "Ouvrir" },
            { "FileChooser.directoryOpenButtonToolTip.textAndMnemonic", "Ouvre le r\u00E9pertoire s\u00E9lectionn\u00E9" },
            { "FileChooser.fileDescription.textAndMnemonic", "Fichier g\u00E9n\u00E9rique" },
            { "FileChooser.fileSizeGigaBytes", "{0} GB" },
            { "FileChooser.fileSizeKiloBytes", "{0} KB" },
            { "FileChooser.fileSizeMegaBytes", "{0} MB" },
            { "FileChooser.filesDetailsAccessibleName", "D\u00E9tails des fichiers" },
            { "FileChooser.filesListAccessibleName", "Liste des fichiers" },
            { "FileChooser.helpButton.textAndMnemonic", "&Aide" },
            { "FileChooser.helpButtonToolTip.textAndMnemonic", "Aide du s\u00E9lecteur de fichiers" },
            { "FileChooser.newFolderError.textAndMnemonic", "Erreur lors de la cr\u00E9ation du dossier" },
            { "FileChooser.newFolderErrorSeparator", ":" },
            { "FileChooser.newFolderParentDoesntExist.textAndMnemonic", "Impossible de cr\u00E9er le dossier.\n\nLe syst\u00E8me ne parvient pas \u00E0 trouver le chemin indiqu\u00E9." },
            { "FileChooser.newFolderParentDoesntExistTitle.textAndMnemonic", "Impossible de cr\u00E9er le dossier" },
            { "FileChooser.openButton.textAndMnemonic", "Ouvrir" },
            { "FileChooser.openButtonToolTip.textAndMnemonic", "Ouvre le fichier s\u00E9lectionn\u00E9" },
            { "FileChooser.openDialogTitle.textAndMnemonic", "Ouvrir" },
            { "FileChooser.other.newFolder", "NewFolder" },
            { "FileChooser.other.newFolder.subsequent", "NewFolder.{0}" },
            { "FileChooser.renameError.textAndMnemonic", "Impossible de renommer {0}" },
            { "FileChooser.renameErrorFileExists.textAndMnemonic", "Impossible de renommer {0} : il existe d\u00E9j\u00E0 un fichier portant le nom indiqu\u00E9. Indiquez-en un autre. " },
            { "FileChooser.renameErrorTitle.textAndMnemonic", "Erreur lors du changement de nom du fichier ou du dossier" },
            { "FileChooser.saveButton.textAndMnemonic", "Enregistrer" },
            { "FileChooser.saveButtonToolTip.textAndMnemonic", "Enregistre le fichier s\u00E9lectionn\u00E9" },
            { "FileChooser.saveDialogTitle.textAndMnemonic", "Enregistrer" },
            { "FileChooser.updateButton.textAndMnemonic", "Mettre \u00E0 jo&ur" },
            { "FileChooser.updateButtonToolTip.textAndMnemonic", "Met \u00E0 jour la liste des r\u00E9pertoires" },
            { "FileChooser.win32.newFolder", "Nouveau dossier" },
            { "FileChooser.win32.newFolder.subsequent", "Nouveau dossier ({0})" },
            { "FormView.browseFileButton.textAndMnemonic", "Parcourir..." },
            { "FormView.resetButton.textAndMnemonic", "R\u00E9initialiser" },
            { "FormView.submitButton.textAndMnemonic", "Soumettre la requ\u00EAte" },
            { "InternalFrame.closeButtonToolTip", "Fermer" },
            { "InternalFrame.iconButtonToolTip", "R\u00E9duire" },
            { "InternalFrame.maxButtonToolTip", "Agrandir" },
            { "InternalFrame.restoreButtonToolTip", "Restaurer" },
            { "InternalFrameTitlePane.closeButton.textAndMnemonic", "&Fermer" },
            { "InternalFrameTitlePane.closeButtonAccessibleName", "Fermer" },
            { "InternalFrameTitlePane.iconifyButtonAccessibleName", "R\u00E9duire" },
            { "InternalFrameTitlePane.maximizeButton.textAndMnemonic", "&Agrandir" },
            { "InternalFrameTitlePane.maximizeButtonAccessibleName", "Agrandir" },
            { "InternalFrameTitlePane.minimizeButton.textAndMnemonic", "&R\u00E9duire" },
            { "InternalFrameTitlePane.moveButton.textAndMnemonic", "D\u00E9p&lacer" },
            { "InternalFrameTitlePane.restoreButton.textAndMnemonic", "&Restaurer" },
            { "InternalFrameTitlePane.sizeButton.textAndMnemonic", "Re&dimensionner" },
            { "IsindexView.prompt", "Ceci est un index de recherche. Tapez des mots-cl\u00E9s pour la recherche :" },
            { "OptionPane.cancelButton.textAndMnemonic", "Annuler" },
            { "OptionPane.inputDialog.titleAndMnemonic", "Entr\u00E9e" },
            { "OptionPane.messageDialog.titleAndMnemonic", "Message" },
            { "OptionPane.noButton.textAndMnemonic", "&Non" },
            { "OptionPane.okButton.textAndMnemonic", "OK" },
            { "OptionPane.title.textAndMnemonic", "S\u00E9lectionner une option" },
            { "OptionPane.yesButton.textAndMnemonic", "&Oui" },
            { "PrintingDialog.abortButton.textAndMnemonic", "&Abandonner" },
            { "PrintingDialog.abortButtonToolTip.textAndMnemonic", "Abandonner l'impression" },
            { "PrintingDialog.contentAborting.textAndMnemonic", "Abandon de l'impression..." },
            { "PrintingDialog.contentInitial.textAndMnemonic", "Impression en cours..." },
            { "PrintingDialog.contentProgress.textAndMnemonic", "Page {0} imprim\u00E9e..." },
            { "PrintingDialog.titleAborting.textAndMnemonic", "Impression (abandon)" },
            { "PrintingDialog.titleProgress.textAndMnemonic", "Impression" },
            { "ProgressMonitor.progress.textAndMnemonic", "Progression..." },
            { "SplitPane.leftButton.textAndMnemonic", "bouton gauche" },
            { "SplitPane.rightButton.textAndMnemonic", "bouton droit" },
        };
    }
}
