package com.sun.swing.internal.plaf.basic.resources;

import java.util.ListResourceBundle;

public final class basic_de extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "AbstractButton.click.textAndMnemonic", "Klicken" },
            { "AbstractDocument.addition.textAndMnemonic", "Hinzuf\u00FCgen" },
            { "AbstractDocument.deletion.textAndMnemonic", "L\u00F6schen" },
            { "AbstractDocument.redo.textAndMnemonic", "Wiederherstellen" },
            { "AbstractDocument.styleChange.textAndMnemonic", "Formatvorlagen\u00E4nderung" },
            { "AbstractDocument.undo.textAndMnemonic", "R\u00FCckg\u00E4ngig" },
            { "AbstractUndoableEdit.redo.textAndMnemonic", "Wiederherstellen" },
            { "AbstractUndoableEdit.undo.textAndMnemonic", "R\u00FCckg\u00E4ngig" },
            { "ColorChooser.cancel.textAndMnemonic", "Abbrechen" },
            { "ColorChooser.cmyk.textAndMnemonic", "C&MYK" },
            { "ColorChooser.cmykAlpha.textAndMnemonic", "Alpha" },
            { "ColorChooser.cmykBlack.textAndMnemonic", "Schwarz" },
            { "ColorChooser.cmykCyan.textAndMnemonic", "Zyan" },
            { "ColorChooser.cmykMagenta.textAndMnemonic", "Magenta" },
            { "ColorChooser.cmykYellow.textAndMnemonic", "Gelb" },
            { "ColorChooser.hsl.textAndMnemonic", "HS&L" },
            { "ColorChooser.hslHue.textAndMnemonic", "Farbton" },
            { "ColorChooser.hslLightness.textAndMnemonic", "Helligkeit" },
            { "ColorChooser.hslSaturation.textAndMnemonic", "S\u00E4ttigung" },
            { "ColorChooser.hslTransparency.textAndMnemonic", "Transparenz" },
            { "ColorChooser.hsv.textAndMnemonic", "&HSV" },
            { "ColorChooser.hsvHue.textAndMnemonic", "Farbton" },
            { "ColorChooser.hsvSaturation.textAndMnemonic", "S\u00E4ttigung" },
            { "ColorChooser.hsvTransparency.textAndMnemonic", "Transparenz" },
            { "ColorChooser.hsvValue.textAndMnemonic", "Wert" },
            { "ColorChooser.ok.textAndMnemonic", "OK" },
            { "ColorChooser.preview.textAndMnemonic", "Vorschau" },
            { "ColorChooser.reset.textAndMnemonic", "&Zur\u00FCcksetzen" },
            { "ColorChooser.rgb.textAndMnemonic", "R&GB" },
            { "ColorChooser.rgbAlpha.textAndMnemonic", "Alpha" },
            { "ColorChooser.rgbBlue.textAndMnemonic", "&Blau" },
            { "ColorChooser.rgbGreen.textAndMnemonic", "Gr\u00FC&n" },
            { "ColorChooser.rgbHexCode.textAndMnemonic", "&Farbcode" },
            { "ColorChooser.rgbRed.textAndMnemonic", "Ro&t" },
            { "ColorChooser.sample.textAndMnemonic", "Beispieltext  Beispieltext" },
            { "ColorChooser.swatches.textAndMnemonic", "&Swatches" },
            { "ColorChooser.swatchesRecent.textAndMnemonic", "Aktuell:" },
            { "ComboBox.togglePopup.textAndMnemonic", "togglePopup" },
            { "FileChooser.acceptAllFileFilter.textAndMnemonic", "Alle Dateien" },
            { "FileChooser.cancelButton.textAndMnemonic", "Abbrechen" },
            { "FileChooser.cancelButtonToolTip.textAndMnemonic", "Dialogfeld f\u00FCr Dateiauswahl schlie\u00DFen" },
            { "FileChooser.directoryDescription.textAndMnemonic", "Verzeichnis" },
            { "FileChooser.directoryOpenButton.textAndMnemonic", "\u00D6ffnen" },
            { "FileChooser.directoryOpenButtonToolTip.textAndMnemonic", "Ausgew\u00E4hltes Verzeichnis \u00F6ffnen" },
            { "FileChooser.fileDescription.textAndMnemonic", "Allgemeine Datei" },
            { "FileChooser.fileSizeGigaBytes", "{0} GB" },
            { "FileChooser.fileSizeKiloBytes", "{0} KB" },
            { "FileChooser.fileSizeMegaBytes", "{0} MB" },
            { "FileChooser.filesDetailsAccessibleName", "Dateidetails" },
            { "FileChooser.filesListAccessibleName", "Dateiliste" },
            { "FileChooser.helpButton.textAndMnemonic", "&Hilfe" },
            { "FileChooser.helpButtonToolTip.textAndMnemonic", "FileChooser-Hilfe" },
            { "FileChooser.newFolderError.textAndMnemonic", "Fehler beim Erstellen eines neuen Ordners" },
            { "FileChooser.newFolderErrorSeparator", ":" },
            { "FileChooser.newFolderParentDoesntExist.textAndMnemonic", "Ordner kann nicht erstellt werden.\n\nSystem kann den angegebenen Pfad nicht finden." },
            { "FileChooser.newFolderParentDoesntExistTitle.textAndMnemonic", "Ordner kann nicht erstellt werden" },
            { "FileChooser.openButton.textAndMnemonic", "\u00D6ffnen" },
            { "FileChooser.openButtonToolTip.textAndMnemonic", "Ausgew\u00E4hlte Datei \u00F6ffnen" },
            { "FileChooser.openDialogTitle.textAndMnemonic", "\u00D6ffnen" },
            { "FileChooser.other.newFolder", "NewFolder" },
            { "FileChooser.other.newFolder.subsequent", "NewFolder.{0}" },
            { "FileChooser.renameError.textAndMnemonic", "{0} kann nicht umbenannt werden" },
            { "FileChooser.renameErrorFileExists.textAndMnemonic", "{0} kann nicht umbenannt werden: Es ist bereits eine Datei mit dem angegebenen Namen vorhanden. Geben Sie einen anderen Dateinamen an. " },
            { "FileChooser.renameErrorTitle.textAndMnemonic", "Fehler beim Umbenennen von Datei oder Ordner" },
            { "FileChooser.saveButton.textAndMnemonic", "Speichern" },
            { "FileChooser.saveButtonToolTip.textAndMnemonic", "Ausgew\u00E4hlte Datei speichern" },
            { "FileChooser.saveDialogTitle.textAndMnemonic", "Speichern" },
            { "FileChooser.updateButton.textAndMnemonic", "A&ktualisieren" },
            { "FileChooser.updateButtonToolTip.textAndMnemonic", "Verzeichnisliste aktualisieren" },
            { "FileChooser.win32.newFolder", "Neuer Ordner" },
            { "FileChooser.win32.newFolder.subsequent", "Neuer Ordner ({0})" },
            { "FormView.browseFileButton.textAndMnemonic", "Durchsuchen..." },
            { "FormView.resetButton.textAndMnemonic", "Zur\u00FCcksetzen" },
            { "FormView.submitButton.textAndMnemonic", "Abfrage weiterleiten" },
            { "InternalFrame.closeButtonToolTip", "Schlie\u00DFen" },
            { "InternalFrame.iconButtonToolTip", "Minimieren" },
            { "InternalFrame.maxButtonToolTip", "Maximieren" },
            { "InternalFrame.restoreButtonToolTip", "Wiederherstellen" },
            { "InternalFrameTitlePane.closeButton.textAndMnemonic", "&Schlie\u00DFen" },
            { "InternalFrameTitlePane.closeButtonAccessibleName", "Schlie\u00DFen" },
            { "InternalFrameTitlePane.iconifyButtonAccessibleName", "Als Symbol darstellen" },
            { "InternalFrameTitlePane.maximizeButton.textAndMnemonic", "Ma&ximieren" },
            { "InternalFrameTitlePane.maximizeButtonAccessibleName", "Maximieren" },
            { "InternalFrameTitlePane.minimizeButton.textAndMnemonic", "Mi&nimieren" },
            { "InternalFrameTitlePane.moveButton.textAndMnemonic", "&Verschieben" },
            { "InternalFrameTitlePane.restoreButton.textAndMnemonic", "&Wiederherstellen" },
            { "InternalFrameTitlePane.sizeButton.textAndMnemonic", "&Gr\u00F6\u00DFe" },
            { "IsindexView.prompt", "Dieser Index kann durchsucht werden. Geben Sie Schl\u00FCsselw\u00F6rter f\u00FCr die Suche ein:" },
            { "OptionPane.cancelButton.textAndMnemonic", "Abbrechen" },
            { "OptionPane.inputDialog.titleAndMnemonic", "Eingabe" },
            { "OptionPane.messageDialog.titleAndMnemonic", "Meldung" },
            { "OptionPane.noButton.textAndMnemonic", "&Nein" },
            { "OptionPane.okButton.textAndMnemonic", "OK" },
            { "OptionPane.title.textAndMnemonic", "Option ausw\u00E4hlen" },
            { "OptionPane.yesButton.textAndMnemonic", "&Ja" },
            { "PrintingDialog.abortButton.textAndMnemonic", "&Abbruch" },
            { "PrintingDialog.abortButtonToolTip.textAndMnemonic", "Druckvorgang abbrechen" },
            { "PrintingDialog.contentAborting.textAndMnemonic", "Druckvorgang wird abgebrochen..." },
            { "PrintingDialog.contentInitial.textAndMnemonic", "Druckvorgang l\u00E4uft..." },
            { "PrintingDialog.contentProgress.textAndMnemonic", "Seite {0} wurde gedruckt..." },
            { "PrintingDialog.titleAborting.textAndMnemonic", "Drucken (Abbruch)" },
            { "PrintingDialog.titleProgress.textAndMnemonic", "Drucken" },
            { "ProgressMonitor.progress.textAndMnemonic", "Fortschritt..." },
            { "SplitPane.leftButton.textAndMnemonic", "linke Schaltfl\u00E4che" },
            { "SplitPane.rightButton.textAndMnemonic", "rechte Schaltfl\u00E4che" },
        };
    }
}
