package com.sun.swing.internal.plaf.basic.resources;

import java.util.ListResourceBundle;

public final class basic_pt_BR extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "AbstractButton.click.textAndMnemonic", "clicar" },
            { "AbstractDocument.addition.textAndMnemonic", "adi\u00E7\u00E3o" },
            { "AbstractDocument.deletion.textAndMnemonic", "exclus\u00E3o" },
            { "AbstractDocument.redo.textAndMnemonic", "Refazer" },
            { "AbstractDocument.styleChange.textAndMnemonic", "altera\u00E7\u00E3o de estilo" },
            { "AbstractDocument.undo.textAndMnemonic", "Desfazer" },
            { "AbstractUndoableEdit.redo.textAndMnemonic", "Refazer" },
            { "AbstractUndoableEdit.undo.textAndMnemonic", "Desfazer" },
            { "ColorChooser.cancel.textAndMnemonic", "Cancelar" },
            { "ColorChooser.cmyk.textAndMnemonic", "C&MYK" },
            { "ColorChooser.cmykAlpha.textAndMnemonic", "Alfa" },
            { "ColorChooser.cmykBlack.textAndMnemonic", "Preto" },
            { "ColorChooser.cmykCyan.textAndMnemonic", "Ciano" },
            { "ColorChooser.cmykMagenta.textAndMnemonic", "Magenta" },
            { "ColorChooser.cmykYellow.textAndMnemonic", "Amarelo" },
            { "ColorChooser.hsl.textAndMnemonic", "HS&L" },
            { "ColorChooser.hslHue.textAndMnemonic", "Matiz" },
            { "ColorChooser.hslLightness.textAndMnemonic", "Clareza" },
            { "ColorChooser.hslSaturation.textAndMnemonic", "Satura\u00E7\u00E3o" },
            { "ColorChooser.hslTransparency.textAndMnemonic", "Transpar\u00EAncia" },
            { "ColorChooser.hsv.textAndMnemonic", "&HSV" },
            { "ColorChooser.hsvHue.textAndMnemonic", "Matiz" },
            { "ColorChooser.hsvSaturation.textAndMnemonic", "Satura\u00E7\u00E3o" },
            { "ColorChooser.hsvTransparency.textAndMnemonic", "Transpar\u00EAncia" },
            { "ColorChooser.hsvValue.textAndMnemonic", "Valor" },
            { "ColorChooser.ok.textAndMnemonic", "OK" },
            { "ColorChooser.preview.textAndMnemonic", "Visualizar" },
            { "ColorChooser.reset.textAndMnemonic", "&Redefinir" },
            { "ColorChooser.rgb.textAndMnemonic", "R&GB" },
            { "ColorChooser.rgbAlpha.textAndMnemonic", "Alfa" },
            { "ColorChooser.rgbBlue.textAndMnemonic", "&Azul" },
            { "ColorChooser.rgbGreen.textAndMnemonic", "&Verde" },
            { "ColorChooser.rgbHexCode.textAndMnemonic", "&C\u00F3digo da Cor" },
            { "ColorChooser.rgbRed.textAndMnemonic", "&Vermelho" },
            { "ColorChooser.sample.textAndMnemonic", "Texto de Amostra Texto de Amostra" },
            { "ColorChooser.swatches.textAndMnemonic", "Amo&stras" },
            { "ColorChooser.swatchesRecent.textAndMnemonic", "Recente:" },
            { "ComboBox.togglePopup.textAndMnemonic", "togglePopup" },
            { "FileChooser.acceptAllFileFilter.textAndMnemonic", "Todos os Arquivos" },
            { "FileChooser.cancelButton.textAndMnemonic", "Cancelar" },
            { "FileChooser.cancelButtonToolTip.textAndMnemonic", "Abortar caixa de di\u00E1logo do seletor de arquivos" },
            { "FileChooser.directoryDescription.textAndMnemonic", "Diret\u00F3rio" },
            { "FileChooser.directoryOpenButton.textAndMnemonic", "Abrir" },
            { "FileChooser.directoryOpenButtonToolTip.textAndMnemonic", "Abrir diret\u00F3rio selecionado" },
            { "FileChooser.fileDescription.textAndMnemonic", "Arquivo Gen\u00E9rico" },
            { "FileChooser.fileSizeGigaBytes", "{0} GB" },
            { "FileChooser.fileSizeKiloBytes", "{0} KB" },
            { "FileChooser.fileSizeMegaBytes", "{0} MB" },
            { "FileChooser.filesDetailsAccessibleName", "Detalhes do Arquivo" },
            { "FileChooser.filesListAccessibleName", "Lista de Arquivos" },
            { "FileChooser.helpButton.textAndMnemonic", "Aj&uda" },
            { "FileChooser.helpButtonToolTip.textAndMnemonic", "Ajuda do FileChooser" },
            { "FileChooser.newFolderError.textAndMnemonic", "Erro ao criar nova pasta" },
            { "FileChooser.newFolderErrorSeparator", ":" },
            { "FileChooser.newFolderParentDoesntExist.textAndMnemonic", "N\u00E3o \u00E9 poss\u00EDvel criar a pasta.\n\nO sistema n\u00E3o pode localizar o caminho especificado." },
            { "FileChooser.newFolderParentDoesntExistTitle.textAndMnemonic", "N\u00E3o \u00E9 poss\u00EDvel criar a pasta" },
            { "FileChooser.openButton.textAndMnemonic", "Abrir" },
            { "FileChooser.openButtonToolTip.textAndMnemonic", "Abrir arquivo selecionado" },
            { "FileChooser.openDialogTitle.textAndMnemonic", "Abrir" },
            { "FileChooser.other.newFolder", "NewFolder" },
            { "FileChooser.other.newFolder.subsequent", "NewFolder.{0}" },
            { "FileChooser.renameError.textAndMnemonic", "N\u00E3o \u00E9 poss\u00EDvel renomear {0}" },
            { "FileChooser.renameErrorFileExists.textAndMnemonic", "N\u00E3o \u00E9 poss\u00EDvel renomear {0}: Um arquivo com o nome especificado j\u00E1 existe. Especifique outro nome de arquivo." },
            { "FileChooser.renameErrorTitle.textAndMnemonic", "Erro ao Renomear o Arquivo ou a Pasta" },
            { "FileChooser.saveButton.textAndMnemonic", "Salvar" },
            { "FileChooser.saveButtonToolTip.textAndMnemonic", "Salvar arquivo selecionado" },
            { "FileChooser.saveDialogTitle.textAndMnemonic", "Salvar" },
            { "FileChooser.updateButton.textAndMnemonic", "At&ualizar" },
            { "FileChooser.updateButtonToolTip.textAndMnemonic", "Atualizar lista de diret\u00F3rios" },
            { "FileChooser.win32.newFolder", "Nova Pasta" },
            { "FileChooser.win32.newFolder.subsequent", "Nova Pasta ({0})" },
            { "FormView.browseFileButton.textAndMnemonic", "Procurar..." },
            { "FormView.resetButton.textAndMnemonic", "Redefinir" },
            { "FormView.submitButton.textAndMnemonic", "Submeter Consulta" },
            { "InternalFrame.closeButtonToolTip", "Fechar" },
            { "InternalFrame.iconButtonToolTip", "Minimizar" },
            { "InternalFrame.maxButtonToolTip", "Maximizar" },
            { "InternalFrame.restoreButtonToolTip", "Restaurar" },
            { "InternalFrameTitlePane.closeButton.textAndMnemonic", "&Fechar" },
            { "InternalFrameTitlePane.closeButtonAccessibleName", "Fechar" },
            { "InternalFrameTitlePane.iconifyButtonAccessibleName", "Iconizar" },
            { "InternalFrameTitlePane.maximizeButton.textAndMnemonic", "Ma&ximizar" },
            { "InternalFrameTitlePane.maximizeButtonAccessibleName", "Maximizar" },
            { "InternalFrameTitlePane.minimizeButton.textAndMnemonic", "Mi&nimizar" },
            { "InternalFrameTitlePane.moveButton.textAndMnemonic", "&Mover" },
            { "InternalFrameTitlePane.restoreButton.textAndMnemonic", "&Restaurar" },
            { "InternalFrameTitlePane.sizeButton.textAndMnemonic", "&Dimensionar" },
            { "IsindexView.prompt", "Trata-se de um \u00EDndice pesquis\u00E1vel. Informe as palavras-chave de pesquisa:" },
            { "OptionPane.cancelButton.textAndMnemonic", "Cancelar" },
            { "OptionPane.inputDialog.titleAndMnemonic", "Entrada" },
            { "OptionPane.messageDialog.titleAndMnemonic", "Mensagem" },
            { "OptionPane.noButton.textAndMnemonic", "&N\u00E3o" },
            { "OptionPane.okButton.textAndMnemonic", "OK" },
            { "OptionPane.title.textAndMnemonic", "Selecionar uma Op\u00E7\u00E3o" },
            { "OptionPane.yesButton.textAndMnemonic", "&Sim" },
            { "PrintingDialog.abortButton.textAndMnemonic", "&Abortar" },
            { "PrintingDialog.abortButtonToolTip.textAndMnemonic", "Abortar Impress\u00E3o" },
            { "PrintingDialog.contentAborting.textAndMnemonic", "Abortando impress\u00E3o..." },
            { "PrintingDialog.contentInitial.textAndMnemonic", "Impress\u00E3o em andamento..." },
            { "PrintingDialog.contentProgress.textAndMnemonic", "P\u00E1gina impressa {0}..." },
            { "PrintingDialog.titleAborting.textAndMnemonic", "Impress\u00E3o (Abortando)" },
            { "PrintingDialog.titleProgress.textAndMnemonic", "Impress\u00E3o" },
            { "ProgressMonitor.progress.textAndMnemonic", "Andamento..." },
            { "SplitPane.leftButton.textAndMnemonic", "bot\u00E3o esquerdo" },
            { "SplitPane.rightButton.textAndMnemonic", "bot\u00E3o direito" },
        };
    }
}
