package com.sun.swing.internal.plaf.basic.resources;

import java.util.ListResourceBundle;

public final class basic_it extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "AbstractButton.click.textAndMnemonic", "fare clic" },
            { "AbstractDocument.addition.textAndMnemonic", "aggiunta" },
            { "AbstractDocument.deletion.textAndMnemonic", "eliminazione" },
            { "AbstractDocument.redo.textAndMnemonic", "Ripeti" },
            { "AbstractDocument.styleChange.textAndMnemonic", "modifica di stile" },
            { "AbstractDocument.undo.textAndMnemonic", "Annulla" },
            { "AbstractUndoableEdit.redo.textAndMnemonic", "Ripeti" },
            { "AbstractUndoableEdit.undo.textAndMnemonic", "Annulla" },
            { "ColorChooser.cancel.textAndMnemonic", "Annulla" },
            { "ColorChooser.cmyk.textAndMnemonic", "C&MYK" },
            { "ColorChooser.cmykAlpha.textAndMnemonic", "Alfa" },
            { "ColorChooser.cmykBlack.textAndMnemonic", "Nero" },
            { "ColorChooser.cmykCyan.textAndMnemonic", "Ciano" },
            { "ColorChooser.cmykMagenta.textAndMnemonic", "Magenta" },
            { "ColorChooser.cmykYellow.textAndMnemonic", "Giallo" },
            { "ColorChooser.hsl.textAndMnemonic", "HS&L" },
            { "ColorChooser.hslHue.textAndMnemonic", "Tonalit\u00E0" },
            { "ColorChooser.hslLightness.textAndMnemonic", "Luminosit\u00E0" },
            { "ColorChooser.hslSaturation.textAndMnemonic", "Saturazione" },
            { "ColorChooser.hslTransparency.textAndMnemonic", "Trasparenza" },
            { "ColorChooser.hsv.textAndMnemonic", "&HSV" },
            { "ColorChooser.hsvHue.textAndMnemonic", "Tonalit\u00E0" },
            { "ColorChooser.hsvSaturation.textAndMnemonic", "Saturazione" },
            { "ColorChooser.hsvTransparency.textAndMnemonic", "Trasparenza" },
            { "ColorChooser.hsvValue.textAndMnemonic", "Valore" },
            { "ColorChooser.ok.textAndMnemonic", "OK" },
            { "ColorChooser.preview.textAndMnemonic", "Anteprima" },
            { "ColorChooser.reset.textAndMnemonic", "&Reimposta" },
            { "ColorChooser.rgb.textAndMnemonic", "R&GB" },
            { "ColorChooser.rgbAlpha.textAndMnemonic", "Alfa" },
            { "ColorChooser.rgbBlue.textAndMnemonic", "&Blu" },
            { "ColorChooser.rgbGreen.textAndMnemonic", "Ver&de" },
            { "ColorChooser.rgbHexCode.textAndMnemonic", "&Codice colori" },
            { "ColorChooser.rgbRed.textAndMnemonic", "Ro&sso" },
            { "ColorChooser.sample.textAndMnemonic", "Testo di prova          Testo di prova" },
            { "ColorChooser.swatches.textAndMnemonic", "Colori cam&pione" },
            { "ColorChooser.swatchesRecent.textAndMnemonic", "Recenti:" },
            { "ComboBox.togglePopup.textAndMnemonic", "togglePopup" },
            { "FileChooser.acceptAllFileFilter.textAndMnemonic", "Tutti i file" },
            { "FileChooser.cancelButton.textAndMnemonic", "Annulla" },
            { "FileChooser.cancelButtonToolTip.textAndMnemonic", "Chiude la finestra di dialogo di selezione file" },
            { "FileChooser.directoryDescription.textAndMnemonic", "Directory" },
            { "FileChooser.directoryOpenButton.textAndMnemonic", "Apri" },
            { "FileChooser.directoryOpenButtonToolTip.textAndMnemonic", "Apre la directory selezionata" },
            { "FileChooser.fileDescription.textAndMnemonic", "File generico" },
            { "FileChooser.fileSizeGigaBytes", "{0} GB" },
            { "FileChooser.fileSizeKiloBytes", "{0} KB" },
            { "FileChooser.fileSizeMegaBytes", "{0} MB" },
            { "FileChooser.filesDetailsAccessibleName", "Dettagli file" },
            { "FileChooser.filesListAccessibleName", "Lista dei file" },
            { "FileChooser.helpButton.textAndMnemonic", "&?" },
            { "FileChooser.helpButtonToolTip.textAndMnemonic", "Guida FileChooser" },
            { "FileChooser.newFolderError.textAndMnemonic", "Errore durante la creazione della nuova cartella" },
            { "FileChooser.newFolderErrorSeparator", ":" },
            { "FileChooser.newFolderParentDoesntExist.textAndMnemonic", "Impossibile creare la cartella.\n\nIl sistema non \u00E8 in grado di trovare il percorso specificato." },
            { "FileChooser.newFolderParentDoesntExistTitle.textAndMnemonic", "Impossibile creare la cartella" },
            { "FileChooser.openButton.textAndMnemonic", "Apri" },
            { "FileChooser.openButtonToolTip.textAndMnemonic", "Apre il file selezionato" },
            { "FileChooser.openDialogTitle.textAndMnemonic", "Apri" },
            { "FileChooser.other.newFolder", "NewFolder" },
            { "FileChooser.other.newFolder.subsequent", "NewFolder.{0}" },
            { "FileChooser.renameError.textAndMnemonic", "Impossibile rinominare {0}" },
            { "FileChooser.renameErrorFileExists.textAndMnemonic", "Impossibile rinominare {0}: esiste gi\u00E0 un file con il nome specificato. Specificare un altro nome. " },
            { "FileChooser.renameErrorTitle.textAndMnemonic", "Errore durante la ridenominazione del file o della cartella" },
            { "FileChooser.saveButton.textAndMnemonic", "Salva" },
            { "FileChooser.saveButtonToolTip.textAndMnemonic", "Salva il file selezionato" },
            { "FileChooser.saveDialogTitle.textAndMnemonic", "Salva" },
            { "FileChooser.updateButton.textAndMnemonic", "Ag&giorna" },
            { "FileChooser.updateButtonToolTip.textAndMnemonic", "Aggiorna la lista directory" },
            { "FileChooser.win32.newFolder", "Nuova cartella" },
            { "FileChooser.win32.newFolder.subsequent", "Nuova cartella ({0})" },
            { "FormView.browseFileButton.textAndMnemonic", "Sfoglia..." },
            { "FormView.resetButton.textAndMnemonic", "Reimposta" },
            { "FormView.submitButton.textAndMnemonic", "Sottometti query" },
            { "InternalFrame.closeButtonToolTip", "Chiudi" },
            { "InternalFrame.iconButtonToolTip", "Riduci a icona" },
            { "InternalFrame.maxButtonToolTip", "Ingrandisci" },
            { "InternalFrame.restoreButtonToolTip", "Ripristina" },
            { "InternalFrameTitlePane.closeButton.textAndMnemonic", "&Chiudi" },
            { "InternalFrameTitlePane.closeButtonAccessibleName", "Chiudi" },
            { "InternalFrameTitlePane.iconifyButtonAccessibleName", "Riduci a icona" },
            { "InternalFrameTitlePane.maximizeButton.textAndMnemonic", "In&grandisci" },
            { "InternalFrameTitlePane.maximizeButtonAccessibleName", "Ingrandisci" },
            { "InternalFrameTitlePane.minimizeButton.textAndMnemonic", "Ri&duci a icona" },
            { "InternalFrameTitlePane.moveButton.textAndMnemonic", "&Sposta" },
            { "InternalFrameTitlePane.restoreButton.textAndMnemonic", "&Ripristina" },
            { "InternalFrameTitlePane.sizeButton.textAndMnemonic", "R&idimensiona" },
            { "IsindexView.prompt", "Questo \u00E8 un indice di ricerca. Immettere le parole chiave:" },
            { "OptionPane.cancelButton.textAndMnemonic", "Annulla" },
            { "OptionPane.inputDialog.titleAndMnemonic", "Input" },
            { "OptionPane.messageDialog.titleAndMnemonic", "Messaggio" },
            { "OptionPane.noButton.textAndMnemonic", "&No" },
            { "OptionPane.okButton.textAndMnemonic", "OK" },
            { "OptionPane.title.textAndMnemonic", "Selezionare una opzione" },
            { "OptionPane.yesButton.textAndMnemonic", "&S\u00EC" },
            { "PrintingDialog.abortButton.textAndMnemonic", "I&nterrompi" },
            { "PrintingDialog.abortButtonToolTip.textAndMnemonic", "Interrompi la stampa" },
            { "PrintingDialog.contentAborting.textAndMnemonic", "Interruzione della stampa..." },
            { "PrintingDialog.contentInitial.textAndMnemonic", "Stampa in corso..." },
            { "PrintingDialog.contentProgress.textAndMnemonic", "Pagina stampata {0}..." },
            { "PrintingDialog.titleAborting.textAndMnemonic", "Stampa in corso (operazione interrotta)" },
            { "PrintingDialog.titleProgress.textAndMnemonic", "Stampa in corso" },
            { "ProgressMonitor.progress.textAndMnemonic", "Avanzamento..." },
            { "SplitPane.leftButton.textAndMnemonic", "tasto sinistro" },
            { "SplitPane.rightButton.textAndMnemonic", "tasto destro" },
        };
    }
}
