/*
 * Copyright (c) 1999, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */
package com.sun.org.omg.CORBA;


/**
* com/sun/org/omg/CORBA/VisibilityHelper.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from ir.idl
* Thursday, May 6, 1999 1:51:44 AM PDT
*/


// orbos 98-01-18: Objects By Value -- begin
public final class VisibilityHelper
{
    private static String  _id = "IDL:omg.org/CORBA/Visibility:1.0";

    public VisibilityHelper()
    {
    }

    public static void insert (org.omg.CORBA.Any a, short that)
    {
        org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
        a.type (type ());
        write (out, that);
        a.read_value (out.create_input_stream (), type ());
    }

    public static short extract (org.omg.CORBA.Any a)
    {
        return read (a.create_input_stream ());
    }

    private static org.omg.CORBA.TypeCode __typeCode = null;
    synchronized public static org.omg.CORBA.TypeCode type ()
    {
        if (__typeCode == null)
            {
                __typeCode = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
                __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (com.sun.org.omg.CORBA.VisibilityHelper.id (), "Visibility", __typeCode);
            }
        return __typeCode;
    }

    public static String id ()
    {
        return _id;
    }

    public static short read (org.omg.CORBA.portable.InputStream istream)
    {
        short value = (short)0;
        value = istream.read_short ();
        return value;
    }

    public static void write (org.omg.CORBA.portable.OutputStream ostream, short value)
    {
        ostream.write_short (value);
    }

}
